// FightFolio — MMA Fighters data + copy translations

const FIGHTERS = [
  // ── ÖSTERREICH ────────────────────────────────────────────────────────────
  {
    id: 'aleksandar-rakic',
    name: 'Aleksandar Rakić',
    city: 'Wien',
    country: 'Austria',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Top-10', 'LHW', 'Österreich'],
    weightClass: 'Light Heavyweight',
    record: '14-4-0',
    rating: 4.9,
    reviews: 0,
    featured: true,
    img: ['#1A0A00', '#3D1F00'],
    accentHue: 42,
    sponsors: [
      { name: 'Venum' },
      { name: 'Monster Energy' },
      { name: 'Phantom Athletics' },
      { name: 'A1 Telekom Austria' }
    ],
  },
  {
    id: 'ismail-naurdiev',
    name: 'Ismail Naurdiev',
    city: 'Wien',
    country: 'Austria',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Welterweight', 'Österreich', 'KO-Artist'],
    weightClass: 'Welterweight',
    record: '16-4-0',
    rating: 4.7,
    reviews: 0,
    img: ['#001A3D', '#003580'],
    accentHue: 210,
    sponsors: [
      { name: 'Gymking' },
      { name: 'Bet-at-home' },
      { name: 'T-Mobile Austria' }
    ],
  },
  {
    id: 'bogdan-grad',
    name: 'Bogdan Grad',
    city: 'Graz',
    country: 'Austria',
    status: 'verified',
    styles: ['Wrestler', 'MMA'],
    tags: ['OKTAGON', 'Heavyweight', 'Steiermark'],
    weightClass: 'Heavyweight',
    record: '13-5-0',
    rating: 4.5,
    reviews: 0,
    img: ['#0A1A00', '#1A3D00'],
    accentHue: 105,
    sponsors: [
      { name: 'Ettl Bros' },
      { name: 'Raiffeisen Sport' },
      { name: 'Nutri-Direct' }
    ],
  },
  {
    id: 'rodrigo-nascimento',
    name: 'Rodrigo Nascimento',
    city: 'Wien',
    country: 'Austria',
    status: 'verified',
    styles: ['Wrestler', 'BJJ'],
    tags: ['UFC', 'Heavyweight', 'Wien', 'Brasilien'],
    weightClass: 'Heavyweight',
    record: '10-2-0',
    rating: 4.6,
    reviews: 0,
    img: ['#1A001A', '#3D003D'],
    accentHue: 300,
    sponsors: [
      { name: 'Venum' },
      { name: 'MHP' },
      { name: 'Cybex' }
    ],
  },
  {
    id: 'florian-aberger',
    name: 'Florian Aberger',
    city: 'Graz',
    country: 'Austria',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['REGIONAL', 'Middleweight', 'Steiermark', 'IMMAF'],
    weightClass: 'Middleweight',
    record: '9-1-0',
    rating: 4.4,
    reviews: 0,
    img: ['#001A00', '#003D00'],
    accentHue: 90,
    sponsors: [
      { name: 'Steiermärkische Sparkasse' },
      { name: 'Hervis Sports' },
      { name: 'Calibian Management' }
    ],
  },
  {
    id: 'wilhelm-ott',
    name: 'Wilhelm Ott',
    city: 'Linz',
    country: 'Austria',
    status: 'self',
    styles: ['Striker', 'MMA'],
    tags: ['REGIONAL', 'Middleweight', 'Linz', 'BKFC'],
    weightClass: 'Middleweight',
    record: '19-19-1',
    rating: 4.0,
    reviews: 0,
    img: ['#0A0A1A', '#1A1A3D'],
    accentHue: 220,
    sponsors: [
      { name: 'Ott Security' },
      { name: 'Empire Sports' }
    ],
  },
  // ── DEUTSCHLAND ───────────────────────────────────────────────────────────
  {
    id: 'christian-eckerlin',
    name: 'Christian Eckerlin',
    city: 'Frankfurt',
    country: 'Germany',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    tags: ['OKTAGON', 'Welterweight', 'Frankfurt', 'King of Frankfurt'],
    weightClass: 'Welterweight',
    record: '28-15-0',
    rating: 4.6,
    reviews: 0,
    img: ['#1A0000', '#3D0000'],
    accentHue: 0,
    sponsors: [
      { name: 'Eckerlin Logistics' },
      { name: 'Mainova' },
      { name: 'König Pilsener' }
    ],
  },
  {
    id: 'kerim-engizek',
    name: 'Kerim Engizek',
    city: 'Düsseldorf',
    country: 'Germany',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    tags: ['OKTAGON', 'Champion', 'Middleweight', 'KO-Artist'],
    weightClass: 'Middleweight',
    record: '21-4-0',
    rating: 4.8,
    reviews: 0,
    img: ['#001A1A', '#003D3D'],
    accentHue: 180,
    sponsors: [
      { name: 'Onyx' },
      { name: 'Bose Germany' },
      { name: 'Snipes' }
    ],
  },
  {
    id: 'nick-hein',
    name: 'Nick Hein',
    city: 'Hamburg',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'BJJ'],
    tags: ['UFC', 'Lightweight', 'Hamburg', 'Judo'],
    weightClass: 'Lightweight',
    record: '13-4-0',
    rating: 4.4,
    reviews: 0,
    img: ['#0A0A1A', '#15153D'],
    accentHue: 240,
    sponsors: [
      { name: 'Sponsoo' },
      { name: 'Under Armour Germany' },
      { name: 'Sky Sport' }
    ],
  },
  {
    id: 'dennis-siver',
    name: 'Dennis Siver',
    city: 'München',
    country: 'Germany',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    tags: ['UFC', 'Featherweight', 'München', 'Veteran'],
    weightClass: 'Featherweight',
    record: '24-13-0',
    rating: 4.3,
    reviews: 0,
    img: ['#1A0A1A', '#3D1A3D'],
    accentHue: 280,
    sponsors: [
      { name: 'Kwon' },
      { name: 'FitX' }
    ],
  },
  {
    id: 'daniel-weichel',
    name: 'Daniel Weichel',
    city: 'Frankfurt',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['Bellator', 'OKTAGON', 'Featherweight', 'M-1 Global'],
    weightClass: 'Featherweight',
    record: '45-14-0',
    rating: 4.5,
    reviews: 0,
    img: ['#1A0A00', '#3D1800'],
    accentHue: 15,
    sponsors: [
      { name: 'Spirit MMA' },
      { name: 'Matrix Fitness' },
      { name: 'Lonsdale Germany' }
    ],
  },
  {
    id: 'joilton-lutterbach',
    name: 'Joilton Lutterbach',
    city: 'Köln',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'OKTAGON', 'Middleweight', 'Köln'],
    weightClass: 'Middleweight',
    record: '41-11-0',
    rating: 4.3,
    reviews: 0,
    img: ['#001A18', '#003D33'],
    accentHue: 170,
    sponsors: [
      { name: 'Paffensport' },
      { name: 'Zec+ Nutrition' },
      { name: 'MyProtein' }
    ],
  },
  {
    id: 'frederic-vosgrone',
    name: 'Frédéric Vosgröne',
    city: 'Düsseldorf',
    country: 'Germany',
    status: 'verified',
    styles: ['BJJ', 'Grappler'],
    tags: ['OKTAGON', 'Light Heavyweight', 'BJJ World Champ', 'ADCC'],
    weightClass: 'Light Heavyweight',
    record: '5-0-0',
    rating: 4.6,
    reviews: 0,
    img: ['#0D001A', '#20003D'],
    accentHue: 270,
    sponsors: [
      { name: 'UFD Gym' },
      { name: 'Olimp Sport Nutrition' }
    ],
  },
  {
    id: 'sascha-sharma',
    name: 'Sascha Sharma',
    city: 'Stuttgart',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'BJJ'],
    tags: ['TUF', 'Lightweight', 'Pforzheim', 'Kong\'s Gym'],
    weightClass: 'Lightweight',
    record: '17-5-0',
    rating: 4.1,
    reviews: 0,
    img: ['#1A1200', '#3D2A00'],
    accentHue: 35,
    sponsors: [
      { name: 'Stallion Gym' },
      { name: 'Vayumedia' }
    ],
  },
  {
    id: 'sebastian-holzmann',
    name: 'Sebastian Holzmann',
    city: 'Leipzig',
    country: 'Germany',
    status: 'self',
    styles: ['Striker', 'MMA'],
    tags: ['REGIONAL', 'Lightweight', 'Halle', 'Sachsen-Anhalt'],
    weightClass: 'Lightweight',
    record: '6-2-0',
    rating: 3.9,
    reviews: 0,
    img: ['#001218', '#002030'],
    accentHue: 200,
    sponsors: [
      { name: 'Leipzig Lions' },
      { name: 'Power & Fitness Shop' }
    ],
  },
  // ── SPANIEN ───────────────────────────────────────────────────────────────
  {
    id: 'ilia-topuria',
    name: 'Ilia Topuria',
    city: 'Alicante',
    country: 'Spain',
    status: 'verified',
    styles: ['Striker', 'BJJ'],
    tags: ['UFC', 'Champion', 'Featherweight', 'El Matador'],
    weightClass: 'Featherweight',
    record: '17-0-0',
    rating: 5.0,
    reviews: 0,
    featured: true,
    img: ['#2A0000', '#700000'],
    accentHue: 0,
    stats: { age: 29, height: '170 cm', reach: '175 cm', stance: 'Orthodox', nationality: 'Georgisch-Spanisch', gym: 'Kings MMA', born: 'Tiflis, Georgien' },
    sponsors: [
      { name: 'Oura Ring' },
      { name: 'Venum' },
      { name: 'Keiser' },
      { name: 'Black Star Sports' }
    ],
  },
  // ── GROSSBRITANNIEN ───────────────────────────────────────────────────────
  {
    id: 'tom-aspinall',
    name: 'Tom Aspinall',
    city: 'Liverpool',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Kickboxer', 'BJJ'],
    tags: ['UFC', 'Interim Champion', 'Heavyweight', 'Team Kaobon'],
    weightClass: 'Heavyweight',
    record: '15-3-0',
    rating: 4.9,
    reviews: 0,
    img: ['#001040', '#002080'],
    accentHue: 220,
    stats: { age: 33, height: '193 cm', reach: '196 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'Team Kaobon', born: 'Wigan, England' },
    sponsors: [
      { name: 'Gymshark' },
      { name: 'MyProtein' },
      { name: 'Vitality' },
      { name: 'Venum' }
    ],
  },
  // ── POLEN ─────────────────────────────────────────────────────────────────
  {
    id: 'jan-blachowicz',
    name: 'Jan Błachowicz',
    city: 'Warschau',
    country: 'Poland',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Former Champion', 'LHW', 'Polish Power'],
    weightClass: 'Light Heavyweight',
    record: '29-10-1',
    rating: 4.7,
    reviews: 0,
    img: ['#1A0008', '#3D0015'],
    accentHue: 350,
    stats: { age: 43, height: '185 cm', reach: '193 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'KSW Akademia', born: 'Cieszyn, Polen' },
    sponsors: [
      { name: 'Subaru Poland' },
      { name: 'SuperBet' },
      { name: 'Olimp Sport Nutrition' }
    ],
  },
  // ── FRANKREICH ────────────────────────────────────────────────────────────
  {
    id: 'benoit-saint-denis',
    name: 'Benoît Saint-Denis',
    city: 'Paris',
    country: 'France',
    status: 'verified',
    styles: ['Wrestler', 'Striker'],
    tags: ['UFC', 'Top-10', 'Lightweight', 'God of War'],
    weightClass: 'Lightweight',
    record: '14-3-0',
    rating: 4.6,
    reviews: 0,
    img: ['#00001A', '#00003D'],
    accentHue: 240,
    stats: { age: 30, height: '178 cm', reach: '185 cm', stance: 'Orthodox', nationality: 'Französisch', gym: 'MMA Factory Paris', born: 'Frankreich' },
    sponsors: [
      { name: 'Venum' },
      { name: 'Unkut' },
      { name: 'Reebok France' }
    ],
  },
  {
    id: 'salahdine-parnasse',
    name: 'Salahdine Parnasse',
    city: 'Paris',
    country: 'France',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['KSW', 'Multi-Champion', 'Featherweight', 'Mbappé des MMA'],
    weightClass: 'Featherweight',
    record: '21-2-0',
    rating: 4.8,
    reviews: 0,
    img: ['#0A001A', '#1A0040'],
    accentHue: 270,
    stats: { age: 30, height: '170 cm', reach: '177 cm', stance: 'Orthodox', nationality: 'Französisch', gym: 'Team Noël Le Gall', born: 'Paris, Frankreich' },
    sponsors: [
      { name: 'Free Mobile' },
      { name: 'Venum' },
      { name: 'KSW' }
    ],
  },
  {
    id: 'mateusz-gamrot',
    name: 'Mateusz Gamrot',
    city: 'Poznań',
    country: 'Poland',
    status: 'verified',
    styles: ['Wrestler', 'MMA'],
    tags: ['UFC', 'Top-5', 'Lightweight', 'Gamer'],
    weightClass: 'Lightweight',
    record: '25-3-0',
    rating: 4.7,
    reviews: 0,
    img: ['#200004', '#400008'],
    accentHue: 10,
    stats: { age: 34, height: '175 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'Grappling Poznań', born: 'Gdańsk, Polen' },
    sponsors: [
      { name: 'Red Bull' },
      { name: 'New Balance Poland' },
      { name: 'Olimp Nutrition' }
    ],
  },
  {
    id: 'manon-fiorot',
    name: 'Manon Fiorot',
    city: 'Nizza',
    country: 'France',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Interim Champion', 'Flyweight', 'The Beast'],
    weightClass: 'Flyweight',
    record: '13-1-0',
    rating: 4.8,
    reviews: 0,
    img: ['#000A1A', '#001040'],
    accentHue: 200,
    stats: { age: 34, height: '165 cm', reach: '168 cm', stance: 'Orthodox', nationality: 'Französisch', gym: 'MMA Factory Nice', born: 'Nizza, Frankreich' },
    sponsors: [
      { name: 'PUMA' },
      { name: 'Venum' },
      { name: 'Nice MMA Shop' }
    ],
  },
  // ── ITALIEN ───────────────────────────────────────────────────────────────
  {
    id: 'marvin-vettori',
    name: 'Marvin Vettori',
    city: 'Rom',
    country: 'Italy',
    status: 'verified',
    styles: ['Wrestler', 'Striker'],
    tags: ['UFC', 'Middleweight', 'Italian Dream', 'Kings MMA'],
    weightClass: 'Middleweight',
    record: '19-7-1',
    rating: 4.5,
    reviews: 0,
    img: ['#001A08', '#003D15'],
    accentHue: 120,
    stats: { age: 32, height: '185 cm', reach: '192 cm', stance: 'Orthodox', nationality: 'Italienisch', gym: 'Kings MMA', born: 'Mezzocorona, Italien' },
    sponsors: [
      { name: 'Dolce & Gabbana' },
      { name: 'Venum' },
      { name: 'Everlast' },
      { name: 'Leone 1947' }
    ],
  },
  // ── GROSSBRITANNIEN ───────────────────────────────────────────────────────
  {
    id: 'leon-edwards',
    name: 'Leon Edwards',
    city: 'Birmingham',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Former Champion', 'Welterweight', 'Rocky'],
    weightClass: 'Welterweight',
    record: '22-6-0',
    rating: 4.8,
    reviews: 0,
    img: ['#001018', '#002030'],
    accentHue: 195,
    stats: { age: 34, height: '183 cm', reach: '188 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'Team Renegade', born: 'Birmingham, England' },
    sponsors: [
      { name: 'Moncler' },
      { name: 'Monster Energy' },
      { name: 'Venum' },
      { name: 'Wow Hydrate' }
    ],
  },
  // ── NIEDERLANDE ───────────────────────────────────────────────────────────
  {
    id: 'gegard-mousasi',
    name: 'Gegard Mousasi',
    city: 'Leiden',
    country: 'Netherlands',
    status: 'verified',
    styles: ['Striker', 'BJJ'],
    tags: ['Bellator', 'UFC', 'PFL', 'Legend', 'Middleweight'],
    weightClass: 'Middleweight',
    record: '49-9-2',
    rating: 4.9,
    reviews: 0,
    img: ['#1A0A00', '#3D1800'],
    accentHue: 30,
    stats: { age: 40, height: '193 cm', reach: '196 cm', stance: 'Orthodox', nationality: 'Niederländisch-Armenisch', gym: "Mike's Gym", born: 'Isfahan, Iran' },
    sponsors: [
      { name: '32Red' },
      { name: 'Affliction' },
      { name: 'Venum' }
    ],
  },
  // ── ITALIEN ───────────────────────────────────────────────────────────────
  {
    id: 'alessio-di-chirico',
    name: 'Alessio Di Chirico',
    city: 'Rom',
    country: 'Italy',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Veteran', 'Middleweight', 'Italy'],
    weightClass: 'Middleweight',
    record: '13-7-0',
    rating: 4.2,
    reviews: 0,
    img: ['#001208', '#002810'],
    accentHue: 145,
    stats: { age: 34, height: '185 cm', reach: '190 cm', stance: 'Southpaw', nationality: 'Italienisch', gym: 'Minerva MMA Roma', born: 'Rom, Italien' },
    sponsors: [
      { name: 'Leone 1947' },
      { name: 'EthicSport' }
    ],
  },
  // ── GROSSBRITANNIEN ───────────────────────────────────────────────────────
  {
    id: 'paddy-pimblett',
    name: 'Paddy Pimblett',
    city: 'Liverpool',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['BJJ', 'Striker'],
    tags: ['UFC', 'Lightweight', 'The Baddy', 'Liverpool'],
    weightClass: 'Lightweight',
    record: '22-3-0',
    rating: 4.6,
    reviews: 0,
    img: ['#0A0020', '#1A0040'],
    accentHue: 260,
    stats: { age: 31, height: '178 cm', reach: '178 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'Next Generation Liverpool', born: 'Liverpool, England' },
    sponsors: [
      { name: 'Barstool Sports' },
      { name: 'Applied Nutrition' }
    ],
  },
  // ── NIEDERLANDE ───────────────────────────────────────────────────────────
  {
    id: 'reinier-de-ridder',
    name: 'Reinier de Ridder',
    city: 'Breda',
    country: 'Netherlands',
    status: 'verified',
    styles: ['Grappler', 'BJJ'],
    tags: ['ONE FC', 'UFC', 'Middleweight', 'Dutch Knight'],
    weightClass: 'Middleweight',
    record: '17-2-0',
    rating: 4.7,
    reviews: 0,
    img: ['#1A0800', '#3D1500'],
    accentHue: 45,
    stats: { age: 36, height: '193 cm', reach: '196 cm', stance: 'Orthodox', nationality: 'Niederländisch', gym: 'Allstars Training Center', born: 'Breda, Niederlande' },
    sponsors: [
      { name: 'Venum' },
      { name: 'MyProtein' },
      { name: 'Dutch Combat Brands' }
    ],
  },
  // ── KROATIEN ──────────────────────────────────────────────────────────────
  {
    id: 'roberto-soldic',
    name: 'Roberto Soldić',
    city: 'Düsseldorf',
    country: 'Croatia',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['ONE', 'KSW', 'Welterweight', 'Robocop', 'KO-Artist'],
    weightClass: 'Welterweight',
    record: '20-4-0',
    rating: 4.8,
    reviews: 0,
    img: ['#1A0010', '#3D0020'],
    accentHue: 330,
    stats: { age: 31, height: '183 cm', reach: '185 cm', stance: 'Southpaw', nationality: 'Kroatisch', gym: 'UFD Gym Düsseldorf', born: 'Split, Kroatien' },
    sponsors: [
      { name: 'Olimp' },
      { name: 'SuperBet' },
      { name: 'Paffensport' }
    ],
  },
  // ── SCHWEDEN ──────────────────────────────────────────────────────────────
  {
    id: 'khamzat-chimaev',
    name: 'Khamzat Chimaev',
    city: 'Stockholm',
    country: 'Sweden',
    status: 'verified',
    styles: ['Wrestler', 'Striker'],
    tags: ['UFC', 'Middleweight', 'Borz', 'Top-5', 'Undefeated'],
    weightClass: 'Middleweight',
    record: '14-0-0',
    rating: 4.9,
    reviews: 0,
    img: ['#001A10', '#003D20'],
    accentHue: 160,
    stats: { age: 32, height: '183 cm', reach: '185 cm', stance: 'Orthodox', nationality: 'Schwedisch-Tschetschenisch', gym: 'Allstars Stockholm', born: 'Tschetschenien, Russland' },
    sponsors: [
      { name: 'Smilodox' },
      { name: 'Venum' }
    ],
  },
  // ── FRANKREICH (Batch 3) ──────────────────────────────────────────────────
  {
    id: 'ciryl-gane',
    name: 'Ciryl Gane',
    city: 'Paris',
    country: 'France',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Contender', 'Heavyweight', 'MMA Factory'],
    weightClass: 'Heavyweight',
    record: '13-2-0',
    rating: 4.8,
    reviews: 0,
    img: ['#001020', '#002050'],
    accentHue: 230,
    stats: { age: 35, height: '196 cm', reach: '211 cm', stance: 'Orthodox', nationality: 'Französisch', gym: 'MMA Factory Paris', born: 'Frankreich' },
    sponsors: [
      { name: 'Venum' },
      { name: 'Gymshark' },
      { name: 'Major' },
      { name: 'Crypto.com' }
    ],
  },
  // ── GROSSBRITANNIEN (Batch 3) ─────────────────────────────────────────────
  {
    id: 'michael-bisping',
    name: 'Michael Bisping',
    city: 'Manchester',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Hall of Fame', 'Former Champion', 'The Count'],
    weightClass: 'Middleweight',
    record: '30-9-0',
    rating: 4.8,
    reviews: 0,
    img: ['#0A0A20', '#15153D'],
    accentHue: 215,
    stats: { age: 47, height: '185 cm', reach: '190 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'Tristar Gym (ret.)', born: 'Manchester, England' },
    sponsors: [
      { name: 'Manscaped' },
      { name: 'DraftKings' },
      { name: 'Sledgehammer Whiskey' },
      { name: 'MyProtein' }
    ],
  },
  // ── POLEN (Batch 3) ───────────────────────────────────────────────────────
  {
    id: 'joanna-jedrzejczyk',
    name: 'Joanna Jędrzejczyk',
    city: 'Warschau',
    country: 'Poland',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Former Champion', 'Strawweight', 'Muay Thai'],
    weightClass: 'Strawweight',
    record: '16-5-0',
    rating: 4.9,
    reviews: 0,
    img: ['#200006', '#430010'],
    accentHue: 345,
    stats: { age: 38, height: '165 cm', reach: '168 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'Tiger Muay Thai', born: 'Białystok, Polen' },
    sponsors: [
      { name: 'PUMA Poland' },
      { name: 'Samsung Poland' },
      { name: 'Dietly' },
      { name: 'MyProtein' }
    ],
  },
  // ── IRLAND ────────────────────────────────────────────────────────────────
  {
    id: 'paul-hughes',
    name: 'Paul Hughes',
    city: 'Belfast',
    country: 'Ireland',
    status: 'verified',
    styles: ['Striker', 'Wrestler'],
    tags: ['PFL', 'Bellator', 'Lightweight', 'Belfast'],
    weightClass: 'Lightweight',
    record: '14-1-0',
    rating: 4.7,
    reviews: 0,
    img: ['#002010', '#004820'],
    accentHue: 140,
    stats: { age: 28, height: '175 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Irisch', gym: 'SBG Ireland', born: 'Belfast, Irland' },
    sponsors: [
      { name: 'Monster Energy' },
      { name: 'Gym King' },
      { name: 'Empire Fighting Chance' }
    ],
  },
  // ── SCHWEDEN (Batch 3) ────────────────────────────────────────────────────
  {
    id: 'alexander-gustafsson',
    name: 'Alexander Gustafsson',
    city: 'Stockholm',
    country: 'Sweden',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Legend', 'LHW', 'The Mauler'],
    weightClass: 'Light Heavyweight',
    record: '18-8-0',
    rating: 4.8,
    reviews: 0,
    img: ['#001A1A', '#003D3D'],
    accentHue: 185,
    stats: { age: 39, height: '193 cm', reach: '196 cm', stance: 'Southpaw', nationality: 'Schwedisch', gym: 'Allstars Training Center', born: 'Arboga, Schweden' },
    sponsors: [
      { name: 'Unibet' },
      { name: 'MyProtein' },
      { name: 'Bad Boy' }
    ],
  },
  // ── PORTUGAL ──────────────────────────────────────────────────────────────
  {
    id: 'manel-kape',
    name: 'Manel Kape',
    city: 'Lissabon',
    country: 'Portugal',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Flyweight', 'Starboy', 'Rizin'],
    weightClass: 'Flyweight',
    record: '19-7-0',
    rating: 4.5,
    reviews: 0,
    img: ['#1A0A00', '#3A1800'],
    accentHue: 25,
    stats: { age: 32, height: '168 cm', reach: '178 cm', stance: 'Orthodox', nationality: 'Portugiesisch', gym: 'MMA Factory Lissabon', born: 'Angola' },
    sponsors: [
      { name: 'Venum' },
      { name: 'Monster Energy' },
      { name: 'Prio Energy' }
    ],
  },
  // ── POLEN (Batch 3) ───────────────────────────────────────────────────────
  {
    id: 'michal-materla',
    name: 'Michał Materla',
    city: 'Stettin',
    country: 'Poland',
    status: 'verified',
    styles: ['Wrestler', 'MMA'],
    tags: ['KSW', 'Legend', 'Middleweight', 'Berserker'],
    weightClass: 'Middleweight',
    record: '33-11-0',
    rating: 4.6,
    reviews: 0,
    img: ['#1A0005', '#380010'],
    accentHue: 5,
    stats: { age: 41, height: '185 cm', reach: '190 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'KSW Akademia', born: 'Stettin, Polen' },
    sponsors: [
      { name: 'Olimp Sport Nutrition' },
      { name: 'Pitbull West Coast' },
      { name: 'Stoprocent' }
    ],
  },
  // ── GROSSBRITANNIEN (Wales) ───────────────────────────────────────────────
  {
    id: 'mason-jones',
    name: 'Mason Jones',
    city: 'Cardiff',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Striker', 'Wrestler'],
    tags: ['PFL', 'Cage Warriors', 'Lightweight', 'The Dragon'],
    weightClass: 'Lightweight',
    record: '15-2-0',
    rating: 4.4,
    reviews: 0,
    img: ['#001218', '#002530'],
    accentHue: 205,
    stats: { age: 29, height: '175 cm', reach: '180 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'Capital City MMA Cardiff', born: 'Cardiff, Wales' },
    sponsors: [
      { name: 'Dragon Energy' },
      { name: 'Venum' },
      { name: 'Scramble' }
    ],
  },
  // ── NIEDERLANDE (Batch 3) ─────────────────────────────────────────────────
  {
    id: 'alistair-overeem',
    name: 'Alistair Overeem',
    city: 'Amsterdam',
    country: 'Netherlands',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'K-1', 'Legend', 'Heavyweight', 'The Reem'],
    weightClass: 'Heavyweight',
    record: '47-19-0',
    rating: 4.9,
    reviews: 0,
    img: ['#1A0C00', '#3D1C00'],
    accentHue: 28,
    stats: { age: 45, height: '193 cm', reach: '203 cm', stance: 'Southpaw', nationality: 'Niederländisch', gym: "Mike's Gym (ret.)", born: 'Hounslow, England' },
    sponsors: [
      { name: 'Olimp Nutrition' },
      { name: 'Venum' },
      { name: '32Red' }
    ],
  },
  // ── GROSSBRITANNIEN (Wales) ───────────────────────────────────────────────
  {
    id: 'jack-shore',
    name: 'Jack Shore',
    city: 'Cardiff',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Grappler', 'BJJ'],
    tags: ['UFC', 'Featherweight', 'Tank', 'Wales'],
    weightClass: 'Featherweight',
    record: '17-2-0',
    rating: 4.5,
    reviews: 0,
    img: ['#080820', '#12123D'],
    accentHue: 245,
    stats: { age: 29, height: '170 cm', reach: '172 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'Tillery Combat', born: 'Aberdare, Wales' },
    sponsors: [
      { name: 'Under Armour Wales' },
      { name: 'Monster Energy' },
      { name: 'Venum' }
    ],
  },
  // ── DÄNEMARK ──────────────────────────────────────────────────────────────
  {
    id: 'mads-burnell',
    name: 'Mads Burnell',
    city: 'Kopenhagen',
    country: 'Denmark',
    status: 'verified',
    styles: ['BJJ', 'Striker'],
    tags: ['PFL', 'Bellator', 'Featherweight', 'Arte Suave'],
    weightClass: 'Featherweight',
    record: '19-6-0',
    rating: 4.5,
    reviews: 0,
    img: ['#1A0008', '#380015'],
    accentHue: 355,
    stats: { age: 32, height: '175 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Dänisch', gym: 'Next Round Copenhagen', born: 'Kopenhagen, Dänemark' },
    sponsors: [
      { name: 'Venum' },
      { name: 'MyProtein Denmark' },
      { name: 'Reebok Nordic' }
    ],
  },
  // ── ISLAND ────────────────────────────────────────────────────────────────
  {
    id: 'gunnar-nelson',
    name: 'Gunnar Nelson',
    city: 'Reykjavik',
    country: 'Iceland',
    status: 'verified',
    styles: ['Grappler', 'BJJ'],
    tags: ['UFC', 'Welterweight', 'Gunni', 'Iceland'],
    weightClass: 'Welterweight',
    record: '19-5-1',
    rating: 4.7,
    reviews: 0,
    img: ['#001820', '#003040'],
    accentHue: 195,
    stats: { age: 37, height: '178 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Isländisch', gym: 'SBG Ireland', born: 'Reykjavik, Island' },
    sponsors: [
      { name: 'Icelandic Glacial' },
      { name: 'Venum' },
      { name: 'Reebok Iceland' }
    ],
  },
  // ── GROSSBRITANNIEN (Batch 3) ─────────────────────────────────────────────
  {
    id: 'arnold-allen',
    name: 'Arnold Allen',
    city: 'Ipswich',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Top-5', 'Featherweight', 'Almighty'],
    weightClass: 'Featherweight',
    record: '20-3-0',
    rating: 4.7,
    reviews: 0,
    img: ['#0A1520', '#152D40'],
    accentHue: 210,
    stats: { age: 31, height: '170 cm', reach: '175 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'SBG Ipswich', born: 'Ipswich, England' },
    sponsors: [
      { name: 'Gymshark' },
      { name: 'MyProtein' },
      { name: 'Venum' }
    ],
  },
  // ── IRLAND (Batch 4) ──────────────────────────────────────────────────────
  {
    id: 'caolan-loughran',
    name: 'Caolán Loughran',
    city: 'Belfast',
    country: 'Ireland',
    status: 'verified',
    styles: ['Striker', 'Wrestler'],
    tags: ['UFC', 'Bantamweight', 'Belfast', 'Team Kaobon'],
    weightClass: 'Bantamweight',
    record: '11-1-0',
    rating: 4.4,
    reviews: 0,
    img: ['#001A0A', '#003A18'],
    accentHue: 145,
    stats: { age: 29, height: '168 cm', reach: '173 cm', stance: 'Orthodox', nationality: 'Irisch', gym: 'SBG Ireland', born: 'Belfast, Irland' },
    sponsors: [
      { name: 'Venum' },
      { name: 'MyProtein' },
      { name: 'Irish Combat Gear' }
    ],
  },
  // ── POLEN (Batch 4) ───────────────────────────────────────────────────────
  {
    id: 'karolina-kowalkiewicz',
    name: 'Karolina Kowalkiewicz',
    city: 'Łódź',
    country: 'Poland',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Strawweight', 'Veteran', 'Muay Thai'],
    weightClass: 'Strawweight',
    record: '16-8-0',
    rating: 4.3,
    reviews: 0,
    img: ['#200008', '#400015'],
    accentHue: 350,
    stats: { age: 40, height: '165 cm', reach: '163 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'KSW / MMA Factory', born: 'Łódź, Polen' },
    sponsors: [
      { name: 'Olimp Nutrition' },
      { name: 'Samsung Poland' },
      { name: 'Dietly' }
    ],
  },
  {
    id: 'marcin-tybura',
    name: 'Marcin Tybura',
    city: 'Warschau',
    country: 'Poland',
    status: 'verified',
    styles: ['BJJ', 'MMA'],
    tags: ['UFC', 'Top-10', 'Heavyweight', 'WCA Fight Team'],
    weightClass: 'Heavyweight',
    record: '26-9-0',
    rating: 4.4,
    reviews: 0,
    img: ['#1A0A0A', '#3A1515'],
    accentHue: 5,
    stats: { age: 39, height: '188 cm', reach: '193 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'WCA Fight Team Warschau', born: 'Warschau, Polen' },
    sponsors: [
      { name: 'Olimp Nutrition' },
      { name: 'SuperBet Poland' }
    ],
  },

  // ── BATCH #5 ──────────────────────────────────────────────────────────────
  {
    id: 'ian-machado-garry',
    name: 'Ian Machado Garry',
    city: 'Dublin',
    country: 'Ireland',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Welterweight', 'Ireland', 'Reach: 188cm'],
    weightClass: 'Welterweight',
    record: '17-1-0',
    rating: 4.8,
    reviews: 0,
    img: ['#001A0A', '#003D1A'],
    accentHue: 145,
    stats: { age: 28, height: '191 cm', reach: '188 cm', stance: 'Orthodox', nationality: 'Irisch', gym: 'Kill Cliff FC', born: 'Dublin, Irland' },
    fightHistory: [
      { result: 'W', opponent: 'Joaquin Buckley', method: 'Unanimous Decision', event: 'UFC 304', round: 3, time: '5:00', date: '2024-07-27', org: 'UFC' },
      { result: 'W', opponent: 'Geoff Neal', method: 'KO', event: 'UFC 291', round: 2, time: '2:45', date: '2023-07-29', org: 'UFC' },
    ],
    sponsors: [
      { name: 'Ichor' },
      { name: 'Venum' },
      { name: 'Monster Energy' },
      { name: 'MyProtein' },
    ],
  },
  {
    id: 'joel-alvarez',
    name: 'Joel Álvarez',
    city: 'Gijón',
    country: 'Spain',
    status: 'verified',
    styles: ['Grappler', 'BJJ'],
    tags: ['UFC', 'Lightweight', 'Spain', '17 Subs', 'Reach: 196cm'],
    weightClass: 'Lightweight',
    record: '22-3-0',
    rating: 4.7,
    reviews: 0,
    img: ['#1A0800', '#3D1600'],
    accentHue: 22,
    stats: { age: 33, height: '191 cm', reach: '196 cm', stance: 'Orthodox', nationality: 'Spanisch', gym: 'Bandog Fight Club', born: 'Gijón, Spanien' },
    fightHistory: [
      { result: 'W', opponent: 'Yusuf Nurmagomedov', method: 'Unanimous Decision', event: 'UFC Fight Night', round: 3, time: '5:00', date: '2023-12-16', org: 'UFC' },
      { result: 'L', opponent: 'Beneil Dariush', method: 'Submission', event: 'UFC Fight Night', round: 2, time: '3:10', date: '2022-10-22', org: 'UFC' },
    ],
    sponsors: [
      { name: 'Everlast Spain' },
      { name: 'Prozis' },
      { name: 'Venum' },
    ],
  },
  {
    id: 'victoria-dudakova',
    name: 'Victoria Dudakova',
    city: 'Moskau',
    country: 'Russia',
    status: 'verified',
    styles: ['Wrestler', 'Grappler'],
    tags: ['PFL', 'Strawweight', 'Russia', 'Team Fedor'],
    weightClass: 'Strawweight',
    record: '10-2-0',
    rating: 4.4,
    reviews: 0,
    img: ['#1A000A', '#3A0015'],
    accentHue: 345,
    stats: { age: 27, height: '165 cm', reach: '170 cm', stance: 'Orthodox', nationality: 'Russisch', gym: 'Team Fedor', born: 'Russland' },
    fightHistory: [
      { result: 'W', opponent: 'Vanessa Melo', method: 'Unanimous Decision', event: 'PFL 2024', round: 3, time: '5:00', date: '2024-06-14', org: 'PFL' },
      { result: 'W', opponent: 'Hannah Guy', method: 'TKO', event: 'PFL 2023', round: 2, time: '3:45', date: '2023-05-05', org: 'PFL' },
    ],
    sponsors: [
      { name: 'Gorilla Energy' },
      { name: 'Venum' },
      { name: 'BetCity' },
    ],
  },
  {
    id: 'costello-van-steenis',
    name: 'Costello van Steenis',
    city: 'Leiden',
    country: 'Netherlands',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['PFL', 'Middleweight', 'Champion', 'Netherlands'],
    weightClass: 'Middleweight',
    record: '18-3-0',
    rating: 4.6,
    reviews: 0,
    img: ['#1A0800', '#3D2000'],
    accentHue: 28,
    stats: { age: 33, height: '185 cm', reach: '190 cm', stance: 'Orthodox', nationality: 'Niederländisch', gym: 'Team Mousasi', born: 'Leiden, Niederlande' },
    fightHistory: [
      { result: 'W', opponent: 'Nick Newell', method: 'TKO', event: 'PFL 2024', round: 2, time: '4:20', date: '2024-04-19', org: 'PFL' },
      { result: 'W', opponent: 'Renan Ferreira', method: 'Decision', event: 'PFL 2023', round: 3, time: '5:00', date: '2023-06-16', org: 'PFL' },
    ],
    sponsors: [
      { name: '32Red' },
      { name: 'Venum' },
      { name: 'Dutch Combat Gear' },
    ],
  },
  {
    id: 'modestas-bukauskas',
    name: 'Modestas Bukauskas',
    city: 'Vilnius',
    country: 'Lithuania',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    tags: ['UFC', 'Light Heavyweight', 'Lithuania', 'Cage Warriors'],
    weightClass: 'Light Heavyweight',
    record: '16-6-0',
    rating: 4.4,
    reviews: 0,
    img: ['#001508', '#002E12'],
    accentHue: 140,
    stats: { age: 32, height: '191 cm', reach: '198 cm', stance: 'Orthodox', nationality: 'Litauisch', gym: 'Gintas Combat', born: 'Vilnius, Litauen' },
    fightHistory: [
      { result: 'W', opponent: 'Tafon Nchukwi', method: 'TKO', event: 'UFC Fight Night', round: 1, time: '3:10', date: '2024-03-02', org: 'UFC' },
      { result: 'L', opponent: 'Alonzo Menifield', method: 'KO', event: 'UFC Fight Night', round: 1, time: '2:55', date: '2021-12-18', org: 'UFC' },
    ],
    sponsors: [
      { name: 'Venum' },
      { name: 'MyProtein' },
      { name: 'Lithium Sports' },
    ],
  },
  {
    id: 'david-zawada',
    name: 'David Zawada',
    city: 'Düsseldorf',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'Grappler'],
    tags: ['PFL', 'KSW', 'Welterweight', 'Germany'],
    weightClass: 'Welterweight',
    record: '20-10-0',
    rating: 4.3,
    reviews: 0,
    img: ['#0A0A1A', '#181830'],
    accentHue: 230,
    stats: { age: 35, height: '183 cm', reach: '185 cm', stance: 'Orthodox', nationality: 'Deutsch', gym: 'UFD Gym Düsseldorf', born: 'Düsseldorf, Deutschland' },
    fightHistory: [
      { result: 'W', opponent: 'Dilmurat Sultanbekov', method: 'KO', event: 'PFL 2024', round: 1, time: '1:55', date: '2024-04-26', org: 'PFL' },
      { result: 'L', opponent: 'Ryuichiro Sumimura', method: 'Decision', event: 'PFL 2023', round: 3, time: '5:00', date: '2023-06-23', org: 'PFL' },
    ],
    sponsors: [
      { name: 'Olimp Nutrition' },
      { name: 'Paffensport' },
      { name: 'Toyo Tires' },
    ],
  },
  {
    id: 'marc-diakiese',
    name: 'Marc Diakiese',
    city: 'London',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Striker', 'Wrestler'],
    tags: ['OKTAGON', 'UFC', 'Lightweight', 'United Kingdom'],
    weightClass: 'Lightweight',
    record: '18-8-0',
    rating: 4.4,
    reviews: 0,
    img: ['#0A001A', '#180030'],
    accentHue: 270,
    stats: { age: 33, height: '178 cm', reach: '188 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'American Top Team', born: 'London, Großbritannien' },
    fightHistory: [
      { result: 'W', opponent: 'Jai Herbert', method: 'Unanimous Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2024-09-28', org: 'OKTAGON' },
      { result: 'L', opponent: 'Guram Kutateladze', method: 'TKO', event: 'UFC Fight Night', round: 3, time: '4:30', date: '2020-09-26', org: 'UFC' },
    ],
    sponsors: [
      { name: 'Venum' },
      { name: 'Gym King' },
      { name: 'Monster Energy' },
    ],
  },
  {
    id: 'losene-keita',
    name: 'Losene Keita',
    city: 'Brüssel',
    country: 'Belgium',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['OKTAGON', 'Champion', 'Belgium', 'Featherweight'],
    weightClass: 'Featherweight',
    record: '15-2-0',
    rating: 4.6,
    reviews: 0,
    img: ['#1A1400', '#3A2A00'],
    accentHue: 45,
    stats: { age: 28, height: '170 cm', reach: '175 cm', stance: 'Orthodox', nationality: 'Belgisch', gym: 'Team Keita', born: 'Brüssel, Belgien' },
    fightHistory: [
      { result: 'W', opponent: 'Ronald Paradeiser', method: 'Unanimous Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2024-12-07', org: 'OKTAGON' },
      { result: 'W', opponent: 'Ivan Buchinger', method: 'TKO', event: 'OKTAGON', round: 2, time: '1:55', date: '2025-07-05', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Onyx' },
      { name: 'Venum' },
      { name: 'Bet-at-home' },
    ],
  },
  {
    id: 'brendan-loughnane',
    name: 'Brendan Loughnane',
    city: 'Manchester',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['PFL', 'Champion', 'Featherweight', 'United Kingdom'],
    weightClass: 'Featherweight',
    record: '30-6-0',
    rating: 4.7,
    reviews: 0,
    img: ['#001833', '#00285A'],
    accentHue: 205,
    stats: { age: 36, height: '178 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'Tiger Muay Thai', born: 'Manchester, England' },
    fightHistory: [
      { result: 'W', opponent: 'Gabriel Braga', method: 'Submission', event: 'PFL 2024', round: 2, time: '3:55', date: '2024-04-12', org: 'PFL' },
      { result: 'W', opponent: 'Antoine Massé', method: 'KO', event: 'PFL 2023', round: 1, time: '0:58', date: '2023-05-12', org: 'PFL' },
    ],
    sponsors: [
      { name: 'Gymshark' },
      { name: 'Monster Energy' },
      { name: 'Venum' },
    ],
  },
  {
    id: 'bernardo-sopai',
    name: 'Bernardo Sopai',
    city: 'Tirana',
    country: 'Albania',
    status: 'verified',
    styles: ['Striker', 'Wrestler'],
    tags: ['UFC', 'Bantamweight', 'Albania', 'Allstars'],
    weightClass: 'Bantamweight',
    record: '13-4-0',
    rating: 4.3,
    reviews: 0,
    img: ['#1A0000', '#3D0000'],
    accentHue: 0,
    stats: { age: 25, height: '168 cm', reach: '170 cm', stance: 'Orthodox', nationality: 'Albanisch', gym: 'Allstars Training Center', born: 'Tirana, Albanien' },
    fightHistory: [
      { result: 'W', opponent: 'Ricky Turcios', method: 'Unanimous Decision', event: 'UFC Fight Night', round: 3, time: '5:00', date: '2025-01-18', org: 'UFC' },
      { result: 'L', opponent: 'Vinicius Oliveira', method: 'KO', event: 'UFC Fight Night', round: 3, time: '1:22', date: '2024-03-09', org: 'UFC' },
    ],
    sponsors: [
      { name: 'Smilodox' },
      { name: 'Venum' },
      { name: 'Reebok Albania' },
    ],
  },
  {
    id: 'veronica-hardy',
    name: 'Veronica Hardy',
    city: 'Bratislava',
    country: 'Slovakia',
    status: 'verified',
    styles: ['Striker', 'BJJ'],
    tags: ['UFC', "Women's Flyweight", 'Slovakia', 'Dan Hardy'],
    weightClass: "Women's Flyweight",
    record: '10-5-1',
    rating: 4.2,
    reviews: 0,
    img: ['#001020', '#001830'],
    accentHue: 215,
    stats: { age: 30, height: '163 cm', reach: '163 cm', stance: 'Orthodox', nationality: 'Slowakisch', gym: 'Team Hardy', born: 'Bratislava, Slowakei' },
    fightHistory: [
      { result: 'L', opponent: 'Erin Blanchfield', method: 'Submission', event: 'UFC Fight Night', round: 2, time: '2:40', date: '2024-03-16', org: 'UFC' },
      { result: 'W', opponent: 'Tabatha Ricci', method: 'Unanimous Decision', event: 'UFC Fight Night', round: 3, time: '5:00', date: '2023-09-09', org: 'UFC' },
    ],
    sponsors: [
      { name: 'Venum' },
      { name: 'MyProtein' },
      { name: 'Everlast' },
    ],
  },
  {
    id: 'nicolas-dalby',
    name: 'Nicolas Dalby',
    city: 'Kopenhagen',
    country: 'Denmark',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Welterweight', 'Denmark', 'Veteran'],
    weightClass: 'Welterweight',
    record: '23-6-1',
    rating: 4.4,
    reviews: 0,
    img: ['#1A0005', '#380010'],
    accentHue: 355,
    stats: { age: 41, height: '180 cm', reach: '188 cm', stance: 'Orthodox', nationality: 'Dänisch', gym: 'Rumble Sports', born: 'Kopenhagen, Dänemark' },
    fightHistory: [
      { result: 'W', opponent: 'Tim Means', method: 'Unanimous Decision', event: 'UFC Fight Night', round: 3, time: '5:00', date: '2024-06-08', org: 'UFC' },
      { result: 'L', opponent: 'Michael Morales', method: 'Unanimous Decision', event: 'UFC Fight Night', round: 3, time: '5:00', date: '2023-10-14', org: 'UFC' },
    ],
    sponsors: [
      { name: 'Unibet Denmark' },
      { name: 'Venum' },
      { name: 'Reebok Nordic' },
    ],
  },
  {
    id: 'aleksandar-ilic',
    name: 'Aleksandar Ilić',
    city: 'Belgrad',
    country: 'Serbia',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['KSW', 'RCC', 'Middleweight', 'Serbia'],
    weightClass: 'Middleweight',
    record: '16-6-0',
    rating: 4.3,
    reviews: 0,
    img: ['#0A0014', '#14002A'],
    accentHue: 265,
    stats: { age: 37, height: '191 cm', reach: '196 cm', stance: 'Southpaw', nationality: 'Serbisch', gym: 'UFD Gym Düsseldorf', born: 'Belgrad, Serbien' },
    fightHistory: [
      { result: 'W', opponent: 'Miran Fabjan', method: 'KO', event: 'FNC 27', round: 1, time: '0:45', date: '2026-02-07', org: 'FNC' },
      { result: 'W', opponent: 'Nikola Matić', method: 'Unanimous Decision', event: 'RCC', round: 3, time: '5:00', date: '2025-09-14', org: 'RCC' },
    ],
    sponsors: [
      { name: 'Olimp' },
      { name: 'Bet-at-home' },
      { name: 'Paffensport' },
    ],
  },
  {
    id: 'pannie-kianzad',
    name: 'Pannie Kianzad',
    city: 'Stockholm',
    country: 'Sweden',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', "Women's Bantamweight", 'Sweden', 'Arte Suave'],
    weightClass: "Women's Bantamweight",
    record: '17-9-0',
    rating: 4.3,
    reviews: 0,
    img: ['#00101A', '#001A2A'],
    accentHue: 200,
    stats: { age: 34, height: '170 cm', reach: '168 cm', stance: 'Orthodox', nationality: 'Schwedisch', gym: 'Arte Suave', born: 'Stockholm, Schweden' },
    fightHistory: [
      { result: 'L', opponent: 'Yana Santos', method: 'Unanimous Decision', event: 'UFC Fight Night', round: 3, time: '5:00', date: '2024-09-14', org: 'UFC' },
      { result: 'W', opponent: 'Aspen Ladd', method: 'Unanimous Decision', event: 'UFC Fight Night', round: 3, time: '5:00', date: '2023-09-16', org: 'UFC' },
    ],
    sponsors: [
      { name: 'Venum' },
      { name: 'Reebok Sweden' },
      { name: 'MyProtein' },
    ],
  },
  {
    id: 'joel-parrado',
    name: 'Joel Parrado',
    city: 'Madrid',
    country: 'Spain',
    status: 'self',
    styles: ['Striker', 'MMA'],
    tags: ['OKTAGON', 'Middleweight', 'Spain', 'Prospect'],
    weightClass: 'Middleweight',
    record: '9-1-0',
    rating: 4.2,
    reviews: 0,
    img: ['#1A0600', '#380E00'],
    accentHue: 18,
    stats: { age: 26, height: '183 cm', reach: '185 cm', stance: 'Orthodox', nationality: 'Spanisch', gym: 'Lokal Spanien', born: 'Spanien' },
    fightHistory: [
      { result: 'W', opponent: 'Andrés Castro', method: 'Unanimous Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2025-09-27', org: 'OKTAGON' },
      { result: 'W', opponent: 'Martin Zawadzki', method: 'TKO', event: 'OKTAGON', round: 2, time: '3:15', date: '2024-11-09', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Everlast' },
      { name: 'Local Spanish Brands' },
    ],
  },

  // ── BATCH #6 ──────────────────────────────────────────────────────────────
  {
    id: 'mateusz-rebecki',
    name: 'Mateusz Rębecki',
    city: 'Stettin',
    country: 'Poland',
    status: 'verified',
    styles: ['Wrestler', 'Grappler'],
    tags: ['UFC', 'Lightweight', 'Poland', 'Rebeasti'],
    weightClass: 'Lightweight',
    record: '20-4-0',
    rating: 4.6,
    reviews: 0,
    img: ['#1A0000', '#400800'],
    accentHue: 5,
    stats: { age: 33, height: '170 cm', reach: '168 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'Berserkers Team / American Top Team', born: 'Stettin, Polen' },
    fightHistory: [
      { result: 'L', opponent: 'Myktybek Orolbai', method: 'Unanimous Decision', event: 'UFC Fight Night', round: 3, time: '5:00', date: '2025-10', org: 'UFC' },
      { result: 'L', opponent: 'Carlos Diego Ferreira', method: 'TKO', event: 'UFC Fight Night', round: 3, time: '2:45', date: '2024-05', org: 'UFC' },
    ],
    sponsors: [
      { name: 'Olimp Sport Nutrition' },
      { name: 'SuperBet Poland' },
      { name: 'Pitbull West Coast' },
    ],
  },
  {
    id: 'fares-ziam',
    name: 'Fares Ziam',
    city: 'Paris',
    country: 'France',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Lightweight', 'France', 'Smile Killer'],
    weightClass: 'Lightweight',
    record: '18-4-0',
    rating: 4.6,
    reviews: 0,
    img: ['#001040', '#001A60'],
    accentHue: 215,
    stats: { age: 29, height: '185 cm', reach: '190 cm', stance: 'Orthodox', nationality: 'Französisch', gym: 'Sanford MMA', born: 'Paris, Frankreich' },
    fightHistory: [
      { result: 'W', opponent: 'Matt Frevola', method: 'KO', event: 'UFC Fight Night', round: 3, time: '2:12', date: '2025-09', org: 'UFC' },
      { result: 'W', opponent: 'Claudio Puelles', method: 'Decision', event: 'UFC Fight Night', round: 3, time: '5:00', date: '2024-02', org: 'UFC' },
    ],
    sponsors: [
      { name: 'Venum' },
      { name: 'Reebok France' },
      { name: 'Gorilla Energy' },
    ],
  },
  {
    id: 'guram-kutateladze',
    name: 'Guram Kutateladze',
    city: 'Stockholm',
    country: 'Sweden',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    tags: ['UFC', 'Lightweight', 'Georgia', 'Georgian Viking'],
    weightClass: 'Lightweight',
    record: '14-4-0',
    rating: 4.5,
    reviews: 0,
    img: ['#001A08', '#003820'],
    accentHue: 155,
    stats: { age: 34, height: '180 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Georgisch', gym: 'Allstars Training Center', born: 'Georgien' },
    fightHistory: [
      { result: 'W', opponent: 'Jordan Vucenic', method: 'Unanimous Decision', event: 'UFC Fight Night', round: 3, time: '5:00', date: '2025-08', org: 'UFC' },
      { result: 'L', opponent: 'Elves Brener', method: 'TKO', event: 'UFC Fight Night', round: 3, time: '3:21', date: '2023-07', org: 'UFC' },
    ],
    sponsors: [
      { name: 'Smilodox' },
      { name: 'Venum' },
      { name: 'Unibet Sweden' },
    ],
  },
  {
    id: 'charalampos-grigoriou',
    name: 'Charalampos Grigoriou',
    city: 'Nikosia',
    country: 'Cyprus',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Bantamweight', 'Cyprus', 'First Cypriot'],
    weightClass: 'Bantamweight',
    record: '9-5-0',
    rating: 4.3,
    reviews: 0,
    img: ['#0A0015', '#1A0030'],
    accentHue: 275,
    stats: { age: 34, height: '170 cm', reach: '170 cm', stance: 'Orthodox', nationality: 'Zypriotisch', gym: 'Serra-Longo Fight Team', born: 'Nikosia, Zypern' },
    fightHistory: [
      { result: 'W', opponent: 'Chad Anheliger', method: 'Decision', event: 'UFC Fight Night', round: 3, time: '5:00', date: '2025-12', org: 'UFC' },
      { result: 'L', opponent: 'Chad Anheliger', method: 'Decision', event: 'UFC Fight Night', round: 3, time: '5:00', date: '2024-03', org: 'UFC' },
    ],
    sponsors: [
      { name: 'Venum' },
      { name: 'MyProtein' },
      { name: 'Cyprus MMA Assets' },
    ],
  },
  {
    id: 'daniel-skvor',
    name: 'Daniel Škvor',
    city: 'Prag',
    country: 'Czechia',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    tags: ['OKTAGON', 'Light Heavyweight', 'Czechia', 'KO-Artist'],
    weightClass: 'Light Heavyweight',
    record: '8-3-0',
    rating: 4.5,
    reviews: 0,
    img: ['#1A0800', '#3D1400'],
    accentHue: 15,
    stats: { age: 37, height: '195 cm', reach: '200 cm', stance: 'Orthodox', nationality: 'Tschechisch', gym: 'Reinders MMA Prag', born: 'Prag, Tschechien' },
    fightHistory: [
      { result: 'W', opponent: 'Will Fleury', method: 'KO', event: 'OKTAGON', round: 2, time: '3:10', date: '2026-03', org: 'OKTAGON' },
      { result: 'W', opponent: 'Narkun', method: 'Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2025-12', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Tipsport' },
      { name: 'OKTAGON Official' },
      { name: 'Gymbeam' },
    ],
  },
  {
    id: 'will-fleury',
    name: 'Will Fleury',
    city: 'Dublin',
    country: 'Ireland',
    status: 'verified',
    styles: ['Wrestler', 'MMA'],
    tags: ['OKTAGON', 'Champion', 'Light Heavyweight', 'SBG'],
    weightClass: 'Light Heavyweight',
    record: '13-3-0',
    rating: 4.7,
    reviews: 0,
    img: ['#001806', '#002E0F'],
    accentHue: 135,
    stats: { age: 37, height: '188 cm', reach: '193 cm', stance: 'Orthodox', nationality: 'Irisch', gym: 'SBG Ireland', born: 'Dublin, Irland' },
    fightHistory: [
      { result: 'W', opponent: 'Pavol Langer', method: 'TKO', event: 'OKTAGON', round: 1, time: '2:45', date: '2026-04', org: 'OKTAGON' },
      { result: 'W', opponent: 'Daniel Škvor', method: 'Submission', event: 'OKTAGON', round: 2, time: '3:55', date: '2025-09', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Monster Energy' },
      { name: 'Venum' },
      { name: 'MyProtein Ireland' },
    ],
  },
  {
    id: 'ivan-buchinger',
    name: 'Ivan Buchinger',
    city: 'Bratislava',
    country: 'Slovakia',
    status: 'verified',
    styles: ['Grappler', 'BJJ'],
    tags: ['OKTAGON', 'Legend', 'Lightweight', 'M-1 Global'],
    weightClass: 'Lightweight',
    record: '44-10-0',
    rating: 4.8,
    reviews: 0,
    img: ['#000820', '#001038'],
    accentHue: 225,
    stats: { age: 40, height: '175 cm', reach: '178 cm', stance: 'Orthodox', nationality: 'Slowakisch', gym: 'MMA Spirit Frankfurt', born: 'Slowakei' },
    fightHistory: [
      { result: 'W', opponent: 'Ronald Paradeiser', method: 'Submission', event: 'OKTAGON', round: 3, time: '4:20', date: '2026-02', org: 'OKTAGON' },
      { result: 'L', opponent: 'Losene Keita', method: 'TKO', event: 'OKTAGON', round: 2, time: '1:55', date: '2025-07', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Tipsport' },
      { name: 'Paffensport' },
      { name: 'FitInn' },
    ],
  },
  {
    id: 'patrik-kincl',
    name: 'Patrik Kincl',
    city: 'Prag',
    country: 'Czechia',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['OKTAGON', 'Interim Champion', 'Middleweight', 'The Inspector'],
    weightClass: 'Middleweight',
    record: '28-11-0',
    rating: 4.7,
    reviews: 0,
    img: ['#180003', '#30000A'],
    accentHue: 350,
    stats: { age: 36, height: '180 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Tschechisch', gym: 'All-Stars Prag', born: 'Prag, Tschechien' },
    fightHistory: [
      { result: 'W', opponent: 'Piotr Wawrzyniak', method: 'Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2026-04', org: 'OKTAGON' },
      { result: 'L', opponent: 'Kerim Engizek', method: 'Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2025-03', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Tipsport' },
      { name: 'Sponsoo' },
      { name: 'Under Armour CZ' },
    ],
  },
  {
    id: 'robert-pukac',
    name: 'Robert Pukač',
    city: 'Bratislava',
    country: 'Slovakia',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['OKTAGON', 'Welterweight', 'Slovakia', 'Diamantový Čávo'],
    weightClass: 'Welterweight',
    record: '17-13-1',
    rating: 4.3,
    reviews: 0,
    img: ['#0A0015', '#180028'],
    accentHue: 260,
    stats: { age: 33, height: '183 cm', reach: '185 cm', stance: 'Orthodox', nationality: 'Slowakisch', gym: 'OFA Bratislava', born: 'Bratislava, Slowakei' },
    fightHistory: [
      { result: 'W', opponent: 'Andrej Kalašnik', method: 'Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2026-03', org: 'OKTAGON' },
      { result: 'W', opponent: 'Christian Jungwirth', method: 'Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2025-11', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Tipsport' },
      { name: 'Local Slovak Brands' },
    ],
  },
  {
    id: 'christian-jungwirth',
    name: 'Christian Jungwirth',
    city: 'Stuttgart',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['OKTAGON', 'Welterweight', 'Germany', 'The Kelt'],
    weightClass: 'Welterweight',
    record: '15-9-0',
    rating: 4.3,
    reviews: 0,
    img: ['#0A0A10', '#181820'],
    accentHue: 225,
    stats: { age: 39, height: '181 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Deutsch', gym: 'Kongs Gym Stuttgart', born: 'Stuttgart, Deutschland' },
    fightHistory: [
      { result: 'L', opponent: 'Ion Surdu', method: 'TKO', event: 'OKTAGON', round: 1, time: '1:30', date: '2026-03', org: 'OKTAGON' },
      { result: 'L', opponent: 'Robert Pukač', method: 'Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2025-11', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Onyx' },
      { name: 'Sponsoo' },
      { name: 'Bama' },
    ],
  },
  {
    id: 'zafar-mohsen',
    name: 'Zafar Mohsen',
    city: 'Frankfurt',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['PFL', 'OKTAGON', 'Featherweight', 'Germany'],
    weightClass: 'Featherweight',
    record: '14-4-0',
    rating: 4.4,
    reviews: 0,
    img: ['#1A0C00', '#3D1C00'],
    accentHue: 25,
    stats: { age: 31, height: '175 cm', reach: '178 cm', stance: 'Orthodox', nationality: 'Deutsch-Afghanisch', gym: 'MMA Spirit Frankfurt', born: 'Deutschland' },
    fightHistory: [
      { result: 'W', opponent: 'Radek Roušal', method: 'Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2026-02', org: 'OKTAGON' },
      { result: 'W', opponent: 'James Hendin', method: 'KO', event: 'PFL', round: 1, time: '0:55', date: '2025-10', org: 'PFL' },
    ],
    sponsors: [
      { name: 'Olimp Nutrition' },
      { name: 'Venum' },
      { name: 'Pitbull West Coast' },
    ],
  },
  {
    id: 'jonas-magard',
    name: 'Jonas Mågård',
    city: 'Kopenhagen',
    country: 'Denmark',
    status: 'verified',
    styles: ['Grappler', 'BJJ'],
    tags: ['OKTAGON', 'Bantamweight', 'Denmark', 'Shark'],
    weightClass: 'Bantamweight',
    record: '17-7-0',
    rating: 4.5,
    reviews: 0,
    img: ['#1A0005', '#38000F'],
    accentHue: 355,
    stats: { age: 33, height: '175 cm', reach: '178 cm', stance: 'Orthodox', nationality: 'Dänisch', gym: 'Manchester Top Team', born: 'Kopenhagen, Dänemark' },
    fightHistory: [
      { result: 'W', opponent: 'Elvis Silva', method: 'Submission', event: 'OKTAGON', round: 2, time: '3:40', date: '2026-04', org: 'OKTAGON' },
      { result: 'L', opponent: 'Igor Severino', method: 'Decision', event: 'OKTAGON', round: 5, time: '5:00', date: '2025-09', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Unibet Denmark' },
      { name: 'Venum' },
      { name: 'Reebok Nordic' },
    ],
  },
  {
    id: 'miran-fabjan',
    name: 'Miran Fabjan',
    city: 'Ljubljana',
    country: 'Slovenia',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    tags: ['FNC', 'Heavyweight', 'Slovenia', 'SloRocky'],
    weightClass: 'Heavyweight',
    record: '7-6-0',
    rating: 4.2,
    reviews: 0,
    img: ['#001808', '#003015'],
    accentHue: 140,
    stats: { age: 41, height: '183 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Slowenisch', gym: 'Zelg Galešić Team', born: 'Ljubljana, Slowenien' },
    fightHistory: [
      { result: 'L', opponent: 'Aleksandar Ilić', method: 'KO', event: 'FNC 27', round: 1, time: '0:45', date: '2026-02-07', org: 'FNC' },
      { result: 'W', opponent: 'Tomislav Spahović', method: 'TKO', event: 'FNC', round: 3, time: '4:10', date: '2025-12', org: 'FNC' },
    ],
    sponsors: [
      { name: 'FNC Official' },
      { name: 'Local Slovenian Partners' },
    ],
  },
  {
    id: 'pavol-langer',
    name: 'Pavol Langer',
    city: 'Košice',
    country: 'Slovakia',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['OKTAGON', 'Light Heavyweight', 'Slovakia', 'Cinderella Story'],
    weightClass: 'Light Heavyweight',
    record: '13-11-0',
    rating: 4.2,
    reviews: 0,
    img: ['#001020', '#001A35'],
    accentHue: 210,
    stats: { age: 34, height: '195 cm', reach: '198 cm', stance: 'Orthodox', nationality: 'Slowakisch', gym: 'MMA Psycho Košice', born: 'Košice, Slowakei' },
    fightHistory: [
      { result: 'L', opponent: 'Will Fleury', method: 'TKO', event: 'OKTAGON', round: 1, time: '2:45', date: '2026-04', org: 'OKTAGON' },
      { result: 'W', opponent: 'Marc Doussis', method: 'Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2025-12', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Tipsport' },
      { name: 'FitInn Slovakia' },
    ],
  },

  // ── BATCH #7 ──────────────────────────────────────────────────────────────
  {
    id: 'makhmud-muradov',
    name: 'Makhmud Muradov',
    city: 'Prag',
    country: 'Czechia',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['OKTAGON', 'Interim Champion', 'Middleweight', 'TMT'],
    weightClass: 'Middleweight',
    record: '27-8-0',
    rating: 4.7,
    reviews: 0,
    img: ['#001A18', '#003430'],
    accentHue: 170,
    stats: { age: 36, height: '188 cm', reach: '191 cm', stance: 'Orthodox', nationality: 'Usbekisch', gym: 'Monster Gym Prag / TMT', born: 'Usbekistan' },
    fightHistory: [
      { result: 'W', opponent: 'Scott Askham', method: 'Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2025-09', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Money Team (TMT)' },
      { name: 'Tipsport' },
      { name: 'Nike Czech' },
    ],
  },
  {
    id: 'alexander-poppeck',
    name: 'Alexander Poppeck',
    city: 'München',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['OKTAGON', 'Light Heavyweight', 'Germany', 'Iron'],
    weightClass: 'Light Heavyweight',
    record: '18-5-0',
    rating: 4.6,
    reviews: 0,
    img: ['#080A18', '#101530'],
    accentHue: 230,
    stats: { age: 34, height: '190 cm', reach: '195 cm', stance: 'Orthodox', nationality: 'Deutsch', gym: 'Munich MMA', born: 'München, Deutschland' },
    fightHistory: [
      { result: 'W', opponent: 'Jorick Montagnac', method: 'TKO', event: 'OKTAGON', round: 2, time: '3:15', date: '2025-12', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Venum' },
      { name: 'Gorilla Energy' },
      { name: 'Sponsoo' },
    ],
  },
  {
    id: 'amiran-gogoladze',
    name: 'Amiran Gogoladze',
    city: 'Tiflis',
    country: 'Georgia',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['OKTAGON', 'Welterweight', 'Georgia', 'The Sniper'],
    weightClass: 'Welterweight',
    record: '17-3-0',
    rating: 4.6,
    reviews: 0,
    img: ['#1A0600', '#380E00'],
    accentHue: 25,
    stats: { age: 28, height: '183 cm', reach: '185 cm', stance: 'Orthodox', nationality: 'Georgisch', gym: 'MMA Spirit Frankfurt', born: 'Tiflis, Georgien' },
    fightHistory: [
      { result: 'W', opponent: 'Leandro Silva', method: 'Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2025-12', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Tipsport' },
      { name: 'Venum' },
      { name: 'Georgian Warriors' },
    ],
  },
  {
    id: 'mateusz-legierski',
    name: 'Mateusz Legierski',
    city: 'Cieszyn',
    country: 'Poland',
    status: 'verified',
    styles: ['Grappler', 'Wrestler'],
    tags: ['OKTAGON', 'Champion', 'Lightweight', 'Poland'],
    weightClass: 'Lightweight',
    record: '11-1-0',
    rating: 4.5,
    reviews: 0,
    img: ['#1A0005', '#380010'],
    accentHue: 5,
    stats: { age: 29, height: '175 cm', reach: '178 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'Octagon Team Cieszyn', born: 'Cieszyn, Polen' },
    fightHistory: [
      { result: 'W', opponent: 'Akonne Wanliss', method: 'Decision', event: 'OKTAGON', round: 5, time: '5:00', date: '2025-12', org: 'OKTAGON' },
      { result: 'W', opponent: 'Matouš Kohout', method: 'Submission', event: 'OKTAGON', round: 1, time: '3:22', date: '2025-05', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Olimp Nutrition' },
      { name: 'Pitbull West Coast' },
    ],
  },
  {
    id: 'mago-machaev',
    name: 'Mago Machaev',
    city: 'Wien',
    country: 'Austria',
    status: 'verified',
    styles: ['Wrestler', 'Striker'],
    tags: ['OKTAGON', 'Champion', 'Featherweight', 'Austria'],
    weightClass: 'Featherweight',
    record: '15-1-0',
    rating: 4.7,
    reviews: 0,
    img: ['#1A1000', '#3A2200'],
    accentHue: 40,
    stats: { age: 26, height: '175 cm', reach: '178 cm', stance: 'Orthodox', nationality: 'Österreichisch', gym: 'UFD Gym Düsseldorf', born: 'Österreich' },
    fightHistory: [
      { result: 'W', opponent: 'Niko Samsonidse', method: 'Decision', event: 'OKTAGON', round: 5, time: '5:00', date: '2025-09', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Venum' },
      { name: 'Onyx' },
      { name: 'Toyo Tires' },
    ],
  },
  {
    id: 'gjoni-palokaj',
    name: 'Gjoni Palokaj',
    city: 'Hannover',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['OKTAGON', 'Featherweight', 'Germany', 'Hannover'],
    weightClass: 'Featherweight',
    record: '10-3-0',
    rating: 4.4,
    reviews: 0,
    img: ['#001020', '#001C38'],
    accentHue: 215,
    stats: { age: 30, height: '173 cm', reach: '175 cm', stance: 'Orthodox', nationality: 'Deutsch', gym: 'Fightschool Hannover', born: 'Hannover, Deutschland' },
    fightHistory: [
      { result: 'W', opponent: 'Jaroslav Pokorný', method: 'KO', event: 'OKTAGON', round: 1, time: '1:45', date: '2025-11', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Gym King' },
      { name: 'Sponsoo' },
      { name: 'Local Hannover Sponsors' },
    ],
  },
  {
    id: 'igor-severino',
    name: 'Igor Severino',
    city: 'Frankfurt',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['OKTAGON', 'Champion', 'Bantamweight', 'Finisher'],
    weightClass: 'Bantamweight',
    record: '10-1-0',
    rating: 4.5,
    reviews: 0,
    img: ['#1A1000', '#3A2800'],
    accentHue: 45,
    stats: { age: 23, height: '170 cm', reach: '172 cm', stance: 'Orthodox', nationality: 'Brasilianisch', gym: 'MMA Spirit Frankfurt', born: 'Brasilien' },
    fightHistory: [
      { result: 'W', opponent: 'Jonas Mågård', method: 'Decision', event: 'OKTAGON', round: 5, time: '5:00', date: '2026-03', org: 'OKTAGON' },
      { result: 'L', opponent: 'Andre Lima', method: 'DQ', event: 'UFC Fight Night', round: 1, time: '2:30', date: '2024-03', org: 'UFC' },
    ],
    sponsors: [
      { name: 'Tipsport' },
      { name: 'Venum' },
    ],
  },
  {
    id: 'krzysztof-jotko',
    name: 'Krzysztof Jotko',
    city: 'Warschau',
    country: 'Poland',
    status: 'verified',
    styles: ['Wrestler', 'MMA'],
    tags: ['OKTAGON', 'UFC Veteran', 'Middleweight', 'Poland'],
    weightClass: 'Middleweight',
    record: '25-6-0',
    rating: 4.5,
    reviews: 0,
    img: ['#1A0008', '#380015'],
    accentHue: 345,
    stats: { age: 36, height: '185 cm', reach: '196 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'American Top Team', born: 'Warschau, Polen' },
    fightHistory: [
      { result: 'W', opponent: 'Hojat Khajevand', method: 'Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2025-12', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Olimp' },
      { name: 'Pitbull West Coast' },
    ],
  },
  {
    id: 'dominik-humburger',
    name: 'Dominik Humburger',
    city: 'Liberec',
    country: 'Czechia',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['OKTAGON', 'Middleweight', 'Czechia', 'Army'],
    weightClass: 'Middleweight',
    record: '10-1-0',
    rating: 4.4,
    reviews: 0,
    img: ['#081408', '#101E10'],
    accentHue: 120,
    stats: { age: 30, height: '185 cm', reach: '188 cm', stance: 'Orthodox', nationality: 'Tschechisch', gym: 'Liberec MMA', born: 'Liberec, Tschechien' },
    fightHistory: [
      { result: 'W', opponent: 'Marek Mazúch', method: 'TKO', event: 'OKTAGON', round: 2, time: '2:55', date: '2026-04', org: 'OKTAGON' },
      { result: 'W', opponent: 'Jakub Běle', method: 'KO', event: 'OKTAGON', round: 1, time: '1:10', date: '2025-11', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Tipsport' },
      { name: 'Nike CZ' },
      { name: 'Under Armour' },
    ],
  },
  {
    id: 'piotr-wawrzyniak',
    name: 'Piotr Wawrzyniak',
    city: 'Poznań',
    country: 'Poland',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['OKTAGON', 'Middleweight', 'Poland', 'Heavy Hands'],
    weightClass: 'Middleweight',
    record: '13-6-0',
    rating: 4.3,
    reviews: 0,
    img: ['#1A0003', '#38000A'],
    accentHue: 3,
    stats: { age: 35, height: '180 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'Czerwony Smok Poznań', born: 'Poznań, Polen' },
    fightHistory: [
      { result: 'L', opponent: 'Patrik Kincl', method: 'Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2026-04', org: 'OKTAGON' },
      { result: 'W', opponent: 'Vlasto Čepo', method: 'TKO', event: 'OKTAGON', round: 3, time: '3:40', date: '2024-01', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Olimp Nutrition' },
      { name: 'SuperBet' },
    ],
  },
  {
    id: 'ronald-paradeiser',
    name: 'Ronald Paradeiser',
    city: 'Bratislava',
    country: 'Slovakia',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['OKTAGON', 'Lightweight', 'Slovakia', 'Rony'],
    weightClass: 'Lightweight',
    record: '20-9-0',
    rating: 4.4,
    reviews: 0,
    img: ['#001018', '#001C28'],
    accentHue: 195,
    stats: { age: 28, height: '187 cm', reach: '192 cm', stance: 'Orthodox', nationality: 'Slowakisch', gym: 'OFA Bratislava', born: 'Bratislava, Slowakei' },
    fightHistory: [
      { result: 'L', opponent: 'Ivan Buchinger', method: 'Submission', event: 'OKTAGON', round: 3, time: '4:20', date: '2026-02', org: 'OKTAGON' },
      { result: 'W', opponent: 'Losene Keita', method: 'Decision', event: 'OKTAGON', round: 3, time: '5:00', date: '2024-12', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Tipsport' },
      { name: 'Venum' },
      { name: 'Reebok Slovakia' },
    ],
  },
  {
    id: 'ion-surdu',
    name: 'Ion Surdu',
    city: 'Chisinau',
    country: 'Moldova',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['OKTAGON', 'Welterweight', 'Moldova', 'The Dracula'],
    weightClass: 'Welterweight',
    record: '15-6-0',
    rating: 4.5,
    reviews: 0,
    img: ['#150003', '#280008'],
    accentHue: 350,
    stats: { age: 31, height: '185 cm', reach: '188 cm', stance: 'Orthodox', nationality: 'Moldauisch', gym: 'MMA Spirit Frankfurt', born: 'Chisinau, Moldau' },
    fightHistory: [
      { result: 'W', opponent: 'Christian Jungwirth', method: 'TKO', event: 'OKTAGON', round: 1, time: '1:30', date: '2026-03', org: 'OKTAGON' },
      { result: 'W', opponent: 'Máté Kertész', method: 'KO', event: 'OKTAGON', round: 1, time: '0:55', date: '2025-09', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Monster Energy' },
      { name: 'Venum' },
      { name: 'SuperBet' },
    ],
  },
  {
    id: 'felix-klinkhammer',
    name: 'Felix Klinkhammer',
    city: 'Berlin',
    country: 'Germany',
    status: 'verified',
    styles: ['Grappler', 'BJJ'],
    tags: ['OKTAGON', 'Welterweight', 'Germany', 'Undefeated'],
    weightClass: 'Welterweight',
    record: '10-0-0',
    rating: 4.6,
    reviews: 0,
    img: ['#000A18', '#001230'],
    accentHue: 200,
    stats: { age: 31, height: '188 cm', reach: '190 cm', stance: 'Orthodox', nationality: 'Deutsch', gym: 'London Shootfighters', born: 'Berlin, Deutschland' },
    fightHistory: [
      { result: 'W', opponent: 'Andrej Kalašnik', method: 'Submission', event: 'OKTAGON', round: 1, time: '2:10', date: '2025-12', org: 'OKTAGON' },
    ],
    sponsors: [
      { name: 'Venum' },
      { name: 'Sponsoo' },
      { name: 'Gym King' },
    ],
  },
];

const COPY = {
  de: {
    // Header
    navHome: 'Home',
    navSubmit: 'Kämpfer melden',
    navImprint: 'Impressum',
    // Hero
    heroTagline: 'MMA-Kämpfer aus ganz Europa entdecken',
    searchPlaceholder: 'Kämpfer, Gewichtsklasse oder Stadt suchen…',
    // Filter
    proOnly: 'Nur Profis',
    country: 'Land',
    allCountries: 'Alle Länder',
    city: 'Stadt',
    allCities: 'Alle Städte',
    // Status labels
    statusVerified: 'Profi',
    statusSelf: 'Semi-Profi',
    statusUnknown: 'Amateur',
    // Results
    resultsCount: (n) => `${n} ${n === 1 ? 'Kämpfer' : 'Kämpfer'} in Europa`,
    emptyTitle: 'Keine Ergebnisse',
    emptyBody: 'Versuche eine andere Stadt oder Gewichtsklasse.',
    reset: 'Filter zurücksetzen',
    featured: 'Featured',
    recordLabel: 'Rekord',
    // Footer
    footerBlurb: 'Die vollständigste MMA-Datenbank für Europa. Faktenbasiert, transparent, werbefrei.',
    footerSections: {
      product: ['Home', 'Kämpfer melden', 'Karte', 'Gewichtsklassen'],
      company: ['Über uns', 'Impressum', 'Datenschutz', 'Kontakt'],
    },
    footerSectionTitles: { product: 'Produkt', company: 'Rechtliches' },
    footerLinks: {
      'Home': 'FightFolio Homepage.html',
      'Kämpfer melden': '#',
      'Karte': '#',
      'Gewichtsklassen': '#',
      'Über uns': '#',
      'Impressum': '#',
      'Datenschutz': '#',
      'Kontakt': '#',
    },
    footerMadeWith: 'Gemacht mit 🥊 für AT & DE',
    newsletter: 'Neue Kämpfer per E-Mail',
    newsletterCta: 'Anmelden',
    copyright: '© 2026 FightFolio.at — Alle Rechte vorbehalten.',
  },
  en: {
    navHome: 'Home',
    navSubmit: 'Submit Fighter',
    navImprint: 'Imprint',
    heroTagline: 'Discover MMA fighters across Europe',
    searchPlaceholder: 'Search fighters, weight class, or city…',
    proOnly: 'Pros only',
    country: 'Country',
    allCountries: 'All countries',
    city: 'City',
    allCities: 'All cities',
    statusVerified: 'Pro Fighter',
    statusSelf: 'Semi-Pro',
    statusUnknown: 'Amateur',
    resultsCount: (n) => `${n} ${n === 1 ? 'fighter' : 'fighters'} across Europe`,
    emptyTitle: 'No results',
    emptyBody: 'Try a different city or weight class.',
    reset: 'Reset filters',
    featured: 'Featured',
    recordLabel: 'Record',
    footerBlurb: 'The most complete MMA database for Europe. Fact-based, transparent, ad-free.',
    footerSections: {
      product: ['Home', 'Submit Fighter', 'Map', 'Weight Classes'],
      company: ['About', 'Imprint', 'Privacy', 'Contact'],
    },
    footerSectionTitles: { product: 'Product', company: 'Legal' },
    footerLinks: {
      'Home': 'FightFolio Homepage.html',
      'Submit Fighter': '#',
      'Map': '#',
      'Weight Classes': '#',
      'About': '#',
      'Imprint': '#',
      'Privacy': '#',
      'Contact': '#',
    },
    footerMadeWith: 'Made with 🥊 for AT & DE',
    newsletter: 'New fighters by email',
    newsletterCta: 'Subscribe',
    copyright: '© 2026 FightFolio.at — All rights reserved.',
  },
};

const FIGHT_STYLES = ['Striker', 'Kickboxer', 'Wrestler', 'BJJ', 'Grappler', 'MMA'];

const CITIES = [
  // Austria
  { id: 'Wien',       label: 'Wien 🇦🇹',       country: 'Austria' },
  { id: 'Graz',       label: 'Graz 🇦🇹',       country: 'Austria' },
  { id: 'Salzburg',   label: 'Salzburg 🇦🇹',   country: 'Austria' },
  { id: 'Innsbruck',  label: 'Innsbruck 🇦🇹',  country: 'Austria' },
  { id: 'Linz',       label: 'Linz 🇦🇹',       country: 'Austria' },
  // Germany
  { id: 'Frankfurt',  label: 'Frankfurt 🇩🇪',  country: 'Germany' },
  { id: 'München',    label: 'München 🇩🇪',    country: 'Germany' },
  { id: 'Hamburg',    label: 'Hamburg 🇩🇪',    country: 'Germany' },
  { id: 'Düsseldorf', label: 'Düsseldorf 🇩🇪', country: 'Germany' },
  { id: 'Köln',       label: 'Köln 🇩🇪',       country: 'Germany' },
  { id: 'Leipzig',    label: 'Leipzig 🇩🇪',    country: 'Germany' },
  { id: 'Stuttgart',  label: 'Stuttgart 🇩🇪',  country: 'Germany' },
  { id: 'Berlin',     label: 'Berlin 🇩🇪',     country: 'Germany' },
  // Spain
  { id: 'Alicante',   label: 'Alicante 🇪🇸',   country: 'Spain' },
  // United Kingdom
  { id: 'Liverpool',  label: 'Liverpool 🇬🇧',  country: 'United Kingdom' },
  { id: 'Birmingham', label: 'Birmingham 🇬🇧', country: 'United Kingdom' },
  // France
  { id: 'Paris',      label: 'Paris 🇫🇷',      country: 'France' },
  { id: 'Nizza',      label: 'Nizza 🇫🇷',      country: 'France' },
  // Poland
  { id: 'Warschau',   label: 'Warschau 🇵🇱',   country: 'Poland' },
  { id: 'Poznań',     label: 'Poznań 🇵🇱',     country: 'Poland' },
  // Italy
  { id: 'Rom',        label: 'Rom 🇮🇹',        country: 'Italy' },
  // Netherlands
  { id: 'Leiden',     label: 'Leiden 🇳🇱',     country: 'Netherlands' },
  { id: 'Breda',      label: 'Breda 🇳🇱',      country: 'Netherlands' },
  // Sweden
  { id: 'Stockholm',  label: 'Stockholm 🇸🇪',  country: 'Sweden' },
  // United Kingdom (Batch 3)
  { id: 'Manchester', label: 'Manchester 🇬🇧', country: 'United Kingdom' },
  { id: 'Cardiff',    label: 'Cardiff 🇬🇧',    country: 'United Kingdom' },
  { id: 'Ipswich',    label: 'Ipswich 🇬🇧',    country: 'United Kingdom' },
  // Ireland
  { id: 'Belfast',    label: 'Belfast 🇮🇪',    country: 'Ireland' },
  // Portugal
  { id: 'Lissabon',   label: 'Lissabon 🇵🇹',   country: 'Portugal' },
  // Poland (Batch 3)
  { id: 'Stettin',    label: 'Stettin 🇵🇱',    country: 'Poland' },
  { id: 'Łódź',      label: 'Łódź 🇵🇱',       country: 'Poland' },
  // Netherlands (Batch 3)
  { id: 'Amsterdam',  label: 'Amsterdam 🇳🇱',  country: 'Netherlands' },
  // Denmark
  { id: 'Kopenhagen', label: 'Kopenhagen 🇩🇰', country: 'Denmark' },
  // Iceland
  { id: 'Reykjavik',  label: 'Reykjavik 🇮🇸',  country: 'Iceland' },
  // Ireland (Batch 5)
  { id: 'Dublin',     label: 'Dublin 🇮🇪',      country: 'Ireland' },
  // Spain (Batch 5)
  { id: 'Gijón',     label: 'Gijón 🇪🇸',       country: 'Spain' },
  { id: 'Madrid',    label: 'Madrid 🇪🇸',      country: 'Spain' },
  // Russia (Batch 5)
  { id: 'Moskau',    label: 'Moskau 🇷🇺',      country: 'Russia' },
  // Lithuania (Batch 5)
  { id: 'Vilnius',   label: 'Vilnius 🇱🇹',     country: 'Lithuania' },
  // Belgium (Batch 5)
  { id: 'Brüssel',   label: 'Brüssel 🇧🇪',     country: 'Belgium' },
  // United Kingdom (Batch 5)
  { id: 'London',    label: 'London 🇬🇧',      country: 'United Kingdom' },
  // Albania (Batch 5)
  { id: 'Tirana',    label: 'Tirana 🇦🇱',      country: 'Albania' },
  // Slovakia (Batch 5)
  { id: 'Bratislava', label: 'Bratislava 🇸🇰', country: 'Slovakia' },
  // Serbia (Batch 5)
  { id: 'Belgrad',   label: 'Belgrad 🇷🇸',     country: 'Serbia' },
  // Czechia (Batch 6)
  { id: 'Prag',      label: 'Prag 🇨🇿',        country: 'Czechia' },
  { id: 'Liberec',   label: 'Liberec 🇨🇿',     country: 'Czechia' },
  // Cyprus (Batch 6)
  { id: 'Nikosia',   label: 'Nikosia 🇨🇾',     country: 'Cyprus' },
  // Slovenia (Batch 6)
  { id: 'Ljubljana', label: 'Ljubljana 🇸🇮',   country: 'Slovenia' },
  // Slovakia (Batch 6)
  { id: 'Košice',    label: 'Košice 🇸🇰',      country: 'Slovakia' },
  // Germany (Batch 7)
  { id: 'Hannover',  label: 'Hannover 🇩🇪',    country: 'Germany' },
  // Georgia (Batch 7)
  { id: 'Tiflis',    label: 'Tiflis 🇬🇪',      country: 'Georgia' },
  // Poland (Batch 7)
  { id: 'Cieszyn',   label: 'Cieszyn 🇵🇱',     country: 'Poland' },
  // Moldova (Batch 7)
  { id: 'Chisinau',  label: 'Chisinau 🇲🇩',    country: 'Moldova' },
];

const COUNTRIES = [
  { id: 'Austria',        label: '🇦🇹 Austria' },
  { id: 'Germany',        label: '🇩🇪 Germany' },
  { id: 'Spain',          label: '🇪🇸 Spain' },
  { id: 'United Kingdom', label: '🇬🇧 United Kingdom' },
  { id: 'France',         label: '🇫🇷 France' },
  { id: 'Poland',         label: '🇵🇱 Poland' },
  { id: 'Italy',          label: '🇮🇹 Italy' },
  { id: 'Netherlands',    label: '🇳🇱 Netherlands' },
  { id: 'Croatia',        label: '🇭🇷 Croatia' },
  { id: 'Sweden',         label: '🇸🇪 Sweden' },
  { id: 'Ireland',        label: '🇮🇪 Ireland' },
  { id: 'Portugal',       label: '🇵🇹 Portugal' },
  { id: 'Denmark',        label: '🇩🇰 Denmark' },
  { id: 'Iceland',        label: '🇮🇸 Iceland' },
  { id: 'Belgium',        label: '🇧🇪 Belgium' },
  { id: 'Serbia',         label: '🇷🇸 Serbia' },
  { id: 'Lithuania',      label: '🇱🇹 Lithuania' },
  { id: 'Albania',        label: '🇦🇱 Albania' },
  { id: 'Slovakia',       label: '🇸🇰 Slovakia' },
  { id: 'Russia',         label: '🇷🇺 Russia' },
  { id: 'Georgia',        label: '🇬🇪 Georgia' },
  { id: 'Czechia',        label: '🇨🇿 Czechia' },
  { id: 'Cyprus',         label: '🇨🇾 Cyprus' },
  { id: 'Slovenia',       label: '🇸🇮 Slovenia' },
  { id: 'Moldova',        label: '🇲🇩 Moldova' },
];

Object.assign(window, { FIGHTERS, COPY, FIGHT_STYLES, CITIES, COUNTRIES });
