// FightFolio — MMA Fighters data + copy translations

const FIGHTERS = [
  // ── ÖSTERREICH ────────────────────────────────────────────────────────────
  {
    id: 'aleksandar-rakic',
    name: 'Aleksandar Rakić',
    city: 'Wien',
    country: 'Austria',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Top-10', 'LHW', 'Österreich'],
    weightClass: 'Light Heavyweight',
    record: '14-4-0',
    rating: 4.9,
    reviews: 0,
    featured: true,
    img: ['#1A0A00', '#3D1F00'],
    accentHue: 42,
    sponsors: [
      { name: 'Venum' },
      { name: 'Monster Energy' },
      { name: 'Phantom Athletics' },
      { name: 'A1 Telekom Austria' }
    ],
  },
  {
    id: 'ismail-naurdiev',
    name: 'Ismail Naurdiev',
    city: 'Wien',
    country: 'Austria',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Welterweight', 'Österreich', 'KO-Artist'],
    weightClass: 'Welterweight',
    record: '16-4-0',
    rating: 4.7,
    reviews: 0,
    img: ['#001A3D', '#003580'],
    accentHue: 210,
    sponsors: [
      { name: 'Gymking' },
      { name: 'Bet-at-home' },
      { name: 'T-Mobile Austria' }
    ],
  },
  {
    id: 'bogdan-grad',
    name: 'Bogdan Grad',
    city: 'Graz',
    country: 'Austria',
    status: 'verified',
    styles: ['Wrestler', 'MMA'],
    tags: ['OKTAGON', 'Heavyweight', 'Steiermark'],
    weightClass: 'Heavyweight',
    record: '13-5-0',
    rating: 4.5,
    reviews: 0,
    img: ['#0A1A00', '#1A3D00'],
    accentHue: 105,
    sponsors: [
      { name: 'Ettl Bros' },
      { name: 'Raiffeisen Sport' },
      { name: 'Nutri-Direct' }
    ],
  },
  {
    id: 'rodrigo-nascimento',
    name: 'Rodrigo Nascimento',
    city: 'Wien',
    country: 'Austria',
    status: 'verified',
    styles: ['Wrestler', 'BJJ'],
    tags: ['UFC', 'Heavyweight', 'Wien', 'Brasilien'],
    weightClass: 'Heavyweight',
    record: '10-2-0',
    rating: 4.6,
    reviews: 0,
    img: ['#1A001A', '#3D003D'],
    accentHue: 300,
    sponsors: [
      { name: 'Venum' },
      { name: 'MHP' },
      { name: 'Cybex' }
    ],
  },
  {
    id: 'florian-aberger',
    name: 'Florian Aberger',
    city: 'Graz',
    country: 'Austria',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['REGIONAL', 'Middleweight', 'Steiermark', 'IMMAF'],
    weightClass: 'Middleweight',
    record: '9-1-0',
    rating: 4.4,
    reviews: 0,
    img: ['#001A00', '#003D00'],
    accentHue: 90,
    sponsors: [
      { name: 'Steiermärkische Sparkasse' },
      { name: 'Hervis Sports' },
      { name: 'Calibian Management' }
    ],
  },
  {
    id: 'wilhelm-ott',
    name: 'Wilhelm Ott',
    city: 'Linz',
    country: 'Austria',
    status: 'self',
    styles: ['Striker', 'MMA'],
    tags: ['REGIONAL', 'Middleweight', 'Linz', 'BKFC'],
    weightClass: 'Middleweight',
    record: '19-19-1',
    rating: 4.0,
    reviews: 0,
    img: ['#0A0A1A', '#1A1A3D'],
    accentHue: 220,
    sponsors: [
      { name: 'Ott Security' },
      { name: 'Empire Sports' }
    ],
  },
  // ── DEUTSCHLAND ───────────────────────────────────────────────────────────
  {
    id: 'christian-eckerlin',
    name: 'Christian Eckerlin',
    city: 'Frankfurt',
    country: 'Germany',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    tags: ['GLORY', 'ONE FC', 'MMA', 'Frankfurt'],
    weightClass: 'Middleweight',
    record: '28-15-0',
    rating: 4.6,
    reviews: 0,
    img: ['#1A0000', '#3D0000'],
    accentHue: 0,
    sponsors: [
      { name: 'Eckerlin Logistics' },
      { name: 'Mainova' },
      { name: 'König Pilsener' }
    ],
  },
  {
    id: 'kerim-engizek',
    name: 'Kerim Engizek',
    city: 'Düsseldorf',
    country: 'Germany',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    tags: ['GLORY', 'Lightweight', 'Deutschland', 'KO-Artist'],
    weightClass: 'Lightweight',
    record: '45-8-0',
    rating: 4.8,
    reviews: 0,
    img: ['#001A1A', '#003D3D'],
    accentHue: 180,
    sponsors: [
      { name: 'Onyx' },
      { name: 'Bose Germany' },
      { name: 'Snipes' }
    ],
  },
  {
    id: 'nick-hein',
    name: 'Nick Hein',
    city: 'Hamburg',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'BJJ'],
    tags: ['UFC', 'Lightweight', 'Hamburg', 'Judo'],
    weightClass: 'Lightweight',
    record: '13-4-0',
    rating: 4.4,
    reviews: 0,
    img: ['#0A0A1A', '#15153D'],
    accentHue: 240,
    sponsors: [
      { name: 'Sponsoo' },
      { name: 'Under Armour Germany' },
      { name: 'Sky Sport' }
    ],
  },
  {
    id: 'dennis-siver',
    name: 'Dennis Siver',
    city: 'München',
    country: 'Germany',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    tags: ['UFC', 'Featherweight', 'München', 'Veteran'],
    weightClass: 'Featherweight',
    record: '24-13-0',
    rating: 4.3,
    reviews: 0,
    img: ['#1A0A1A', '#3D1A3D'],
    accentHue: 280,
    sponsors: [
      { name: 'Kwon' },
      { name: 'FitX' }
    ],
  },
  {
    id: 'daniel-weichel',
    name: 'Daniel Weichel',
    city: 'Frankfurt',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['Bellator', 'OKTAGON', 'Featherweight', 'M-1 Global'],
    weightClass: 'Featherweight',
    record: '45-14-0',
    rating: 4.5,
    reviews: 0,
    img: ['#1A0A00', '#3D1800'],
    accentHue: 15,
    sponsors: [
      { name: 'Spirit MMA' },
      { name: 'Matrix Fitness' },
      { name: 'Lonsdale Germany' }
    ],
  },
  {
    id: 'joilton-lutterbach',
    name: 'Joilton Lutterbach',
    city: 'Köln',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'OKTAGON', 'Middleweight', 'Köln'],
    weightClass: 'Middleweight',
    record: '41-11-0',
    rating: 4.3,
    reviews: 0,
    img: ['#001A18', '#003D33'],
    accentHue: 170,
    sponsors: [
      { name: 'Paffensport' },
      { name: 'Zec+ Nutrition' },
      { name: 'MyProtein' }
    ],
  },
  {
    id: 'frederic-vosgrone',
    name: 'Frédéric Vosgröne',
    city: 'Düsseldorf',
    country: 'Germany',
    status: 'verified',
    styles: ['BJJ', 'Grappler'],
    tags: ['OKTAGON', 'Light Heavyweight', 'BJJ World Champ', 'ADCC'],
    weightClass: 'Light Heavyweight',
    record: '5-0-0',
    rating: 4.6,
    reviews: 0,
    img: ['#0D001A', '#20003D'],
    accentHue: 270,
    sponsors: [
      { name: 'UFD Gym' },
      { name: 'Olimp Sport Nutrition' }
    ],
  },
  {
    id: 'sascha-sharma',
    name: 'Sascha Sharma',
    city: 'Stuttgart',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'BJJ'],
    tags: ['TUF', 'Lightweight', 'Pforzheim', 'Kong\'s Gym'],
    weightClass: 'Lightweight',
    record: '17-5-0',
    rating: 4.1,
    reviews: 0,
    img: ['#1A1200', '#3D2A00'],
    accentHue: 35,
    sponsors: [
      { name: 'Stallion Gym' },
      { name: 'Vayumedia' }
    ],
  },
  {
    id: 'sebastian-holzmann',
    name: 'Sebastian Holzmann',
    city: 'Leipzig',
    country: 'Germany',
    status: 'self',
    styles: ['Striker', 'MMA'],
    tags: ['REGIONAL', 'Lightweight', 'Halle', 'Sachsen-Anhalt'],
    weightClass: 'Lightweight',
    record: '6-2-0',
    rating: 3.9,
    reviews: 0,
    img: ['#001218', '#002030'],
    accentHue: 200,
    sponsors: [
      { name: 'Leipzig Lions' },
      { name: 'Power & Fitness Shop' }
    ],
  },
  // ── SPANIEN ───────────────────────────────────────────────────────────────
  {
    id: 'ilia-topuria',
    name: 'Ilia Topuria',
    city: 'Alicante',
    country: 'Spain',
    status: 'verified',
    styles: ['Striker', 'BJJ'],
    tags: ['UFC', 'Champion', 'Featherweight', 'El Matador'],
    weightClass: 'Featherweight',
    record: '17-0-0',
    rating: 5.0,
    reviews: 0,
    featured: true,
    img: ['#2A0000', '#700000'],
    accentHue: 0,
    stats: { age: 29, height: '170 cm', reach: '175 cm', stance: 'Orthodox', nationality: 'Georgisch-Spanisch', gym: 'Kings MMA', born: 'Tiflis, Georgien' },
    sponsors: [
      { name: 'Oura Ring' },
      { name: 'Venum' },
      { name: 'Keiser' },
      { name: 'Black Star Sports' }
    ],
  },
  // ── GROSSBRITANNIEN ───────────────────────────────────────────────────────
  {
    id: 'tom-aspinall',
    name: 'Tom Aspinall',
    city: 'Liverpool',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Kickboxer', 'BJJ'],
    tags: ['UFC', 'Interim Champion', 'Heavyweight', 'Team Kaobon'],
    weightClass: 'Heavyweight',
    record: '15-3-0',
    rating: 4.9,
    reviews: 0,
    img: ['#001040', '#002080'],
    accentHue: 220,
    stats: { age: 33, height: '193 cm', reach: '196 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'Team Kaobon', born: 'Wigan, England' },
    sponsors: [
      { name: 'Gymshark' },
      { name: 'MyProtein' },
      { name: 'Vitality' },
      { name: 'Venum' }
    ],
  },
  // ── POLEN ─────────────────────────────────────────────────────────────────
  {
    id: 'jan-blachowicz',
    name: 'Jan Błachowicz',
    city: 'Warschau',
    country: 'Poland',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Former Champion', 'LHW', 'Polish Power'],
    weightClass: 'Light Heavyweight',
    record: '29-10-1',
    rating: 4.7,
    reviews: 0,
    img: ['#1A0008', '#3D0015'],
    accentHue: 350,
    stats: { age: 43, height: '185 cm', reach: '193 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'KSW Akademia', born: 'Cieszyn, Polen' },
    sponsors: [
      { name: 'Subaru Poland' },
      { name: 'SuperBet' },
      { name: 'Olimp Sport Nutrition' }
    ],
  },
  // ── FRANKREICH ────────────────────────────────────────────────────────────
  {
    id: 'benoit-saint-denis',
    name: 'Benoît Saint-Denis',
    city: 'Paris',
    country: 'France',
    status: 'verified',
    styles: ['Wrestler', 'Striker'],
    tags: ['UFC', 'Top-10', 'Lightweight', 'God of War'],
    weightClass: 'Lightweight',
    record: '14-3-0',
    rating: 4.6,
    reviews: 0,
    img: ['#00001A', '#00003D'],
    accentHue: 240,
    stats: { age: 30, height: '178 cm', reach: '185 cm', stance: 'Orthodox', nationality: 'Französisch', gym: 'MMA Factory Paris', born: 'Frankreich' },
    sponsors: [
      { name: 'Venum' },
      { name: 'Unkut' },
      { name: 'Reebok France' }
    ],
  },
  {
    id: 'salahdine-parnasse',
    name: 'Salahdine Parnasse',
    city: 'Paris',
    country: 'France',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['KSW', 'Multi-Champion', 'Featherweight', 'Mbappé des MMA'],
    weightClass: 'Featherweight',
    record: '21-2-0',
    rating: 4.8,
    reviews: 0,
    img: ['#0A001A', '#1A0040'],
    accentHue: 270,
    stats: { age: 30, height: '170 cm', reach: '177 cm', stance: 'Orthodox', nationality: 'Französisch', gym: 'Team Noël Le Gall', born: 'Paris, Frankreich' },
    sponsors: [
      { name: 'Free Mobile' },
      { name: 'Venum' },
      { name: 'KSW' }
    ],
  },
  {
    id: 'mateusz-gamrot',
    name: 'Mateusz Gamrot',
    city: 'Poznań',
    country: 'Poland',
    status: 'verified',
    styles: ['Wrestler', 'MMA'],
    tags: ['UFC', 'Top-5', 'Lightweight', 'Gamer'],
    weightClass: 'Lightweight',
    record: '25-3-0',
    rating: 4.7,
    reviews: 0,
    img: ['#200004', '#400008'],
    accentHue: 10,
    stats: { age: 34, height: '175 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'Grappling Poznań', born: 'Gdańsk, Polen' },
    sponsors: [
      { name: 'Red Bull' },
      { name: 'New Balance Poland' },
      { name: 'Olimp Nutrition' }
    ],
  },
  {
    id: 'manon-fiorot',
    name: 'Manon Fiorot',
    city: 'Nizza',
    country: 'France',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Interim Champion', 'Flyweight', 'The Beast'],
    weightClass: 'Flyweight',
    record: '13-1-0',
    rating: 4.8,
    reviews: 0,
    img: ['#000A1A', '#001040'],
    accentHue: 200,
    stats: { age: 34, height: '165 cm', reach: '168 cm', stance: 'Orthodox', nationality: 'Französisch', gym: 'MMA Factory Nice', born: 'Nizza, Frankreich' },
    sponsors: [
      { name: 'PUMA' },
      { name: 'Venum' },
      { name: 'Nice MMA Shop' }
    ],
  },
  // ── ITALIEN ───────────────────────────────────────────────────────────────
  {
    id: 'marvin-vettori',
    name: 'Marvin Vettori',
    city: 'Rom',
    country: 'Italy',
    status: 'verified',
    styles: ['Wrestler', 'Striker'],
    tags: ['UFC', 'Middleweight', 'Italian Dream', 'Kings MMA'],
    weightClass: 'Middleweight',
    record: '19-7-1',
    rating: 4.5,
    reviews: 0,
    img: ['#001A08', '#003D15'],
    accentHue: 120,
    stats: { age: 32, height: '185 cm', reach: '192 cm', stance: 'Orthodox', nationality: 'Italienisch', gym: 'Kings MMA', born: 'Mezzocorona, Italien' },
    sponsors: [
      { name: 'Dolce & Gabbana' },
      { name: 'Venum' },
      { name: 'Everlast' },
      { name: 'Leone 1947' }
    ],
  },
  // ── GROSSBRITANNIEN ───────────────────────────────────────────────────────
  {
    id: 'leon-edwards',
    name: 'Leon Edwards',
    city: 'Birmingham',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Former Champion', 'Welterweight', 'Rocky'],
    weightClass: 'Welterweight',
    record: '22-6-0',
    rating: 4.8,
    reviews: 0,
    img: ['#001018', '#002030'],
    accentHue: 195,
    stats: { age: 34, height: '183 cm', reach: '188 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'Team Renegade', born: 'Birmingham, England' },
    sponsors: [
      { name: 'Moncler' },
      { name: 'Monster Energy' },
      { name: 'Venum' },
      { name: 'Wow Hydrate' }
    ],
  },
  // ── NIEDERLANDE ───────────────────────────────────────────────────────────
  {
    id: 'gegard-mousasi',
    name: 'Gegard Mousasi',
    city: 'Leiden',
    country: 'Netherlands',
    status: 'verified',
    styles: ['Striker', 'BJJ'],
    tags: ['Bellator', 'UFC', 'PFL', 'Legend', 'Middleweight'],
    weightClass: 'Middleweight',
    record: '49-9-2',
    rating: 4.9,
    reviews: 0,
    img: ['#1A0A00', '#3D1800'],
    accentHue: 30,
    stats: { age: 40, height: '193 cm', reach: '196 cm', stance: 'Orthodox', nationality: 'Niederländisch-Armenisch', gym: "Mike's Gym", born: 'Isfahan, Iran' },
    sponsors: [
      { name: '32Red' },
      { name: 'Affliction' },
      { name: 'Venum' }
    ],
  },
  // ── ITALIEN ───────────────────────────────────────────────────────────────
  {
    id: 'alessio-di-chirico',
    name: 'Alessio Di Chirico',
    city: 'Rom',
    country: 'Italy',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Veteran', 'Middleweight', 'Italy'],
    weightClass: 'Middleweight',
    record: '13-7-0',
    rating: 4.2,
    reviews: 0,
    img: ['#001208', '#002810'],
    accentHue: 145,
    stats: { age: 34, height: '185 cm', reach: '190 cm', stance: 'Southpaw', nationality: 'Italienisch', gym: 'Minerva MMA Roma', born: 'Rom, Italien' },
    sponsors: [
      { name: 'Leone 1947' },
      { name: 'EthicSport' }
    ],
  },
  // ── GROSSBRITANNIEN ───────────────────────────────────────────────────────
  {
    id: 'paddy-pimblett',
    name: 'Paddy Pimblett',
    city: 'Liverpool',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['BJJ', 'Striker'],
    tags: ['UFC', 'Lightweight', 'The Baddy', 'Liverpool'],
    weightClass: 'Lightweight',
    record: '22-3-0',
    rating: 4.6,
    reviews: 0,
    img: ['#0A0020', '#1A0040'],
    accentHue: 260,
    stats: { age: 31, height: '178 cm', reach: '178 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'Next Generation Liverpool', born: 'Liverpool, England' },
    sponsors: [
      { name: 'Barstool Sports' },
      { name: 'Applied Nutrition' }
    ],
  },
  // ── NIEDERLANDE ───────────────────────────────────────────────────────────
  {
    id: 'reinier-de-ridder',
    name: 'Reinier de Ridder',
    city: 'Breda',
    country: 'Netherlands',
    status: 'verified',
    styles: ['Grappler', 'BJJ'],
    tags: ['ONE FC', 'UFC', 'Middleweight', 'Dutch Knight'],
    weightClass: 'Middleweight',
    record: '17-2-0',
    rating: 4.7,
    reviews: 0,
    img: ['#1A0800', '#3D1500'],
    accentHue: 45,
    stats: { age: 36, height: '193 cm', reach: '196 cm', stance: 'Orthodox', nationality: 'Niederländisch', gym: 'Allstars Training Center', born: 'Breda, Niederlande' },
    sponsors: [
      { name: 'Venum' },
      { name: 'MyProtein' },
      { name: 'Dutch Combat Brands' }
    ],
  },
  // ── KROATIEN ──────────────────────────────────────────────────────────────
  {
    id: 'roberto-soldic',
    name: 'Roberto Soldić',
    city: 'Düsseldorf',
    country: 'Croatia',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['ONE', 'KSW', 'Welterweight', 'Robocop', 'KO-Artist'],
    weightClass: 'Welterweight',
    record: '20-4-0',
    rating: 4.8,
    reviews: 0,
    img: ['#1A0010', '#3D0020'],
    accentHue: 330,
    stats: { age: 31, height: '183 cm', reach: '185 cm', stance: 'Southpaw', nationality: 'Kroatisch', gym: 'UFD Gym Düsseldorf', born: 'Split, Kroatien' },
    sponsors: [
      { name: 'Olimp' },
      { name: 'SuperBet' },
      { name: 'Paffensport' }
    ],
  },
  // ── SCHWEDEN ──────────────────────────────────────────────────────────────
  {
    id: 'khamzat-chimaev',
    name: 'Khamzat Chimaev',
    city: 'Stockholm',
    country: 'Sweden',
    status: 'verified',
    styles: ['Wrestler', 'Striker'],
    tags: ['UFC', 'Middleweight', 'Borz', 'Top-5', 'Undefeated'],
    weightClass: 'Middleweight',
    record: '14-0-0',
    rating: 4.9,
    reviews: 0,
    img: ['#001A10', '#003D20'],
    accentHue: 160,
    stats: { age: 32, height: '183 cm', reach: '185 cm', stance: 'Orthodox', nationality: 'Schwedisch-Tschetschenisch', gym: 'Allstars Stockholm', born: 'Tschetschenien, Russland' },
    sponsors: [
      { name: 'Smilodox' },
      { name: 'Venum' }
    ],
  },
  // ── FRANKREICH (Batch 3) ──────────────────────────────────────────────────
  {
    id: 'ciryl-gane',
    name: 'Ciryl Gane',
    city: 'Paris',
    country: 'France',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Contender', 'Heavyweight', 'MMA Factory'],
    weightClass: 'Heavyweight',
    record: '13-2-0',
    rating: 4.8,
    reviews: 0,
    img: ['#001020', '#002050'],
    accentHue: 230,
    stats: { age: 35, height: '196 cm', reach: '211 cm', stance: 'Orthodox', nationality: 'Französisch', gym: 'MMA Factory Paris', born: 'Frankreich' },
    sponsors: [
      { name: 'Venum' },
      { name: 'Gymshark' },
      { name: 'Major' },
      { name: 'Crypto.com' }
    ],
  },
  // ── GROSSBRITANNIEN (Batch 3) ─────────────────────────────────────────────
  {
    id: 'michael-bisping',
    name: 'Michael Bisping',
    city: 'Manchester',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Hall of Fame', 'Former Champion', 'The Count'],
    weightClass: 'Middleweight',
    record: '30-9-0',
    rating: 4.8,
    reviews: 0,
    img: ['#0A0A20', '#15153D'],
    accentHue: 215,
    stats: { age: 47, height: '185 cm', reach: '190 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'Tristar Gym (ret.)', born: 'Manchester, England' },
    sponsors: [
      { name: 'Manscaped' },
      { name: 'DraftKings' },
      { name: 'Sledgehammer Whiskey' },
      { name: 'MyProtein' }
    ],
  },
  // ── POLEN (Batch 3) ───────────────────────────────────────────────────────
  {
    id: 'joanna-jedrzejczyk',
    name: 'Joanna Jędrzejczyk',
    city: 'Warschau',
    country: 'Poland',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Former Champion', 'Strawweight', 'Muay Thai'],
    weightClass: 'Strawweight',
    record: '16-5-0',
    rating: 4.9,
    reviews: 0,
    img: ['#200006', '#430010'],
    accentHue: 345,
    stats: { age: 38, height: '165 cm', reach: '168 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'Tiger Muay Thai', born: 'Białystok, Polen' },
    sponsors: [
      { name: 'PUMA Poland' },
      { name: 'Samsung Poland' },
      { name: 'Dietly' },
      { name: 'MyProtein' }
    ],
  },
  // ── IRLAND ────────────────────────────────────────────────────────────────
  {
    id: 'paul-hughes',
    name: 'Paul Hughes',
    city: 'Belfast',
    country: 'Ireland',
    status: 'verified',
    styles: ['Striker', 'Wrestler'],
    tags: ['PFL', 'Bellator', 'Lightweight', 'Belfast'],
    weightClass: 'Lightweight',
    record: '14-1-0',
    rating: 4.7,
    reviews: 0,
    img: ['#002010', '#004820'],
    accentHue: 140,
    stats: { age: 28, height: '175 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Irisch', gym: 'SBG Ireland', born: 'Belfast, Irland' },
    sponsors: [
      { name: 'Monster Energy' },
      { name: 'Gym King' },
      { name: 'Empire Fighting Chance' }
    ],
  },
  // ── SCHWEDEN (Batch 3) ────────────────────────────────────────────────────
  {
    id: 'alexander-gustafsson',
    name: 'Alexander Gustafsson',
    city: 'Stockholm',
    country: 'Sweden',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Legend', 'LHW', 'The Mauler'],
    weightClass: 'Light Heavyweight',
    record: '18-8-0',
    rating: 4.8,
    reviews: 0,
    img: ['#001A1A', '#003D3D'],
    accentHue: 185,
    stats: { age: 39, height: '193 cm', reach: '196 cm', stance: 'Southpaw', nationality: 'Schwedisch', gym: 'Allstars Training Center', born: 'Arboga, Schweden' },
    sponsors: [
      { name: 'Unibet' },
      { name: 'MyProtein' },
      { name: 'Bad Boy' }
    ],
  },
  // ── PORTUGAL ──────────────────────────────────────────────────────────────
  {
    id: 'manel-kape',
    name: 'Manel Kape',
    city: 'Lissabon',
    country: 'Portugal',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Flyweight', 'Starboy', 'Rizin'],
    weightClass: 'Flyweight',
    record: '19-7-0',
    rating: 4.5,
    reviews: 0,
    img: ['#1A0A00', '#3A1800'],
    accentHue: 25,
    stats: { age: 32, height: '168 cm', reach: '178 cm', stance: 'Orthodox', nationality: 'Portugiesisch', gym: 'MMA Factory Lissabon', born: 'Angola' },
    sponsors: [
      { name: 'Venum' },
      { name: 'Monster Energy' },
      { name: 'Prio Energy' }
    ],
  },
  // ── POLEN (Batch 3) ───────────────────────────────────────────────────────
  {
    id: 'michal-materla',
    name: 'Michał Materla',
    city: 'Stettin',
    country: 'Poland',
    status: 'verified',
    styles: ['Wrestler', 'MMA'],
    tags: ['KSW', 'Legend', 'Middleweight', 'Berserker'],
    weightClass: 'Middleweight',
    record: '33-11-0',
    rating: 4.6,
    reviews: 0,
    img: ['#1A0005', '#380010'],
    accentHue: 5,
    stats: { age: 41, height: '185 cm', reach: '190 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'KSW Akademia', born: 'Stettin, Polen' },
    sponsors: [
      { name: 'Olimp Sport Nutrition' },
      { name: 'Pitbull West Coast' },
      { name: 'Stoprocent' }
    ],
  },
  // ── GROSSBRITANNIEN (Wales) ───────────────────────────────────────────────
  {
    id: 'mason-jones',
    name: 'Mason Jones',
    city: 'Cardiff',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Striker', 'Wrestler'],
    tags: ['PFL', 'Cage Warriors', 'Lightweight', 'The Dragon'],
    weightClass: 'Lightweight',
    record: '15-2-0',
    rating: 4.4,
    reviews: 0,
    img: ['#001218', '#002530'],
    accentHue: 205,
    stats: { age: 29, height: '175 cm', reach: '180 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'Capital City MMA Cardiff', born: 'Cardiff, Wales' },
    sponsors: [
      { name: 'Dragon Energy' },
      { name: 'Venum' },
      { name: 'Scramble' }
    ],
  },
  // ── NIEDERLANDE (Batch 3) ─────────────────────────────────────────────────
  {
    id: 'alistair-overeem',
    name: 'Alistair Overeem',
    city: 'Amsterdam',
    country: 'Netherlands',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'K-1', 'Legend', 'Heavyweight', 'The Reem'],
    weightClass: 'Heavyweight',
    record: '47-19-0',
    rating: 4.9,
    reviews: 0,
    img: ['#1A0C00', '#3D1C00'],
    accentHue: 28,
    stats: { age: 45, height: '193 cm', reach: '203 cm', stance: 'Southpaw', nationality: 'Niederländisch', gym: "Mike's Gym (ret.)", born: 'Hounslow, England' },
    sponsors: [
      { name: 'Olimp Nutrition' },
      { name: 'Venum' },
      { name: '32Red' }
    ],
  },
  // ── GROSSBRITANNIEN (Wales) ───────────────────────────────────────────────
  {
    id: 'jack-shore',
    name: 'Jack Shore',
    city: 'Cardiff',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Grappler', 'BJJ'],
    tags: ['UFC', 'Featherweight', 'Tank', 'Wales'],
    weightClass: 'Featherweight',
    record: '17-2-0',
    rating: 4.5,
    reviews: 0,
    img: ['#080820', '#12123D'],
    accentHue: 245,
    stats: { age: 29, height: '170 cm', reach: '172 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'Tillery Combat', born: 'Aberdare, Wales' },
    sponsors: [
      { name: 'Under Armour Wales' },
      { name: 'Monster Energy' },
      { name: 'Venum' }
    ],
  },
  // ── DÄNEMARK ──────────────────────────────────────────────────────────────
  {
    id: 'mads-burnell',
    name: 'Mads Burnell',
    city: 'Kopenhagen',
    country: 'Denmark',
    status: 'verified',
    styles: ['BJJ', 'Striker'],
    tags: ['PFL', 'Bellator', 'Featherweight', 'Arte Suave'],
    weightClass: 'Featherweight',
    record: '19-6-0',
    rating: 4.5,
    reviews: 0,
    img: ['#1A0008', '#380015'],
    accentHue: 355,
    stats: { age: 32, height: '175 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Dänisch', gym: 'Next Round Copenhagen', born: 'Kopenhagen, Dänemark' },
    sponsors: [
      { name: 'Venum' },
      { name: 'MyProtein Denmark' },
      { name: 'Reebok Nordic' }
    ],
  },
  // ── ISLAND ────────────────────────────────────────────────────────────────
  {
    id: 'gunnar-nelson',
    name: 'Gunnar Nelson',
    city: 'Reykjavik',
    country: 'Iceland',
    status: 'verified',
    styles: ['Grappler', 'BJJ'],
    tags: ['UFC', 'Welterweight', 'Gunni', 'Iceland'],
    weightClass: 'Welterweight',
    record: '19-5-1',
    rating: 4.7,
    reviews: 0,
    img: ['#001820', '#003040'],
    accentHue: 195,
    stats: { age: 37, height: '178 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Isländisch', gym: 'SBG Ireland', born: 'Reykjavik, Island' },
    sponsors: [
      { name: 'Icelandic Glacial' },
      { name: 'Venum' },
      { name: 'Reebok Iceland' }
    ],
  },
  // ── GROSSBRITANNIEN (Batch 3) ─────────────────────────────────────────────
  {
    id: 'arnold-allen',
    name: 'Arnold Allen',
    city: 'Ipswich',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'Top-5', 'Featherweight', 'Almighty'],
    weightClass: 'Featherweight',
    record: '20-3-0',
    rating: 4.7,
    reviews: 0,
    img: ['#0A1520', '#152D40'],
    accentHue: 210,
    stats: { age: 31, height: '170 cm', reach: '175 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'SBG Ipswich', born: 'Ipswich, England' },
    sponsors: [
      { name: 'Gymshark' },
      { name: 'MyProtein' },
      { name: 'Venum' }
    ],
  },
  // ── IRLAND (Batch 4) ──────────────────────────────────────────────────────
  {
    id: 'caolan-loughran',
    name: 'Caolán Loughran',
    city: 'Belfast',
    country: 'Ireland',
    status: 'verified',
    styles: ['Striker', 'Wrestler'],
    tags: ['UFC', 'Bantamweight', 'Belfast', 'Team Kaobon'],
    weightClass: 'Bantamweight',
    record: '11-1-0',
    rating: 4.4,
    reviews: 0,
    img: ['#001A0A', '#003A18'],
    accentHue: 145,
    stats: { age: 29, height: '168 cm', reach: '173 cm', stance: 'Orthodox', nationality: 'Irisch', gym: 'SBG Ireland', born: 'Belfast, Irland' },
    sponsors: [
      { name: 'Venum' },
      { name: 'MyProtein' },
      { name: 'Irish Combat Gear' }
    ],
  },
  // ── POLEN (Batch 4) ───────────────────────────────────────────────────────
  {
    id: 'karolina-kowalkiewicz',
    name: 'Karolina Kowalkiewicz',
    city: 'Łódź',
    country: 'Poland',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Strawweight', 'Veteran', 'Muay Thai'],
    weightClass: 'Strawweight',
    record: '16-8-0',
    rating: 4.3,
    reviews: 0,
    img: ['#200008', '#400015'],
    accentHue: 350,
    stats: { age: 40, height: '165 cm', reach: '163 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'KSW / MMA Factory', born: 'Łódź, Polen' },
    sponsors: [
      { name: 'Olimp Nutrition' },
      { name: 'Samsung Poland' },
      { name: 'Dietly' }
    ],
  },
  {
    id: 'marcin-tybura',
    name: 'Marcin Tybura',
    city: 'Warschau',
    country: 'Poland',
    status: 'verified',
    styles: ['BJJ', 'MMA'],
    tags: ['UFC', 'Top-10', 'Heavyweight', 'WCA Fight Team'],
    weightClass: 'Heavyweight',
    record: '26-9-0',
    rating: 4.4,
    reviews: 0,
    img: ['#1A0A0A', '#3A1515'],
    accentHue: 5,
    stats: { age: 39, height: '188 cm', reach: '193 cm', stance: 'Orthodox', nationality: 'Polnisch', gym: 'WCA Fight Team Warschau', born: 'Warschau, Polen' },
    sponsors: [
      { name: 'Olimp Nutrition' },
      { name: 'SuperBet Poland' }
    ],
  },

  // ── BATCH #5 ──────────────────────────────────────────────────────────────
  {
    id: 'ian-machado-garry',
    name: 'Ian Machado Garry',
    city: 'Dublin',
    country: 'Ireland',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Welterweight', 'Ireland', 'Reach: 188cm'],
    weightClass: 'Welterweight',
    record: '17-1-0',
    rating: 4.8,
    reviews: 0,
    img: ['#001A0A', '#003D1A'],
    accentHue: 145,
    stats: { age: 28, height: '191 cm', reach: '188 cm', stance: 'Orthodox', nationality: 'Irisch', gym: 'Kill Cliff FC', born: 'Dublin, Irland' },
    sponsors: [
      { name: 'Ichor' },
      { name: 'Venum' },
      { name: 'Monster Energy' },
      { name: 'MyProtein' },
    ],
  },
  {
    id: 'joel-alvarez',
    name: 'Joel Álvarez',
    city: 'Gijón',
    country: 'Spain',
    status: 'verified',
    styles: ['Grappler', 'BJJ'],
    tags: ['UFC', 'Lightweight', 'Spain', '17 Subs', 'Reach: 196cm'],
    weightClass: 'Lightweight',
    record: '22-3-0',
    rating: 4.7,
    reviews: 0,
    img: ['#1A0800', '#3D1600'],
    accentHue: 22,
    stats: { age: 33, height: '191 cm', reach: '196 cm', stance: 'Orthodox', nationality: 'Spanisch', gym: 'Bandog Fight Club', born: 'Gijón, Spanien' },
    sponsors: [
      { name: 'Everlast Spain' },
      { name: 'Prozis' },
      { name: 'Venum' },
    ],
  },
  {
    id: 'victoria-dudakova',
    name: 'Victoria Dudakova',
    city: 'Moskau',
    country: 'Russia',
    status: 'verified',
    styles: ['Wrestler', 'Grappler'],
    tags: ['PFL', 'Strawweight', 'Russia', 'Team Fedor'],
    weightClass: 'Strawweight',
    record: '10-2-0',
    rating: 4.4,
    reviews: 0,
    img: ['#1A000A', '#3A0015'],
    accentHue: 345,
    stats: { age: 27, height: '165 cm', reach: '170 cm', stance: 'Orthodox', nationality: 'Russisch', gym: 'Team Fedor', born: 'Russland' },
    sponsors: [
      { name: 'Gorilla Energy' },
      { name: 'Venum' },
      { name: 'BetCity' },
    ],
  },
  {
    id: 'costello-van-steenis',
    name: 'Costello van Steenis',
    city: 'Leiden',
    country: 'Netherlands',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['PFL', 'Middleweight', 'Champion', 'Netherlands'],
    weightClass: 'Middleweight',
    record: '18-3-0',
    rating: 4.6,
    reviews: 0,
    img: ['#1A0800', '#3D2000'],
    accentHue: 28,
    stats: { age: 33, height: '185 cm', reach: '190 cm', stance: 'Orthodox', nationality: 'Niederländisch', gym: 'Team Mousasi', born: 'Leiden, Niederlande' },
    sponsors: [
      { name: '32Red' },
      { name: 'Venum' },
      { name: 'Dutch Combat Gear' },
    ],
  },
  {
    id: 'modestas-bukauskas',
    name: 'Modestas Bukauskas',
    city: 'Vilnius',
    country: 'Lithuania',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    tags: ['UFC', 'Light Heavyweight', 'Lithuania', 'Cage Warriors'],
    weightClass: 'Light Heavyweight',
    record: '16-6-0',
    rating: 4.4,
    reviews: 0,
    img: ['#001508', '#002E12'],
    accentHue: 140,
    stats: { age: 32, height: '191 cm', reach: '198 cm', stance: 'Orthodox', nationality: 'Litauisch', gym: 'Gintas Combat', born: 'Vilnius, Litauen' },
    sponsors: [
      { name: 'Venum' },
      { name: 'MyProtein' },
      { name: 'Lithium Sports' },
    ],
  },
  {
    id: 'david-zawada',
    name: 'David Zawada',
    city: 'Düsseldorf',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'Grappler'],
    tags: ['PFL', 'KSW', 'Welterweight', 'Germany'],
    weightClass: 'Welterweight',
    record: '20-10-0',
    rating: 4.3,
    reviews: 0,
    img: ['#0A0A1A', '#181830'],
    accentHue: 230,
    stats: { age: 35, height: '183 cm', reach: '185 cm', stance: 'Orthodox', nationality: 'Deutsch', gym: 'UFD Gym Düsseldorf', born: 'Düsseldorf, Deutschland' },
    sponsors: [
      { name: 'Olimp Nutrition' },
      { name: 'Paffensport' },
      { name: 'Toyo Tires' },
    ],
  },
  {
    id: 'marc-diakiese',
    name: 'Marc Diakiese',
    city: 'London',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Striker', 'Wrestler'],
    tags: ['OKTAGON', 'UFC', 'Lightweight', 'United Kingdom'],
    weightClass: 'Lightweight',
    record: '18-8-0',
    rating: 4.4,
    reviews: 0,
    img: ['#0A001A', '#180030'],
    accentHue: 270,
    stats: { age: 33, height: '178 cm', reach: '188 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'American Top Team', born: 'London, Großbritannien' },
    sponsors: [
      { name: 'Venum' },
      { name: 'Gym King' },
      { name: 'Monster Energy' },
    ],
  },
  {
    id: 'losene-keita',
    name: 'Losene Keita',
    city: 'Brüssel',
    country: 'Belgium',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['OKTAGON', 'Champion', 'Belgium', 'Featherweight'],
    weightClass: 'Featherweight',
    record: '15-2-0',
    rating: 4.6,
    reviews: 0,
    img: ['#1A1400', '#3A2A00'],
    accentHue: 45,
    stats: { age: 28, height: '170 cm', reach: '175 cm', stance: 'Orthodox', nationality: 'Belgisch', gym: 'Team Keita', born: 'Brüssel, Belgien' },
    sponsors: [
      { name: 'Onyx' },
      { name: 'Venum' },
      { name: 'Bet-at-home' },
    ],
  },
  {
    id: 'brendan-loughnane',
    name: 'Brendan Loughnane',
    city: 'Manchester',
    country: 'United Kingdom',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['PFL', 'Champion', 'Featherweight', 'United Kingdom'],
    weightClass: 'Featherweight',
    record: '30-6-0',
    rating: 4.7,
    reviews: 0,
    img: ['#001833', '#00285A'],
    accentHue: 205,
    stats: { age: 36, height: '178 cm', reach: '183 cm', stance: 'Orthodox', nationality: 'Britisch', gym: 'Tiger Muay Thai', born: 'Manchester, England' },
    sponsors: [
      { name: 'Gymshark' },
      { name: 'Monster Energy' },
      { name: 'Venum' },
    ],
  },
  {
    id: 'bernardo-sopai',
    name: 'Bernardo Sopai',
    city: 'Tirana',
    country: 'Albania',
    status: 'verified',
    styles: ['Striker', 'Wrestler'],
    tags: ['UFC', 'Bantamweight', 'Albania', 'Allstars'],
    weightClass: 'Bantamweight',
    record: '12-4-0',
    rating: 4.3,
    reviews: 0,
    img: ['#1A0000', '#3D0000'],
    accentHue: 0,
    stats: { age: 25, height: '168 cm', reach: '170 cm', stance: 'Orthodox', nationality: 'Albanisch', gym: 'Allstars Training Center', born: 'Tirana, Albanien' },
    sponsors: [
      { name: 'Smilodox' },
      { name: 'Venum' },
      { name: 'Reebok Albania' },
    ],
  },
  {
    id: 'veronica-hardy',
    name: 'Veronica Hardy',
    city: 'Bratislava',
    country: 'Slovakia',
    status: 'verified',
    styles: ['Striker', 'BJJ'],
    tags: ['UFC', "Women's Flyweight", 'Slovakia', 'Dan Hardy'],
    weightClass: "Women's Flyweight",
    record: '10-5-1',
    rating: 4.2,
    reviews: 0,
    img: ['#001020', '#001830'],
    accentHue: 215,
    stats: { age: 30, height: '163 cm', reach: '163 cm', stance: 'Orthodox', nationality: 'Slowakisch', gym: 'Team Hardy', born: 'Bratislava, Slowakei' },
    sponsors: [
      { name: 'Venum' },
      { name: 'MyProtein' },
      { name: 'Everlast' },
    ],
  },
  {
    id: 'nicolas-dalby',
    name: 'Nicolas Dalby',
    city: 'Kopenhagen',
    country: 'Denmark',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Welterweight', 'Denmark', 'Veteran'],
    weightClass: 'Welterweight',
    record: '23-6-1',
    rating: 4.4,
    reviews: 0,
    img: ['#1A0005', '#380010'],
    accentHue: 355,
    stats: { age: 41, height: '180 cm', reach: '188 cm', stance: 'Orthodox', nationality: 'Dänisch', gym: 'Rumble Sports', born: 'Kopenhagen, Dänemark' },
    sponsors: [
      { name: 'Unibet Denmark' },
      { name: 'Venum' },
      { name: 'Reebok Nordic' },
    ],
  },
  {
    id: 'aleksandar-ilic',
    name: 'Aleksandar Ilić',
    city: 'Belgrad',
    country: 'Serbia',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['KSW', 'RCC', 'Middleweight', 'Serbia'],
    weightClass: 'Middleweight',
    record: '16-6-0',
    rating: 4.3,
    reviews: 0,
    img: ['#0A0014', '#14002A'],
    accentHue: 265,
    stats: { age: 37, height: '191 cm', reach: '196 cm', stance: 'Southpaw', nationality: 'Serbisch', gym: 'UFD Gym Düsseldorf', born: 'Belgrad, Serbien' },
    sponsors: [
      { name: 'Olimp' },
      { name: 'Bet-at-home' },
      { name: 'Paffensport' },
    ],
  },
  {
    id: 'pannie-kianzad',
    name: 'Pannie Kianzad',
    city: 'Stockholm',
    country: 'Sweden',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', "Women's Bantamweight", 'Sweden', 'Arte Suave'],
    weightClass: "Women's Bantamweight",
    record: '17-9-0',
    rating: 4.3,
    reviews: 0,
    img: ['#00101A', '#001A2A'],
    accentHue: 200,
    stats: { age: 34, height: '170 cm', reach: '168 cm', stance: 'Orthodox', nationality: 'Schwedisch', gym: 'Arte Suave', born: 'Stockholm, Schweden' },
    sponsors: [
      { name: 'Venum' },
      { name: 'Reebok Sweden' },
      { name: 'MyProtein' },
    ],
  },
  {
    id: 'joel-parrado',
    name: 'Joel Parrado',
    city: 'Madrid',
    country: 'Spain',
    status: 'self',
    styles: ['Striker', 'MMA'],
    tags: ['OKTAGON', 'Middleweight', 'Spain', 'Prospect'],
    weightClass: 'Middleweight',
    record: '9-1-0',
    rating: 4.2,
    reviews: 0,
    img: ['#1A0600', '#380E00'],
    accentHue: 18,
    stats: { age: 26, height: '183 cm', reach: '185 cm', stance: 'Orthodox', nationality: 'Spanisch', gym: 'Lokal Spanien', born: 'Spanien' },
    sponsors: [
      { name: 'Everlast' },
      { name: 'Local Spanish Brands' },
    ],
  },
];

const COPY = {
  de: {
    // Header
    navHome: 'Home',
    navSubmit: 'Kämpfer melden',
    navImprint: 'Impressum',
    // Hero
    heroTagline: 'MMA-Kämpfer aus ganz Europa entdecken',
    searchPlaceholder: 'Kämpfer, Gewichtsklasse oder Stadt suchen…',
    // Filter
    proOnly: 'Nur Profis',
    country: 'Land',
    allCountries: 'Alle Länder',
    city: 'Stadt',
    allCities: 'Alle Städte',
    // Status labels
    statusVerified: 'Profi',
    statusSelf: 'Semi-Profi',
    statusUnknown: 'Amateur',
    // Results
    resultsCount: (n) => `${n} ${n === 1 ? 'Kämpfer' : 'Kämpfer'} in Europa`,
    emptyTitle: 'Keine Ergebnisse',
    emptyBody: 'Versuche eine andere Stadt oder Gewichtsklasse.',
    reset: 'Filter zurücksetzen',
    featured: 'Featured',
    recordLabel: 'Rekord',
    // Footer
    footerBlurb: 'Die vollständigste MMA-Datenbank für Europa. Faktenbasiert, transparent, werbefrei.',
    footerSections: {
      product: ['Home', 'Kämpfer melden', 'Karte', 'Gewichtsklassen'],
      company: ['Über uns', 'Impressum', 'Datenschutz', 'Kontakt'],
    },
    footerSectionTitles: { product: 'Produkt', company: 'Rechtliches' },
    footerLinks: {
      'Home': 'FightFolio Homepage.html',
      'Kämpfer melden': '#',
      'Karte': '#',
      'Gewichtsklassen': '#',
      'Über uns': '#',
      'Impressum': '#',
      'Datenschutz': '#',
      'Kontakt': '#',
    },
    footerMadeWith: 'Gemacht mit 🥊 für AT & DE',
    newsletter: 'Neue Kämpfer per E-Mail',
    newsletterCta: 'Anmelden',
    copyright: '© 2026 FightFolio.at — Alle Rechte vorbehalten.',
  },
  en: {
    navHome: 'Home',
    navSubmit: 'Submit Fighter',
    navImprint: 'Imprint',
    heroTagline: 'Discover MMA fighters across Europe',
    searchPlaceholder: 'Search fighters, weight class, or city…',
    proOnly: 'Pros only',
    country: 'Country',
    allCountries: 'All countries',
    city: 'City',
    allCities: 'All cities',
    statusVerified: 'Pro Fighter',
    statusSelf: 'Semi-Pro',
    statusUnknown: 'Amateur',
    resultsCount: (n) => `${n} ${n === 1 ? 'fighter' : 'fighters'} across Europe`,
    emptyTitle: 'No results',
    emptyBody: 'Try a different city or weight class.',
    reset: 'Reset filters',
    featured: 'Featured',
    recordLabel: 'Record',
    footerBlurb: 'The most complete MMA database for Europe. Fact-based, transparent, ad-free.',
    footerSections: {
      product: ['Home', 'Submit Fighter', 'Map', 'Weight Classes'],
      company: ['About', 'Imprint', 'Privacy', 'Contact'],
    },
    footerSectionTitles: { product: 'Product', company: 'Legal' },
    footerLinks: {
      'Home': 'FightFolio Homepage.html',
      'Submit Fighter': '#',
      'Map': '#',
      'Weight Classes': '#',
      'About': '#',
      'Imprint': '#',
      'Privacy': '#',
      'Contact': '#',
    },
    footerMadeWith: 'Made with 🥊 for AT & DE',
    newsletter: 'New fighters by email',
    newsletterCta: 'Subscribe',
    copyright: '© 2026 FightFolio.at — All rights reserved.',
  },
};

const FIGHT_STYLES = ['Striker', 'Kickboxer', 'Wrestler', 'BJJ', 'Grappler', 'MMA'];

const CITIES = [
  // Austria
  { id: 'Wien',       label: 'Wien 🇦🇹',       country: 'Austria' },
  { id: 'Graz',       label: 'Graz 🇦🇹',       country: 'Austria' },
  { id: 'Salzburg',   label: 'Salzburg 🇦🇹',   country: 'Austria' },
  { id: 'Innsbruck',  label: 'Innsbruck 🇦🇹',  country: 'Austria' },
  { id: 'Linz',       label: 'Linz 🇦🇹',       country: 'Austria' },
  // Germany
  { id: 'Frankfurt',  label: 'Frankfurt 🇩🇪',  country: 'Germany' },
  { id: 'München',    label: 'München 🇩🇪',    country: 'Germany' },
  { id: 'Hamburg',    label: 'Hamburg 🇩🇪',    country: 'Germany' },
  { id: 'Düsseldorf', label: 'Düsseldorf 🇩🇪', country: 'Germany' },
  { id: 'Köln',       label: 'Köln 🇩🇪',       country: 'Germany' },
  { id: 'Leipzig',    label: 'Leipzig 🇩🇪',    country: 'Germany' },
  { id: 'Stuttgart',  label: 'Stuttgart 🇩🇪',  country: 'Germany' },
  { id: 'Berlin',     label: 'Berlin 🇩🇪',     country: 'Germany' },
  // Spain
  { id: 'Alicante',   label: 'Alicante 🇪🇸',   country: 'Spain' },
  // United Kingdom
  { id: 'Liverpool',  label: 'Liverpool 🇬🇧',  country: 'United Kingdom' },
  { id: 'Birmingham', label: 'Birmingham 🇬🇧', country: 'United Kingdom' },
  // France
  { id: 'Paris',      label: 'Paris 🇫🇷',      country: 'France' },
  { id: 'Nizza',      label: 'Nizza 🇫🇷',      country: 'France' },
  // Poland
  { id: 'Warschau',   label: 'Warschau 🇵🇱',   country: 'Poland' },
  { id: 'Poznań',     label: 'Poznań 🇵🇱',     country: 'Poland' },
  // Italy
  { id: 'Rom',        label: 'Rom 🇮🇹',        country: 'Italy' },
  // Netherlands
  { id: 'Leiden',     label: 'Leiden 🇳🇱',     country: 'Netherlands' },
  { id: 'Breda',      label: 'Breda 🇳🇱',      country: 'Netherlands' },
  // Sweden
  { id: 'Stockholm',  label: 'Stockholm 🇸🇪',  country: 'Sweden' },
  // United Kingdom (Batch 3)
  { id: 'Manchester', label: 'Manchester 🇬🇧', country: 'United Kingdom' },
  { id: 'Cardiff',    label: 'Cardiff 🇬🇧',    country: 'United Kingdom' },
  { id: 'Ipswich',    label: 'Ipswich 🇬🇧',    country: 'United Kingdom' },
  // Ireland
  { id: 'Belfast',    label: 'Belfast 🇮🇪',    country: 'Ireland' },
  // Portugal
  { id: 'Lissabon',   label: 'Lissabon 🇵🇹',   country: 'Portugal' },
  // Poland (Batch 3)
  { id: 'Stettin',    label: 'Stettin 🇵🇱',    country: 'Poland' },
  { id: 'Łódź',      label: 'Łódź 🇵🇱',       country: 'Poland' },
  // Netherlands (Batch 3)
  { id: 'Amsterdam',  label: 'Amsterdam 🇳🇱',  country: 'Netherlands' },
  // Denmark
  { id: 'Kopenhagen', label: 'Kopenhagen 🇩🇰', country: 'Denmark' },
  // Iceland
  { id: 'Reykjavik',  label: 'Reykjavik 🇮🇸',  country: 'Iceland' },
  // Ireland (Batch 5)
  { id: 'Dublin',     label: 'Dublin 🇮🇪',      country: 'Ireland' },
  // Spain (Batch 5)
  { id: 'Gijón',     label: 'Gijón 🇪🇸',       country: 'Spain' },
  { id: 'Madrid',    label: 'Madrid 🇪🇸',      country: 'Spain' },
  // Russia (Batch 5)
  { id: 'Moskau',    label: 'Moskau 🇷🇺',      country: 'Russia' },
  // Lithuania (Batch 5)
  { id: 'Vilnius',   label: 'Vilnius 🇱🇹',     country: 'Lithuania' },
  // Belgium (Batch 5)
  { id: 'Brüssel',   label: 'Brüssel 🇧🇪',     country: 'Belgium' },
  // United Kingdom (Batch 5)
  { id: 'London',    label: 'London 🇬🇧',      country: 'United Kingdom' },
  // Albania (Batch 5)
  { id: 'Tirana',    label: 'Tirana 🇦🇱',      country: 'Albania' },
  // Slovakia (Batch 5)
  { id: 'Bratislava', label: 'Bratislava 🇸🇰', country: 'Slovakia' },
  // Serbia (Batch 5)
  { id: 'Belgrad',   label: 'Belgrad 🇷🇸',     country: 'Serbia' },
];

const COUNTRIES = [
  { id: 'Austria',        label: '🇦🇹 Austria' },
  { id: 'Germany',        label: '🇩🇪 Germany' },
  { id: 'Spain',          label: '🇪🇸 Spain' },
  { id: 'United Kingdom', label: '🇬🇧 United Kingdom' },
  { id: 'France',         label: '🇫🇷 France' },
  { id: 'Poland',         label: '🇵🇱 Poland' },
  { id: 'Italy',          label: '🇮🇹 Italy' },
  { id: 'Netherlands',    label: '🇳🇱 Netherlands' },
  { id: 'Croatia',        label: '🇭🇷 Croatia' },
  { id: 'Sweden',         label: '🇸🇪 Sweden' },
  { id: 'Ireland',        label: '🇮🇪 Ireland' },
  { id: 'Portugal',       label: '🇵🇹 Portugal' },
  { id: 'Denmark',        label: '🇩🇰 Denmark' },
  { id: 'Iceland',        label: '🇮🇸 Iceland' },
  { id: 'Belgium',        label: '🇧🇪 Belgium' },
  { id: 'Serbia',         label: '🇷🇸 Serbia' },
  { id: 'Lithuania',      label: '🇱🇹 Lithuania' },
  { id: 'Albania',        label: '🇦🇱 Albania' },
  { id: 'Slovakia',       label: '🇸🇰 Slovakia' },
  { id: 'Russia',         label: '🇷🇺 Russia' },
];

Object.assign(window, { FIGHTERS, COPY, FIGHT_STYLES, CITIES, COUNTRIES });
