// FightFolio — MMA Fighters data + copy translations

const FIGHTERS = [
  // ── ÖSTERREICH ────────────────────────────────────────────────────────────
  {
    id: 'aleksandar-rakic',
    name: 'Aleksandar Rakić',
    city: 'Wien',
    country: 'Austria',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Top-10', 'LHW', 'Österreich'],
    weightClass: 'Light Heavyweight',
    record: '14-4-0',
    rating: 4.9,
    reviews: 0,
    featured: true,
    img: ['#1A0A00', '#3D1F00'],
    accentHue: 42,
    sponsors: [
      { name: 'Venum' },
      { name: 'Monster Energy' },
      { name: 'Phantom Athletics' },
      { name: 'A1 Telekom Austria' }
    ],
  },
  {
    id: 'ismail-naurdiev',
    name: 'Ismail Naurdiev',
    city: 'Wien',
    country: 'Austria',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    tags: ['UFC', 'Welterweight', 'Österreich', 'KO-Artist'],
    weightClass: 'Welterweight',
    record: '16-4-0',
    rating: 4.7,
    reviews: 0,
    img: ['#001A3D', '#003580'],
    accentHue: 210,
    sponsors: [
      { name: 'Gymking' },
      { name: 'Bet-at-home' },
      { name: 'T-Mobile Austria' }
    ],
  },
  {
    id: 'bogdan-grad',
    name: 'Bogdan Grad',
    city: 'Graz',
    country: 'Austria',
    status: 'verified',
    styles: ['Wrestler', 'MMA'],
    tags: ['OKTAGON', 'Heavyweight', 'Steiermark'],
    weightClass: 'Heavyweight',
    record: '13-5-0',
    rating: 4.5,
    reviews: 0,
    img: ['#0A1A00', '#1A3D00'],
    accentHue: 105,
    sponsors: [
      { name: 'Ettl Bros' },
      { name: 'Raiffeisen Sport' },
      { name: 'Nutri-Direct' }
    ],
  },
  {
    id: 'rodrigo-nascimento',
    name: 'Rodrigo Nascimento',
    city: 'Wien',
    country: 'Austria',
    status: 'verified',
    styles: ['Wrestler', 'BJJ'],
    tags: ['UFC', 'Heavyweight', 'Wien', 'Brasilien'],
    weightClass: 'Heavyweight',
    record: '10-2-0',
    rating: 4.6,
    reviews: 0,
    img: ['#1A001A', '#3D003D'],
    accentHue: 300,
    sponsors: [
      { name: 'Venum' },
      { name: 'MHP' },
      { name: 'Cybex' }
    ],
  },
  {
    id: 'florian-aberger',
    name: 'Florian Aberger',
    city: 'Graz',
    country: 'Austria',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['REGIONAL', 'Middleweight', 'Steiermark', 'IMMAF'],
    weightClass: 'Middleweight',
    record: '9-1-0',
    rating: 4.4,
    reviews: 0,
    img: ['#001A00', '#003D00'],
    accentHue: 90,
    sponsors: [
      { name: 'Steiermärkische Sparkasse' },
      { name: 'Hervis Sports' },
      { name: 'Calibian Management' }
    ],
  },
  {
    id: 'wilhelm-ott',
    name: 'Wilhelm Ott',
    city: 'Linz',
    country: 'Austria',
    status: 'self',
    styles: ['Striker', 'MMA'],
    tags: ['REGIONAL', 'Middleweight', 'Linz', 'BKFC'],
    weightClass: 'Middleweight',
    record: '19-19-1',
    rating: 4.0,
    reviews: 0,
    img: ['#0A0A1A', '#1A1A3D'],
    accentHue: 220,
    sponsors: [
      { name: 'Ott Security' },
      { name: 'Empire Sports' }
    ],
  },
  // ── DEUTSCHLAND ───────────────────────────────────────────────────────────
  {
    id: 'christian-eckerlin',
    name: 'Christian Eckerlin',
    city: 'Frankfurt',
    country: 'Germany',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    tags: ['GLORY', 'ONE FC', 'MMA', 'Frankfurt'],
    weightClass: 'Middleweight',
    record: '28-15-0',
    rating: 4.6,
    reviews: 0,
    img: ['#1A0000', '#3D0000'],
    accentHue: 0,
    sponsors: [
      { name: 'Eckerlin Logistics' },
      { name: 'Mainova' },
      { name: 'König Pilsener' }
    ],
  },
  {
    id: 'kerim-engizek',
    name: 'Kerim Engizek',
    city: 'Düsseldorf',
    country: 'Germany',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    tags: ['GLORY', 'Lightweight', 'Deutschland', 'KO-Artist'],
    weightClass: 'Lightweight',
    record: '45-8-0',
    rating: 4.8,
    reviews: 0,
    img: ['#001A1A', '#003D3D'],
    accentHue: 180,
    sponsors: [
      { name: 'Onyx' },
      { name: 'Bose Germany' },
      { name: 'Snipes' }
    ],
  },
  {
    id: 'nick-hein',
    name: 'Nick Hein',
    city: 'Hamburg',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'BJJ'],
    tags: ['UFC', 'Lightweight', 'Hamburg', 'Judo'],
    weightClass: 'Lightweight',
    record: '13-4-0',
    rating: 4.4,
    reviews: 0,
    img: ['#0A0A1A', '#15153D'],
    accentHue: 240,
    sponsors: [
      { name: 'Sponsoo' },
      { name: 'Under Armour Germany' },
      { name: 'Sky Sport' }
    ],
  },
  {
    id: 'dennis-siver',
    name: 'Dennis Siver',
    city: 'München',
    country: 'Germany',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    tags: ['UFC', 'Featherweight', 'München', 'Veteran'],
    weightClass: 'Featherweight',
    record: '24-13-0',
    rating: 4.3,
    reviews: 0,
    img: ['#1A0A1A', '#3D1A3D'],
    accentHue: 280,
    sponsors: [
      { name: 'Kwon' },
      { name: 'FitX' }
    ],
  },
  {
    id: 'daniel-weichel',
    name: 'Daniel Weichel',
    city: 'Frankfurt',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['Bellator', 'OKTAGON', 'Featherweight', 'M-1 Global'],
    weightClass: 'Featherweight',
    record: '45-14-0',
    rating: 4.5,
    reviews: 0,
    img: ['#1A0A00', '#3D1800'],
    accentHue: 15,
    sponsors: [
      { name: 'Spirit MMA' },
      { name: 'Matrix Fitness' },
      { name: 'Lonsdale Germany' }
    ],
  },
  {
    id: 'joilton-lutterbach',
    name: 'Joilton Lutterbach',
    city: 'Köln',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    tags: ['UFC', 'OKTAGON', 'Middleweight', 'Köln'],
    weightClass: 'Middleweight',
    record: '41-11-0',
    rating: 4.3,
    reviews: 0,
    img: ['#001A18', '#003D33'],
    accentHue: 170,
    sponsors: [
      { name: 'Paffensport' },
      { name: 'Zec+ Nutrition' },
      { name: 'MyProtein' }
    ],
  },
  {
    id: 'frederic-vosgrone',
    name: 'Frédéric Vosgröne',
    city: 'Düsseldorf',
    country: 'Germany',
    status: 'verified',
    styles: ['BJJ', 'Grappler'],
    tags: ['OKTAGON', 'Light Heavyweight', 'BJJ World Champ', 'ADCC'],
    weightClass: 'Light Heavyweight',
    record: '5-0-0',
    rating: 4.6,
    reviews: 0,
    img: ['#0D001A', '#20003D'],
    accentHue: 270,
    sponsors: [
      { name: 'UFD Gym' },
      { name: 'Olimp Sport Nutrition' }
    ],
  },
  {
    id: 'sascha-sharma',
    name: 'Sascha Sharma',
    city: 'Stuttgart',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'BJJ'],
    tags: ['TUF', 'Lightweight', 'Pforzheim', 'Kong\'s Gym'],
    weightClass: 'Lightweight',
    record: '17-5-0',
    rating: 4.1,
    reviews: 0,
    img: ['#1A1200', '#3D2A00'],
    accentHue: 35,
    sponsors: [
      { name: 'Stallion Gym' },
      { name: 'Vayumedia' }
    ],
  },
  {
    id: 'sebastian-holzmann',
    name: 'Sebastian Holzmann',
    city: 'Leipzig',
    country: 'Germany',
    status: 'self',
    styles: ['Striker', 'MMA'],
    tags: ['REGIONAL', 'Lightweight', 'Halle', 'Sachsen-Anhalt'],
    weightClass: 'Lightweight',
    record: '6-2-0',
    rating: 3.9,
    reviews: 0,
    img: ['#001218', '#002030'],
    accentHue: 200,
    sponsors: [
      { name: 'Leipzig Lions' },
      { name: 'Power & Fitness Shop' }
    ],
  },
];

const COPY = {
  de: {
    // Header
    navHome: 'Home',
    navSubmit: 'Kämpfer melden',
    navImprint: 'Impressum',
    // Hero
    heroTagline: 'MMA-Kämpfer aus Österreich und Deutschland entdecken',
    searchPlaceholder: 'Kämpfer, Gewichtsklasse oder Stadt suchen…',
    // Filter
    proOnly: 'Nur Profis',
    city: 'Stadt',
    allCities: 'Alle Städte',
    // Status labels
    statusVerified: 'Profi',
    statusSelf: 'Semi-Profi',
    statusUnknown: 'Amateur',
    // Results
    resultsCount: (n) => `${n} ${n === 1 ? 'Kämpfer' : 'Kämpfer'} in AT & DE`,
    emptyTitle: 'Keine Ergebnisse',
    emptyBody: 'Versuche eine andere Stadt oder Gewichtsklasse.',
    reset: 'Filter zurücksetzen',
    featured: 'Featured',
    recordLabel: 'Rekord',
    // Footer
    footerBlurb: 'Die vollständigste MMA-Datenbank für Österreich und Deutschland. Faktenbasiert, transparent, werbefrei.',
    footerSections: {
      product: ['Home', 'Kämpfer melden', 'Karte', 'Gewichtsklassen'],
      company: ['Über uns', 'Impressum', 'Datenschutz', 'Kontakt'],
    },
    footerSectionTitles: { product: 'Produkt', company: 'Rechtliches' },
    footerLinks: {
      'Home': 'FightFolio Homepage.html',
      'Kämpfer melden': '#',
      'Karte': '#',
      'Gewichtsklassen': '#',
      'Über uns': '#',
      'Impressum': '#',
      'Datenschutz': '#',
      'Kontakt': '#',
    },
    footerMadeWith: 'Gemacht mit 🥊 für AT & DE',
    newsletter: 'Neue Kämpfer per E-Mail',
    newsletterCta: 'Anmelden',
    copyright: '© 2026 FightFolio.at — Alle Rechte vorbehalten.',
  },
  en: {
    navHome: 'Home',
    navSubmit: 'Submit Fighter',
    navImprint: 'Imprint',
    heroTagline: 'Discover MMA fighters from Austria and Germany',
    searchPlaceholder: 'Search fighters, weight class, or city…',
    proOnly: 'Pros only',
    city: 'City',
    allCities: 'All cities',
    statusVerified: 'Pro Fighter',
    statusSelf: 'Semi-Pro',
    statusUnknown: 'Amateur',
    resultsCount: (n) => `${n} ${n === 1 ? 'fighter' : 'fighters'} in AT & DE`,
    emptyTitle: 'No results',
    emptyBody: 'Try a different city or weight class.',
    reset: 'Reset filters',
    featured: 'Featured',
    recordLabel: 'Record',
    footerBlurb: 'The most complete MMA database for Austria and Germany. Fact-based, transparent, ad-free.',
    footerSections: {
      product: ['Home', 'Submit Fighter', 'Map', 'Weight Classes'],
      company: ['About', 'Imprint', 'Privacy', 'Contact'],
    },
    footerSectionTitles: { product: 'Product', company: 'Legal' },
    footerLinks: {
      'Home': 'FightFolio Homepage.html',
      'Submit Fighter': '#',
      'Map': '#',
      'Weight Classes': '#',
      'About': '#',
      'Imprint': '#',
      'Privacy': '#',
      'Contact': '#',
    },
    footerMadeWith: 'Made with 🥊 for AT & DE',
    newsletter: 'New fighters by email',
    newsletterCta: 'Subscribe',
    copyright: '© 2026 FightFolio.at — All rights reserved.',
  },
};

const FIGHT_STYLES = ['Striker', 'Kickboxer', 'Wrestler', 'BJJ', 'Grappler', 'MMA'];

const CITIES = [
  // Austria
  { id: 'Wien', label: 'Wien 🇦🇹' },
  { id: 'Graz', label: 'Graz 🇦🇹' },
  { id: 'Salzburg', label: 'Salzburg 🇦🇹' },
  { id: 'Innsbruck', label: 'Innsbruck 🇦🇹' },
  { id: 'Linz', label: 'Linz 🇦🇹' },
  // Germany
  { id: 'Frankfurt', label: 'Frankfurt 🇩🇪' },
  { id: 'München', label: 'München 🇩🇪' },
  { id: 'Hamburg', label: 'Hamburg 🇩🇪' },
  { id: 'Düsseldorf', label: 'Düsseldorf 🇩🇪' },
  { id: 'Köln', label: 'Köln 🇩🇪' },
  { id: 'Leipzig', label: 'Leipzig 🇩🇪' },
  { id: 'Stuttgart', label: 'Stuttgart 🇩🇪' },
  { id: 'Berlin', label: 'Berlin 🇩🇪' },
];

Object.assign(window, { FIGHTERS, COPY, FIGHT_STYLES, CITIES });
