// ─────────────────────────────────────────────────────────────────────────────
// FightFolio — Fighter profiles
// ─────────────────────────────────────────────────────────────────────────────

const VENUES = {

  // ── ALEKSANDAR RAKIĆ ──────────────────────────────────────────────────────
  'aleksandar-rakic': {
    id: 'aleksandar-rakic',
    name: 'Aleksandar Rakić',
    tagline_de: 'Österreichs größter UFC-Star — #7 Light Heavyweight der Welt',
    tagline_en: "Austria's biggest UFC star — #7 Light Heavyweight in the world",
    city: 'Wien',
    country: 'Austria',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    weightClass: 'Light Heavyweight',
    record: '14-4-0',
    rating: 4.9,
    reviews: 0,
    tags: ['UFC', 'Top-10', 'LHW', 'Österreich', 'SBG Wien'],
    gallery: [
      { hue: 42, a: '#1A0A00', b: '#3D1F00' },
      { hue: 30, a: '#2D1500', b: '#1A0A00' },
      { hue: 55, a: '#1F1A00', b: '#3A2E00' },
      { hue: 20, a: '#3D0000', b: '#1A0000' },
      { hue: 60, a: '#1A1A00', b: '#2D2D00' },
    ],
    nextFight: {
      opponent_de: 'TBD',
      opponent_en: 'TBD',
      date_de: 'Q3 2026',
      date_en: 'Q3 2026',
      event: 'UFC Fight Night',
      location: 'TBD',
    },
    fightHistory: [
      { opponent: 'Jan Błachowicz',    result: 'W', method: 'KO/TKO', event: 'UFC 288',          date: '2023-05-13', round: 3, time: '2:30' },
      { opponent: 'Magomed Ankalaev',  result: 'L', method: 'KO/TKO', event: 'UFC 282',          date: '2022-12-10', round: 2, time: '1:22' },
      { opponent: 'Thiago Santos',     result: 'W', method: 'KO/TKO', event: 'UFC Fight Night',  date: '2022-03-12', round: 1, time: '2:30' },
      { opponent: 'Volkan Oezdemir',   result: 'W', method: 'Decision', event: 'UFC Fight Night', date: '2021-06-26', round: 3, time: '5:00' },
      { opponent: 'Anthony Smith',     result: 'W', method: 'KO/TKO', event: 'UFC Fight Night',  date: '2021-02-27', round: 3, time: '4:00' },
      { opponent: 'Nikita Krylov',     result: 'W', method: 'Decision', event: 'UFC Fight Night', date: '2020-09-26', round: 3, time: '5:00' },
      { opponent: 'Devin Clark',       result: 'W', method: 'Decision', event: 'UFC Fight Night', date: '2020-03-07', round: 3, time: '5:00' },
      { opponent: 'Ed Herman',         result: 'W', method: 'KO/TKO', event: 'UFC on ESPN',      date: '2019-10-05', round: 1, time: '2:45' },
    ],
    stats: {
      age: 33,
      height: '196 cm',
      reach: '199 cm',
      stance: 'Orthodox',
      nationality: 'Österreichisch',
      gym: 'SBG Wien',
      born: 'Belgrad, Serbien',
    },
    reviews_list: [],
    career_log: [
      { date: '2023-05-13', event_de: 'UFC 288 — Sieg über Jan Błachowicz (KO Runde 3)', event_en: 'UFC 288 — Win over Jan Błachowicz (KO Round 3)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2022-12-10', event_de: 'UFC 282 — Niederlage gegen Magomed Ankalaev (KO)', event_en: 'UFC 282 — Loss to Magomed Ankalaev (KO)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2021-06-26', event_de: 'UFC Fight Night — Sieg über Volkan Oezdemir (Decision)', event_en: 'UFC Fight Night — Win over Volkan Oezdemir (Decision)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2018-01-01', event_de: 'Wechsel zu UFC — Profi-Debüt in der Premier-Liga', event_en: 'Signed with UFC — Pro debut in the premier league', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'ismail-naurdiev',  name: 'Ismail Naurdiev',    city: 'Wien',      country: 'Austria', status: 'verified', weightClass: 'Welterweight',      record: '16-4', hue: 210 },
      { id: 'bogdan-grad',      name: 'Bogdan Grad',        city: 'Graz',      country: 'Austria', status: 'verified', weightClass: 'Heavyweight',       record: '13-5', hue: 105 },
      { id: 'christian-eckerlin', name: 'Christian Eckerlin', city: 'Frankfurt', country: 'Germany', status: 'verified', weightClass: 'Middleweight', record: '28-15', hue: 0 },
    ],
  },

  // ── ISMAIL NAURDIEV ────────────────────────────────────────────────────────
  'ismail-naurdiev': {
    id: 'ismail-naurdiev',
    name: 'Ismail Naurdiev',
    tagline_de: 'Der Österreichische Wonderboy — Weltklasse-Striker im Weltergewicht',
    tagline_en: 'The Austrian Wonderboy — World-class striker at Welterweight',
    city: 'Wien',
    country: 'Austria',
    status: 'verified',
    styles: ['Striker', 'Kickboxer'],
    weightClass: 'Welterweight',
    record: '16-4-0',
    rating: 4.7,
    reviews: 0,
    tags: ['UFC', 'Welterweight', 'KO-Artist', 'Österreich'],
    gallery: [
      { hue: 210, a: '#001A3D', b: '#003580' },
      { hue: 220, a: '#00122D', b: '#001F50' },
      { hue: 195, a: '#001A2D', b: '#003050' },
      { hue: 230, a: '#0A0A2D', b: '#151550' },
      { hue: 200, a: '#001520', b: '#002840' },
    ],
    nextFight: {
      opponent_de: 'TBD',
      opponent_en: 'TBD',
      date_de: 'Q4 2026',
      date_en: 'Q4 2026',
      event: 'UFC Fight Night',
      location: 'TBD',
    },
    fightHistory: [
      { opponent: 'Niko Price',       result: 'W', method: 'KO/TKO',  event: 'UFC Fight Night', date: '2023-09-23', round: 2, time: '3:12' },
      { opponent: 'Jeremiah Wells',   result: 'L', method: 'KO/TKO',  event: 'UFC 284',         date: '2023-02-11', round: 1, time: '1:55' },
      { opponent: 'Warlley Alves',    result: 'W', method: 'KO/TKO',  event: 'UFC Fight Night', date: '2022-10-22', round: 1, time: '3:45' },
      { opponent: 'Matt Semelsberger',result: 'W', method: 'KO/TKO',  event: 'UFC 269',         date: '2021-12-11', round: 2, time: '2:03' },
      { opponent: 'Claudio Silva',    result: 'L', method: 'Decision', event: 'UFC Fight Night', date: '2021-05-22', round: 3, time: '5:00' },
    ],
    stats: {
      age: 29,
      height: '185 cm',
      reach: '191 cm',
      stance: 'Southpaw',
      nationality: 'Österreichisch',
      gym: 'Team Naurdiev Wien',
      born: 'Wien, Österreich',
    },
    reviews_list: [],
    career_log: [
      { date: '2023-09-23', event_de: 'UFC Fight Night — Sieg über Niko Price (KO Runde 2)', event_en: 'UFC Fight Night — Win over Niko Price (KO Round 2)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2021-12-11', event_de: 'UFC 269 — Sieg über Matt Semelsberger (KO)', event_en: 'UFC 269 — Win over Matt Semelsberger (KO)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'aleksandar-rakic', name: 'Aleksandar Rakić',   city: 'Wien',      country: 'Austria', status: 'verified', weightClass: 'Light Heavyweight', record: '14-4', hue: 42 },
      { id: 'kerim-engizek',   name: 'Kerim Engizek',      city: 'Düsseldorf', country: 'Germany', status: 'verified', weightClass: 'Lightweight',       record: '45-8', hue: 180 },
    ],
  },

  // ── CHRISTIAN ECKERLIN ────────────────────────────────────────────────────
  'christian-eckerlin': {
    id: 'christian-eckerlin',
    name: 'Christian Eckerlin',
    tagline_de: 'Deutschlands härtester Kickboxer — GLORY & ONE FC Veteran',
    tagline_en: "Germany's hardest kickboxer — GLORY & ONE FC veteran",
    city: 'Frankfurt',
    country: 'Germany',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    weightClass: 'Middleweight',
    record: '28-15-0',
    rating: 4.6,
    reviews: 0,
    tags: ['GLORY', 'ONE FC', 'MMA', 'Frankfurt', 'Deutschland'],
    gallery: [
      { hue: 0,   a: '#1A0000', b: '#3D0000' },
      { hue: 10,  a: '#2D0000', b: '#1A0000' },
      { hue: 350, a: '#3D0000', b: '#200000' },
      { hue: 5,   a: '#1A0500', b: '#350A00' },
      { hue: 15,  a: '#2D0500', b: '#1A0300' },
    ],
    nextFight: {
      opponent_de: 'TBD',
      opponent_en: 'TBD',
      date_de: 'Q2 2026',
      date_en: 'Q2 2026',
      event: 'GLORY Kickboxing',
      location: 'Frankfurt',
    },
    fightHistory: [
      { opponent: 'Donegi Abena',     result: 'L', method: 'Decision', event: 'GLORY 88',        date: '2023-11-18', round: 5, time: '3:00' },
      { opponent: 'Gago Drago',       result: 'W', method: 'KO/TKO',  event: 'GLORY 83',        date: '2023-04-01', round: 2, time: '2:55' },
      { opponent: 'Yoann Kongolo',    result: 'W', method: 'Decision', event: 'GLORY 79',        date: '2022-11-19', round: 5, time: '3:00' },
      { opponent: 'Imad Hadar',       result: 'W', method: 'KO/TKO',  event: 'GLORY 77',        date: '2022-09-17', round: 1, time: '1:30' },
      { opponent: 'Jahfarr Wilnis',   result: 'W', method: 'Decision', event: 'GLORY Fight Night', date: '2022-06-11', round: 3, time: '3:00' },
    ],
    stats: {
      age: 35,
      height: '188 cm',
      reach: '194 cm',
      stance: 'Orthodox',
      nationality: 'Deutsch',
      gym: 'Team Eckerlin Frankfurt',
      born: 'Frankfurt am Main',
    },
    reviews_list: [],
    career_log: [
      { date: '2023-04-01', event_de: 'GLORY 83 — Sieg über Gago Drago (KO)', event_en: 'GLORY 83 — Win over Gago Drago (KO)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2022-09-17', event_de: 'GLORY 77 — Sieg über Imad Hadar (KO in Runde 1)', event_en: 'GLORY 77 — Win over Imad Hadar (KO Round 1)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'kerim-engizek',   name: 'Kerim Engizek', city: 'Düsseldorf', country: 'Germany', status: 'verified', weightClass: 'Lightweight', record: '45-8', hue: 180 },
      { id: 'dennis-siver',    name: 'Dennis Siver',   city: 'München',    country: 'Germany', status: 'verified', weightClass: 'Featherweight', record: '24-13', hue: 280 },
    ],
  },

  // ── KERIM ENGIZEK ─────────────────────────────────────────────────────────
  'kerim-engizek': {
    id: 'kerim-engizek',
    name: 'Kerim Engizek',
    tagline_de: 'GLORY Lightweight Weltmeister — 45 Siege, davon 30 per KO',
    tagline_en: 'GLORY Lightweight World Champion — 45 wins, 30 by KO',
    city: 'Düsseldorf',
    country: 'Germany',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    weightClass: 'Lightweight',
    record: '45-8-0',
    rating: 4.8,
    reviews: 0,
    tags: ['GLORY', 'Weltmeister', 'Lightweight', 'Deutschland', 'KO-Artist'],
    gallery: [
      { hue: 180, a: '#001A1A', b: '#003D3D' },
      { hue: 190, a: '#001515', b: '#003030' },
      { hue: 170, a: '#001A10', b: '#003D25' },
      { hue: 185, a: '#001520', b: '#003040' },
      { hue: 175, a: '#001A15', b: '#003D2D' },
    ],
    nextFight: {
      opponent_de: 'TBD — WM-Titelverteidigung',
      opponent_en: 'TBD — World title defence',
      date_de: 'Q2 2026',
      date_en: 'Q2 2026',
      event: 'GLORY Kickboxing',
      location: 'Düsseldorf',
    },
    fightHistory: [
      { opponent: 'Tyjani Beztati',   result: 'W', method: 'Decision', event: 'GLORY 90 SuperFight', date: '2024-03-09', round: 5, time: '3:00' },
      { opponent: 'Petch PK Saenchai',result: 'W', method: 'KO/TKO',  event: 'GLORY 87',        date: '2023-09-16', round: 3, time: '2:11' },
      { opponent: 'Stoyan Koprivlenski', result: 'W', method: 'KO/TKO', event: 'GLORY 84',     date: '2023-06-10', round: 1, time: '0:58' },
      { opponent: 'Anvar Boynazarov', result: 'W', method: 'KO/TKO',  event: 'GLORY 80',        date: '2022-12-10', round: 2, time: '1:22' },
      { opponent: 'Tyjani Beztati',   result: 'L', method: 'Decision', event: 'GLORY 75',       date: '2022-06-04', round: 5, time: '3:00' },
    ],
    stats: {
      age: 31,
      height: '176 cm',
      reach: '180 cm',
      stance: 'Orthodox',
      nationality: 'Deutsch-Türkisch',
      gym: 'Team Engizek Düsseldorf',
      born: 'Düsseldorf',
    },
    reviews_list: [],
    career_log: [
      { date: '2024-03-09', event_de: 'GLORY 90 — WM-Titelverteidigung gegen Tyjani Beztati', event_en: 'GLORY 90 — World title defence vs Tyjani Beztati', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2023-09-16', event_de: 'GLORY 87 — Sieg über Petch PK Saenchai (KO)', event_en: 'GLORY 87 — Win over Petch PK Saenchai (KO)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'christian-eckerlin', name: 'Christian Eckerlin', city: 'Frankfurt', country: 'Germany', status: 'verified', weightClass: 'Middleweight', record: '28-15', hue: 0 },
      { id: 'nick-hein',         name: 'Nick Hein',          city: 'Hamburg',    country: 'Germany', status: 'verified', weightClass: 'Lightweight',  record: '13-4', hue: 240 },
    ],
  },

  // ── BOGDAN GRAD ───────────────────────────────────────────────────────────
  'bogdan-grad': {
    id: 'bogdan-grad',
    name: 'Bogdan Grad',
    tagline_de: 'Grazer Heavyweight-Maschine — Dominanter Wrestler der OKTAGON-Liga',
    tagline_en: 'Graz Heavyweight machine — Dominant wrestler of the OKTAGON league',
    city: 'Graz',
    country: 'Austria',
    status: 'verified',
    styles: ['Wrestler', 'MMA'],
    weightClass: 'Heavyweight',
    record: '13-5-0',
    rating: 4.5,
    reviews: 0,
    tags: ['OKTAGON', 'Heavyweight', 'Steiermark', 'Österreich'],
    gallery: [
      { hue: 105, a: '#0A1A00', b: '#1A3D00' },
      { hue: 115, a: '#081500', b: '#153000' },
      { hue: 95,  a: '#0D1A00', b: '#1F3D00' },
      { hue: 120, a: '#0A1A08', b: '#1A3D10' },
      { hue: 100, a: '#0A1500', b: '#1A2D00' },
    ],
    nextFight: {
      opponent_de: 'Ondřej Novák',
      opponent_en: 'Ondřej Novák',
      date_de: '14. Juni 2026',
      date_en: 'June 14, 2026',
      event: 'OKTAGON 60',
      location: 'Wien, Österreich',
    },
    fightHistory: [
      { opponent: 'Martin Šolc',        result: 'W', method: 'KO/TKO',  event: 'OKTAGON 55',   date: '2025-11-15', round: 2, time: '4:12' },
      { opponent: 'Petr Kníže',         result: 'W', method: 'Decision', event: 'OKTAGON 52',  date: '2025-06-07', round: 3, time: '5:00' },
      { opponent: 'Mounir el Harrachi', result: 'L', method: 'Decision', event: 'OKTAGON 49',  date: '2025-01-18', round: 3, time: '5:00' },
      { opponent: 'Radek Roušal',       result: 'W', method: 'Submission', event: 'OKTAGON 45', date: '2024-08-24', round: 1, time: '3:22' },
      { opponent: 'Roman Šimánek',      result: 'W', method: 'Decision', event: 'OKTAGON 42',  date: '2024-03-16', round: 3, time: '5:00' },
    ],
    stats: {
      age: 30,
      height: '191 cm',
      reach: '198 cm',
      stance: 'Orthodox',
      nationality: 'Österreichisch',
      gym: 'MMA Graz',
      born: 'Graz, Österreich',
    },
    reviews_list: [],
    career_log: [
      { date: '2025-11-15', event_de: 'OKTAGON 55 — Sieg über Martin Šolc (KO)', event_en: 'OKTAGON 55 — Win over Martin Šolc (KO)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'rodrigo-nascimento', name: 'Rodrigo Nascimento', city: 'Wien',      country: 'Austria', status: 'verified', weightClass: 'Heavyweight', record: '10-2', hue: 300 },
      { id: 'aleksandar-rakic',   name: 'Aleksandar Rakić',   city: 'Wien',      country: 'Austria', status: 'verified', weightClass: 'Light Heavyweight', record: '14-4', hue: 42 },
    ],
  },

  // ── RODRIGO NASCIMENTO ────────────────────────────────────────────────────
  'rodrigo-nascimento': {
    id: 'rodrigo-nascimento',
    name: 'Rodrigo Nascimento',
    tagline_de: 'Brasilianischer UFC-Heavyweight mit Wohnsitz Wien',
    tagline_en: 'Brazilian UFC Heavyweight based in Vienna',
    city: 'Wien',
    country: 'Austria',
    status: 'verified',
    styles: ['Wrestler', 'BJJ'],
    weightClass: 'Heavyweight',
    record: '10-2-0',
    rating: 4.6,
    reviews: 0,
    tags: ['UFC', 'Heavyweight', 'Wien', 'Brasilien', 'BJJ'],
    gallery: [
      { hue: 300, a: '#1A001A', b: '#3D003D' },
      { hue: 310, a: '#150015', b: '#2D002D' },
      { hue: 290, a: '#1A0015', b: '#3D0030' },
      { hue: 315, a: '#1A001A', b: '#3D003D' },
      { hue: 285, a: '#120012', b: '#280028' },
    ],
    nextFight: {
      opponent_de: 'TBD',
      opponent_en: 'TBD',
      date_de: 'Q3 2026',
      date_en: 'Q3 2026',
      event: 'UFC',
      location: 'TBD',
    },
    fightHistory: [
      { opponent: 'Chris Barnett',   result: 'W', method: 'KO/TKO',  event: 'UFC Fight Night', date: '2023-10-21', round: 1, time: '3:41' },
      { opponent: 'Jared Vanderaa',  result: 'W', method: 'Decision', event: 'UFC Fight Night', date: '2023-05-06', round: 3, time: '5:00' },
      { opponent: 'Alexandr Romanov',result: 'L', method: 'Decision', event: 'UFC Fight Night', date: '2022-10-15', round: 3, time: '5:00' },
      { opponent: 'Parker Porter',   result: 'W', method: 'Submission', event: 'UFC Fight Night', date: '2022-05-21', round: 1, time: '4:55' },
      { opponent: 'Chase Sherman',   result: 'W', method: 'KO/TKO',  event: 'UFC 278',         date: '2022-08-20', round: 1, time: '2:08' },
    ],
    stats: {
      age: 31,
      height: '193 cm',
      reach: '201 cm',
      stance: 'Orthodox',
      nationality: 'Brasilianisch-Österreichisch',
      gym: 'Factory X Wien',
      born: 'Fortaleza, Brasilien',
    },
    reviews_list: [],
    career_log: [
      { date: '2023-10-21', event_de: 'UFC Fight Night — Sieg über Chris Barnett (KO)', event_en: 'UFC Fight Night — Win over Chris Barnett (KO)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'bogdan-grad',        name: 'Bogdan Grad',       city: 'Graz',  country: 'Austria', status: 'verified', weightClass: 'Heavyweight', record: '13-5', hue: 105 },
      { id: 'aleksandar-rakic',   name: 'Aleksandar Rakić',  city: 'Wien',  country: 'Austria', status: 'verified', weightClass: 'Light Heavyweight', record: '14-4', hue: 42 },
    ],
  },

  // ── NICK HEIN ─────────────────────────────────────────────────────────────
  'nick-hein': {
    id: 'nick-hein',
    name: 'Nick Hein',
    tagline_de: 'UFC-Veteran und Judo-Weltmeister — Hamburg',
    tagline_en: 'UFC veteran and Judo World Champion — Hamburg',
    city: 'Hamburg',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'BJJ'],
    weightClass: 'Lightweight',
    record: '13-4-0',
    rating: 4.4,
    reviews: 0,
    tags: ['UFC', 'Judo', 'Lightweight', 'Hamburg', 'Deutschland'],
    gallery: [
      { hue: 240, a: '#0A0A1A', b: '#15153D' },
      { hue: 250, a: '#080815', b: '#10102D' },
      { hue: 230, a: '#0A0A20', b: '#151545' },
      { hue: 245, a: '#0A0A18', b: '#151535' },
      { hue: 235, a: '#080810', b: '#101025' },
    ],
    nextFight: {
      opponent_de: 'Comeback geplant 2026',
      opponent_en: 'Comeback planned 2026',
      date_de: 'TBD 2026',
      date_en: 'TBD 2026',
      event: 'TBD',
      location: 'Hamburg',
    },
    fightHistory: [
      { opponent: 'Dan Moret',       result: 'W', method: 'Decision', event: 'UFC Fight Night', date: '2018-07-28', round: 3, time: '5:00' },
      { opponent: 'Stevie Ray',      result: 'L', method: 'Decision', event: 'UFC Fight Night', date: '2017-09-02', round: 3, time: '5:00' },
      { opponent: 'Damien Brown',    result: 'W', method: 'Decision', event: 'UFC 215',         date: '2017-09-09', round: 3, time: '5:00' },
      { opponent: 'Alan Jouban',     result: 'W', method: 'Decision', event: 'UFC Fight Night', date: '2016-02-27', round: 3, time: '5:00' },
    ],
    stats: {
      age: 38,
      height: '180 cm',
      reach: '183 cm',
      stance: 'Orthodox',
      nationality: 'Deutsch',
      gym: 'Grappling Industries Hamburg',
      born: 'Hamburg',
    },
    reviews_list: [],
    career_log: [
      { date: '2018-07-28', event_de: 'UFC Fight Night — Sieg über Dan Moret (Decision)', event_en: 'UFC Fight Night — Win over Dan Moret (Decision)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'kerim-engizek',    name: 'Kerim Engizek',    city: 'Düsseldorf', country: 'Germany', status: 'verified', weightClass: 'Lightweight',   record: '45-8',  hue: 180 },
      { id: 'dennis-siver',     name: 'Dennis Siver',      city: 'München',    country: 'Germany', status: 'verified', weightClass: 'Featherweight', record: '24-13', hue: 280 },
    ],
  },

  // ── FLORIAN ABERGER ───────────────────────────────────────────────────────
  'florian-aberger': {
    id: 'florian-aberger',
    name: 'Florian Aberger',
    tagline_de: 'Österreichs Knockout-Spezialist — 9-1-0 mit 67% Finishrate',
    tagline_en: "Austria's knockout specialist — 9-1-0 with 67% finish rate",
    city: 'Graz',
    country: 'Austria',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    weightClass: 'Middleweight',
    record: '9-1-0',
    rating: 4.4,
    reviews: 0,
    tags: ['REGIONAL', 'Middleweight', 'Steiermark', 'IMMAF'],
    gallery: [
      { hue: 90, a: '#001A00', b: '#003D00' },
      { hue: 100, a: '#001500', b: '#002E00' },
      { hue: 80,  a: '#0A1A00', b: '#183D00' },
      { hue: 95,  a: '#001800', b: '#003500' },
      { hue: 85,  a: '#001200', b: '#002800' },
    ],
    nextFight: {
      opponent_de: 'TBD',
      opponent_en: 'TBD',
      date_de: '2026',
      date_en: '2026',
      event: 'Fight Event Austria',
      location: 'Graz',
    },
    fightHistory: [
      { opponent: 'Jorge Bueno',       result: 'W', method: 'Decision', event: 'Regional MMA AT',         date: '2023-09-16', round: 3, time: '5:00' },
      { opponent: 'Markus Hofer',      result: 'W', method: 'KO/TKO',   event: 'Fight Event Austria 12',  date: '2023-03-18', round: 1, time: '2:14' },
      { opponent: 'Ivan Petrov',       result: 'W', method: 'KO/TKO',   event: 'CAGE SPORT 29',           date: '2022-10-08', round: 2, time: '3:45' },
      { opponent: 'Stefan Müllner',    result: 'W', method: 'Decision', event: 'Fight Event Austria 10',  date: '2022-05-21', round: 3, time: '5:00' },
      { opponent: 'Daniel Rohrbach',   result: 'W', method: 'Submission',event: 'CAGE SPORT 26',          date: '2021-11-13', round: 2, time: '4:02' },
      { opponent: 'Tobias Kirchner',   result: 'L', method: 'Decision', event: 'OKTAGON Qualifier',       date: '2021-05-08', round: 3, time: '5:00' },
      { opponent: 'Luka Pajić',        result: 'W', method: 'KO/TKO',   event: 'Fight Event Austria 8',   date: '2020-10-03', round: 1, time: '1:58' },
      { opponent: 'Patrick Leitner',   result: 'W', method: 'KO/TKO',   event: 'IMMAF European Open',     date: '2019-04-20', round: 2, time: '3:11' },
    ],
    stats: {
      age: 30,
      height: '185 cm',
      reach: '188 cm',
      stance: 'Orthodox',
      nationality: 'Österreichisch',
      gym: 'Graz MMA Academy',
      born: 'Graz, Österreich',
    },
    reviews_list: [],
    career_log: [
      { date: '2023-09-16', event_de: 'Regional MMA AT — Sieg über Jorge Bueno (Decision)', event_en: 'Regional MMA AT — Win over Jorge Bueno (Decision)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2019-04-20', event_de: 'IMMAF European Open 2019 — Vertreter Österreichs', event_en: 'IMMAF European Open 2019 — Representing Austria', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'bogdan-grad',         name: 'Bogdan Grad',        city: 'Graz',    country: 'Austria', status: 'verified', weightClass: 'Heavyweight',      record: '13-5', hue: 105 },
      { id: 'rodrigo-nascimento',  name: 'Rodrigo Nascimento', city: 'Wien',    country: 'Austria', status: 'verified', weightClass: 'Heavyweight',      record: '10-2', hue: 300 },
    ],
  },

  // ── WILHELM OTT ───────────────────────────────────────────────────────────
  'wilhelm-ott': {
    id: 'wilhelm-ott',
    name: 'Wilhelm Ott',
    tagline_de: 'The Austrian Nightmare — 40 Profikämpfe, Veteran der europäischen Szene',
    tagline_en: 'The Austrian Nightmare — 40 pro fights, European scene veteran',
    city: 'Linz',
    country: 'Austria',
    status: 'self',
    styles: ['Striker', 'MMA'],
    weightClass: 'Middleweight',
    record: '19-19-1',
    rating: 4.0,
    reviews: 0,
    tags: ['REGIONAL', 'Middleweight', 'Linz', 'BKFC'],
    gallery: [
      { hue: 220, a: '#0A0A1A', b: '#1A1A3D' },
      { hue: 230, a: '#080818', b: '#141430' },
      { hue: 210, a: '#0A0E1A', b: '#1A1E3D' },
      { hue: 225, a: '#080A18', b: '#14163A' },
      { hue: 215, a: '#0A0C1A', b: '#1A1C3D' },
    ],
    nextFight: {
      opponent_de: 'TBD',
      opponent_en: 'TBD',
      date_de: '2026',
      date_en: '2026',
      event: 'Regional MMA',
      location: 'Linz',
    },
    fightHistory: [
      { opponent: 'Andreas Peuker',   result: 'W', method: 'KO/TKO',    event: 'EFM 5',                  date: '2022-04-09', round: 2, time: '0:45' },
      { opponent: 'Michał Materla',   result: 'L', method: 'Submission', event: 'EFM 3',                  date: '2020-06-20', round: 1, time: '1:04' },
      { opponent: 'Dominik Thalhammer',result: 'W',method: 'KO/TKO',    event: 'Fight Event Austria 9',  date: '2019-11-16', round: 1, time: '3:22' },
      { opponent: 'Viktor Horak',     result: 'L', method: 'Decision',   event: 'CAGE SPORT 22',          date: '2019-05-11', round: 3, time: '5:00' },
      { opponent: 'Sasa Radovic',     result: 'W', method: 'Decision',   event: 'Regional MMA AT',        date: '2018-10-06', round: 3, time: '5:00' },
      { opponent: 'Niklas Brandt',    result: 'L', method: 'Decision',   event: 'CAGE SPORT 18',          date: '2018-03-17', round: 3, time: '5:00' },
      { opponent: 'Marco Steininger', result: 'W', method: 'Submission', event: 'Fight Event Austria 7',  date: '2017-09-23', round: 2, time: '2:48' },
      { opponent: 'Peter Grill',      result: 'D', method: 'Draw',       event: 'Austrian MMA Open',      date: '2017-04-15', round: 3, time: '5:00' },
    ],
    stats: {
      age: 38,
      height: '182 cm',
      reach: '185 cm',
      stance: 'Orthodox',
      nationality: 'Österreichisch',
      gym: 'MMA Linz',
      born: 'Linz, Österreich',
    },
    reviews_list: [],
    career_log: [
      { date: '2022-04-09', event_de: 'EFM 5 — KO-Sieg über Andreas Peuker (R2)', event_en: 'EFM 5 — KO win over Andreas Peuker (R2)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2020-06-20', event_de: 'EFM 3 — Niederlage gegen Ex-KSW-Champion Michał Materla', event_en: 'EFM 3 — Loss to ex-KSW champion Michał Materla', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'florian-aberger', name: 'Florian Aberger', city: 'Graz', country: 'Austria', status: 'verified', weightClass: 'Middleweight', record: '9-1', hue: 90 },
      { id: 'ismail-naurdiev', name: 'Ismail Naurdiev',  city: 'Wien', country: 'Austria', status: 'verified', weightClass: 'Welterweight',  record: '16-4', hue: 210 },
    ],
  },

  // ── DANIEL WEICHEL ────────────────────────────────────────────────────────
  'daniel-weichel': {
    id: 'daniel-weichel',
    name: 'Daniel Weichel',
    tagline_de: 'Bellator Season 10 Turnier-Champion — M-1 Global Lightweight Champion',
    tagline_en: 'Bellator Season 10 Tournament Champion — M-1 Global Lightweight Champion',
    city: 'Frankfurt',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    weightClass: 'Featherweight',
    record: '45-14-0',
    rating: 4.5,
    reviews: 0,
    tags: ['Bellator', 'OKTAGON', 'Featherweight', 'M-1 Global', 'Champion'],
    gallery: [
      { hue: 15, a: '#1A0A00', b: '#3D1800' },
      { hue: 20, a: '#1F0C00', b: '#3D1A00' },
      { hue: 10, a: '#1A0800', b: '#3A1200' },
      { hue: 25, a: '#1A0E00', b: '#3D1E00' },
      { hue: 12, a: '#150800', b: '#301500' },
    ],
    nextFight: {
      opponent_de: 'TBD',
      opponent_en: 'TBD',
      date_de: '2026',
      date_en: '2026',
      event: 'OKTAGON MMA',
      location: 'TBD',
    },
    fightHistory: [
      { opponent: 'Aboubakar Tounkara', result: 'W', method: 'Decision', event: 'OKTAGON 76',      date: '2025-09-20', round: 3, time: '5:00' },
      { opponent: 'Mads Burnell',        result: 'L', method: 'Decision', event: 'Bellator 299',    date: '2023-09-23', round: 3, time: '5:00' },
      { opponent: 'Emmanuel Dawa',       result: 'W', method: 'Decision', event: 'OKTAGON 46',      date: '2022-11-19', round: 3, time: '5:00' },
      { opponent: 'Patricky Freire',     result: 'L', method: 'Decision', event: 'Bellator 281',    date: '2022-05-06', round: 3, time: '5:00' },
      { opponent: 'Emmanuel Sanchez',    result: 'L', method: 'Decision', event: 'Bellator 253',    date: '2020-11-19', round: 3, time: '5:00' },
      { opponent: 'Pedro Carvalho',      result: 'W', method: 'Decision', event: 'Bellator 242',    date: '2020-07-16', round: 3, time: '5:00' },
      { opponent: 'Saul Rogers',         result: 'W', method: 'KO/TKO',   event: 'Bellator 220',    date: '2019-04-27', round: 1, time: '2:43' },
      { opponent: 'Patricio Freire',     result: 'L', method: 'Decision', event: 'Bellator 148',    date: '2016-01-16', round: 5, time: '5:00' },
    ],
    stats: {
      age: 41,
      height: '176 cm',
      reach: '179 cm',
      stance: 'Orthodox',
      nationality: 'Deutsch',
      gym: 'MMA Spirit',
      born: 'Kaiserslautern, Deutschland',
    },
    reviews_list: [],
    career_log: [
      { date: '2025-09-20', event_de: 'OKTAGON 76 — Sieg über Aboubakar Tounkara (Decision)', event_en: 'OKTAGON 76 — Win over Aboubakar Tounkara (Decision)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2014-11-15', event_de: 'Bellator Season 10 — Turnier-Champion im Federgewicht', event_en: 'Bellator Season 10 — Featherweight Tournament Champion', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2011-05-01', event_de: 'M-1 Global — Lightweight Champion', event_en: 'M-1 Global — Lightweight Champion', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'christian-eckerlin', name: 'Christian Eckerlin', city: 'Frankfurt', country: 'Germany', status: 'verified', weightClass: 'Middleweight', record: '28-15', hue: 0 },
      { id: 'dennis-siver',       name: 'Dennis Siver',       city: 'München',   country: 'Germany', status: 'verified', weightClass: 'Featherweight', record: '24-13', hue: 280 },
    ],
  },

  // ── JOILTON LUTTERBACH ────────────────────────────────────────────────────
  'joilton-lutterbach': {
    id: 'joilton-lutterbach',
    name: 'Joilton Lutterbach',
    tagline_de: 'Ehemaliger UFC-Fighter — 41 Profikämpfe im Mittelgewicht',
    tagline_en: 'Former UFC fighter — 41 pro fights at Middleweight',
    city: 'Köln',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'MMA'],
    weightClass: 'Middleweight',
    record: '41-11-0',
    rating: 4.3,
    reviews: 0,
    tags: ['UFC', 'OKTAGON', 'Middleweight', 'Köln'],
    gallery: [
      { hue: 170, a: '#001A18', b: '#003D33' },
      { hue: 175, a: '#001512', b: '#003028' },
      { hue: 165, a: '#001A15', b: '#003D2D' },
      { hue: 172, a: '#001A16', b: '#003D30' },
      { hue: 168, a: '#001514', b: '#003028' },
    ],
    nextFight: {
      opponent_de: 'TBD — Rückkehr geplant nach Sperre (Juni 2026)',
      opponent_en: 'TBD — Return planned after suspension (June 2026)',
      date_de: '2026',
      date_en: '2026',
      event: 'OKTAGON MMA',
      location: 'TBD',
    },
    fightHistory: [
      { opponent: 'Kaik Brito',        result: 'L', method: 'KO/TKO',    event: 'OKTAGON 73',      date: '2025-06-28', round: 1, time: '1:43' },
      { opponent: 'Mauricio Otalora',   result: 'W', method: 'Submission', event: 'RFA 18',          date: '2024-10-19', round: 2, time: '3:15' },
      { opponent: 'Manuelo Morales',    result: 'W', method: 'KO/TKO',    event: 'Falcon MMA 3',    date: '2024-08-10', round: 1, time: '0:40' },
      { opponent: 'Nico Yamamoto',      result: 'W', method: 'Decision',  event: 'PFL Europe',      date: '2023-05-20', round: 3, time: '5:00' },
      { opponent: 'Kyle Daukaus',       result: 'L', method: 'Decision',  event: 'UFC Fight Night', date: '2022-08-06', round: 3, time: '5:00' },
      { opponent: 'Roman Dolidze',      result: 'L', method: 'KO/TKO',   event: 'UFC Fight Night', date: '2021-10-02', round: 1, time: '4:23' },
      { opponent: 'Jordan Wright',      result: 'W', method: 'KO/TKO',   event: 'UFC Fight Night', date: '2021-07-17', round: 2, time: '2:02' },
      { opponent: 'Oskar Piechota',     result: 'W', method: 'Decision',  event: 'UFC on ESPN',     date: '2021-02-27', round: 3, time: '5:00' },
    ],
    stats: {
      age: 38,
      height: '185 cm',
      reach: '190 cm',
      stance: 'Orthodox',
      nationality: 'Deutsch-Brasilianisch',
      gym: 'Kampfsportzentrum Köln',
      born: 'São Paulo, Brasilien',
    },
    reviews_list: [],
    career_log: [
      { date: '2025-06-28', event_de: 'OKTAGON 73 — Niederlage vs Kaik Brito (KO R1)', event_en: 'OKTAGON 73 — Loss to Kaik Brito (KO R1)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2022-08-06', event_de: 'UFC Fight Night — letzter UFC-Auftritt vs Kyle Daukaus', event_en: 'UFC Fight Night — last UFC appearance vs Kyle Daukaus', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2021-02-27', event_de: 'UFC on ESPN — Sieg über Oskar Piechota (Decision)', event_en: 'UFC on ESPN — Win over Oskar Piechota (Decision)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'christian-eckerlin', name: 'Christian Eckerlin', city: 'Frankfurt', country: 'Germany', status: 'verified', weightClass: 'Middleweight', record: '28-15', hue: 0 },
      { id: 'daniel-weichel',     name: 'Daniel Weichel',     city: 'Frankfurt', country: 'Germany', status: 'verified', weightClass: 'Featherweight', record: '45-14', hue: 15 },
    ],
  },

  // ── FRÉDÉRIC VOSGRÖNE ─────────────────────────────────────────────────────
  'frederic-vosgrone': {
    id: 'frederic-vosgrone',
    name: 'Frédéric Vosgröne',
    tagline_de: 'BJJ-Weltmeister — 5-0-0, 100% Finishrate, OKTAGON-Newcomer des Jahres',
    tagline_en: 'BJJ World Champion — 5-0-0, 100% finish rate, OKTAGON newcomer of the year',
    city: 'Düsseldorf',
    country: 'Germany',
    status: 'verified',
    styles: ['BJJ', 'Grappler'],
    weightClass: 'Light Heavyweight',
    record: '5-0-0',
    rating: 4.6,
    reviews: 0,
    tags: ['OKTAGON', 'Light Heavyweight', 'BJJ World Champ', 'ADCC', 'Undefeated'],
    gallery: [
      { hue: 270, a: '#0D001A', b: '#20003D' },
      { hue: 280, a: '#0A0015', b: '#1A0030' },
      { hue: 260, a: '#0D001A', b: '#1D0035' },
      { hue: 275, a: '#0C0018', b: '#1E003A' },
      { hue: 265, a: '#0A0015', b: '#18002D' },
    ],
    nextFight: {
      opponent_de: 'Samuel Chavarría',
      opponent_en: 'Samuel Chavarría',
      date_de: '2026',
      date_en: '2026',
      event: 'OKTAGON 83',
      location: 'Stuttgart',
    },
    fightHistory: [
      { opponent: 'Fabio Moraes',          result: 'W', method: 'Submission', event: 'OKTAGON 76',         date: '2025-09-20', round: 1, time: '2:18' },
      { opponent: 'Lucas Alsina',           result: 'W', method: 'Submission', event: 'OKTAGON 72',         date: '2025-05-17', round: 1, time: '3:44' },
      { opponent: 'Christian Fischer',      result: 'W', method: 'Submission', event: 'We Love MMA 74',     date: '2024-11-09', round: 2, time: '1:55' },
      { opponent: 'Tom Breese',             result: 'W', method: 'Submission', event: 'Levels Fight League 17', date: '2024-06-15', round: 1, time: '4:02' },
      { opponent: 'Hamza Azzaoui',          result: 'W', method: 'Submission', event: 'We Love MMA 68',     date: '2024-02-03', round: 1, time: '2:33' },
    ],
    stats: {
      age: 29,
      height: '190 cm',
      reach: '194 cm',
      stance: 'Orthodox',
      nationality: 'Deutsch',
      gym: 'Xtreme Couture Düsseldorf',
      born: 'Düsseldorf, Deutschland',
    },
    reviews_list: [],
    career_log: [
      { date: '2025-09-20', event_de: 'OKTAGON 76 — Sieg über Fabio Moraes (Submission R1)', event_en: 'OKTAGON 76 — Win over Fabio Moraes (Submission R1)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2024-01-01', event_de: 'No-Gi World Championship — Titel im Light Heavyweight', event_en: 'No-Gi World Championship — Light Heavyweight title', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2023-06-01', event_de: 'ADCC European Trials — Qualifikation für Hauptturnier', event_en: 'ADCC European Trials — Qualified for main event', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'kerim-engizek',    name: 'Kerim Engizek',    city: 'Düsseldorf', country: 'Germany', status: 'verified', weightClass: 'Lightweight',       record: '45-8', hue: 180 },
      { id: 'joilton-lutterbach',name: 'Joilton Lutterbach',city: 'Köln',    country: 'Germany', status: 'verified', weightClass: 'Middleweight',      record: '41-11', hue: 170 },
    ],
  },

  // ── SASCHA SHARMA ─────────────────────────────────────────────────────────
  'sascha-sharma': {
    id: 'sascha-sharma',
    name: 'Sascha Sharma',
    tagline_de: 'The Ultimate Fighter Season 22 — Leichtgewichts-Veteran aus Pforzheim',
    tagline_en: 'The Ultimate Fighter Season 22 — Lightweight veteran from Pforzheim',
    city: 'Stuttgart',
    country: 'Germany',
    status: 'verified',
    styles: ['Striker', 'BJJ'],
    weightClass: 'Lightweight',
    record: '17-5-0',
    rating: 4.1,
    reviews: 0,
    tags: ['TUF', 'Lightweight', 'Pforzheim', "Kong's Gym"],
    gallery: [
      { hue: 35, a: '#1A1200', b: '#3D2A00' },
      { hue: 40, a: '#1A1400', b: '#3D2E00' },
      { hue: 30, a: '#1A1000', b: '#3D2200' },
      { hue: 38, a: '#1A1300', b: '#3D2C00' },
      { hue: 32, a: '#1A1100', b: '#3D2500' },
    ],
    nextFight: {
      opponent_de: 'TBD',
      opponent_en: 'TBD',
      date_de: '2026',
      date_en: '2026',
      event: 'National Fighting Championship',
      location: 'Deutschland',
    },
    fightHistory: [
      { opponent: 'Saba Bolaghi',         result: 'W', method: 'Decision',  event: 'National Fighting Championship 2', date: '2020-09-19', round: 3, time: '5:00' },
      { opponent: 'Chris Gruetzemacher',   result: 'L', method: 'Decision',  event: 'The Ultimate Fighter 22',          date: '2015-12-04', round: 3, time: '5:00' },
      { opponent: 'Henrique Bernardo',     result: 'W', method: 'KO/TKO',    event: 'NFC 3',                            date: '2019-04-13', round: 2, time: '3:28' },
      { opponent: 'Alexander Jacobsen',    result: 'W', method: 'Decision',  event: 'NFC 2',                            date: '2018-10-20', round: 3, time: '5:00' },
      { opponent: 'Kevin Piché',           result: 'L', method: 'Decision',  event: 'NFC 1',                            date: '2018-03-10', round: 3, time: '5:00' },
      { opponent: 'Juan Torres',           result: 'W', method: 'Submission', event: 'Kong\'s Gym Fight Night',         date: '2017-09-16', round: 1, time: '2:50' },
      { opponent: 'Marcel Haase',          result: 'W', method: 'KO/TKO',    event: 'Warriors Fighting Championship',  date: '2017-04-08', round: 1, time: '1:44' },
      { opponent: 'Gregor Herb',           result: 'W', method: 'Decision',  event: 'WFC 3',                           date: '2016-09-24', round: 3, time: '5:00' },
    ],
    stats: {
      age: 36,
      height: '175 cm',
      reach: '178 cm',
      stance: 'Orthodox',
      nationality: 'Deutsch',
      gym: "Kong's Gym Pforzheim",
      born: 'Pforzheim, Deutschland',
    },
    reviews_list: [],
    career_log: [
      { date: '2020-09-19', event_de: 'NFC 2 — Sieg über Saba Bolaghi (Decision)', event_en: 'NFC 2 — Win over Saba Bolaghi (Decision)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2015-12-04', event_de: 'The Ultimate Fighter Season 22 — Teilnahme am Finale', event_en: 'The Ultimate Fighter Season 22 — Participated in the finale', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'nick-hein',     name: 'Nick Hein',     city: 'Hamburg',    country: 'Germany', status: 'verified', weightClass: 'Lightweight',  record: '13-4', hue: 240 },
      { id: 'daniel-weichel',name: 'Daniel Weichel', city: 'Frankfurt', country: 'Germany', status: 'verified', weightClass: 'Featherweight', record: '45-14', hue: 15 },
    ],
  },

  // ── SEBASTIAN HOLZMANN ────────────────────────────────────────────────────
  'sebastian-holzmann': {
    id: 'sebastian-holzmann',
    name: 'Sebastian Holzmann',
    tagline_de: 'Regionalliga-Fighter aus Halle — 6-2-0, Leichtgewicht',
    tagline_en: 'Regional league fighter from Halle — 6-2-0, Lightweight',
    city: 'Leipzig',
    country: 'Germany',
    status: 'self',
    styles: ['Striker', 'MMA'],
    weightClass: 'Lightweight',
    record: '6-2-0',
    rating: 3.9,
    reviews: 0,
    tags: ['REGIONAL', 'Lightweight', 'Halle', 'Sachsen-Anhalt'],
    gallery: [
      { hue: 200, a: '#001218', b: '#002030' },
      { hue: 205, a: '#000E14', b: '#001828' },
      { hue: 195, a: '#00101A', b: '#001E30' },
      { hue: 202, a: '#001018', b: '#001E2E' },
      { hue: 198, a: '#000E16', b: '#001A2C' },
    ],
    nextFight: {
      opponent_de: 'TBD — Rückkehr nach Pause',
      opponent_en: 'TBD — Return after hiatus',
      date_de: '2026',
      date_en: '2026',
      event: 'Regional MMA DE',
      location: 'Halle / Leipzig',
    },
    fightHistory: [
      { opponent: 'Louis Glismann',   result: 'L', method: 'Decision',   event: 'Vogtländer Fight Night 2', date: '2018-10-06', round: 3, time: '5:00' },
      { opponent: 'Kevin Ruart',      result: 'W', method: 'Decision',   event: 'WSFC 3',                   date: '2017-05-20', round: 3, time: '5:00' },
      { opponent: 'Rico Steinbach',   result: 'W', method: 'KO/TKO',     event: 'WFC 4',                    date: '2016-11-12', round: 1, time: '2:15' },
      { opponent: 'Jonas Brandt',     result: 'L', method: 'Submission', event: 'La Familia Fight Night 6', date: '2015-09-19', round: 2, time: '3:44' },
      { opponent: 'Sören Keil',       result: 'W', method: 'Decision',   event: 'La Familia Fight Night 5', date: '2014-10-11', round: 3, time: '5:00' },
      { opponent: 'Mathias Delf',     result: 'W', method: 'KO/TKO',     event: 'La Familia Fight Night 4', date: '2013-05-18', round: 2, time: '1:32' },
    ],
    stats: {
      age: 35,
      height: '178 cm',
      reach: '181 cm',
      stance: 'Orthodox',
      nationality: 'Deutsch',
      gym: 'Halle MMA Team',
      born: 'Halle, Deutschland',
    },
    reviews_list: [],
    career_log: [
      { date: '2018-10-06', event_de: 'Vogtländer Fight Night 2 — Letzter Kampf (Niederlage Decision)', event_en: 'Vogtländer Fight Night 2 — Last fight (Decision loss)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
      { date: '2013-05-18', event_de: 'La Familia Fight Night 4 — Profidebüt-Sieg über Mathias Delf', event_en: 'La Familia Fight Night 4 — Pro debut win over Mathias Delf', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'sascha-sharma',  name: 'Sascha Sharma',  city: 'Stuttgart', country: 'Germany', status: 'verified', weightClass: 'Lightweight', record: '17-5', hue: 35 },
      { id: 'nick-hein',      name: 'Nick Hein',       city: 'Hamburg',   country: 'Germany', status: 'verified', weightClass: 'Lightweight', record: '13-4', hue: 240 },
    ],
  },

  // ── DENNIS SIVER ──────────────────────────────────────────────────────────
  'dennis-siver': {
    id: 'dennis-siver',
    name: 'Dennis Siver',
    tagline_de: 'UFC Featherweight Veteran — Münchner Kickboxer mit Weltklasse-Karate',
    tagline_en: 'UFC Featherweight veteran — Munich kickboxer with world-class karate',
    city: 'München',
    country: 'Germany',
    status: 'verified',
    styles: ['Kickboxer', 'Striker'],
    weightClass: 'Featherweight',
    record: '24-13-0',
    rating: 4.3,
    reviews: 0,
    tags: ['UFC', 'Featherweight', 'München', 'Karate', 'Veteran'],
    gallery: [
      { hue: 280, a: '#1A0A1A', b: '#3D1A3D' },
      { hue: 290, a: '#150815', b: '#2D152D' },
      { hue: 270, a: '#1A0A20', b: '#3D1A45' },
      { hue: 285, a: '#1A0A18', b: '#3D1A35' },
      { hue: 275, a: '#180810', b: '#351025' },
    ],
    nextFight: {
      opponent_de: 'Zurückgetreten — Legende des deutschen MMA',
      opponent_en: 'Retired — Legend of German MMA',
      date_de: '—',
      date_en: '—',
      event: '—',
      location: 'München',
    },
    fightHistory: [
      { opponent: 'Myles Jury',     result: 'L', method: 'Decision', event: 'UFC Fight Night', date: '2018-09-22', round: 3, time: '5:00' },
      { opponent: 'Conor McGregor', result: 'L', method: 'KO/TKO',  event: 'UFC Boston',      date: '2015-01-18', round: 2, time: '1:54' },
      { opponent: 'Jimy Hette',     result: 'W', method: 'Decision', event: 'UFC Fight Night', date: '2014-07-26', round: 3, time: '5:00' },
      { opponent: 'Manny Gamburyan',result: 'W', method: 'KO/TKO',  event: 'UFC Fight Night', date: '2014-01-25', round: 1, time: '3:05' },
    ],
    stats: {
      age: 41,
      height: '175 cm',
      reach: '177 cm',
      stance: 'Southpaw',
      nationality: 'Russisch-Deutsch',
      gym: 'Team Siver München',
      born: 'Omsk, Russland',
    },
    reviews_list: [],
    career_log: [
      { date: '2015-01-18', event_de: 'UFC Boston — Kampf gegen Conor McGregor (Niederlage KO)', event_en: 'UFC Boston — Fight vs Conor McGregor (Loss KO)', actor_de: 'FightFolio-Team', actor_en: 'FightFolio team' },
    ],
    similar: [
      { id: 'christian-eckerlin', name: 'Christian Eckerlin', city: 'Frankfurt', country: 'Germany', status: 'verified', weightClass: 'Middleweight', record: '28-15', hue: 0 },
      { id: 'nick-hein',          name: 'Nick Hein',          city: 'Hamburg',   country: 'Germany', status: 'verified', weightClass: 'Lightweight',  record: '13-4', hue: 240 },
    ],
  },

};

const DETAIL_COPY = {
  de: {
    breadcrumb: ['Home', 'Kämpfer', ''],
    sections: {
      info: 'Über den Kämpfer',
      nextFight: 'Nächster Kampf',
      fightHistory: 'Kampfhistorie',
      reviews: 'Fan-Bewertungen',
      career: 'Karriere-Log',
      similar: 'Ähnliche Kämpfer',
      stats: 'Statistiken',
      address: 'Standort',
    },
    actions: {
      instagram: 'Instagram',
      share: 'Teilen',
      report: 'Fehler melden',
    },
    seeAllPhotos: 'Alle Fotos',
    reviewsCount: (n) => `${n} Bewertungen`,
    writeReview: 'Bewertung schreiben',
    statLabels: {
      age: 'Alter',
      height: 'Größe',
      reach: 'Spannweite',
      stance: 'Kampfhaltung',
      nationality: 'Nationalität',
      gym: 'Gym',
      born: 'Geburtsort',
    },
    resultLabels: { W: 'Sieg', L: 'Niederlage', NC: 'No Contest', D: 'Unentschieden' },
    nextFightLabels: {
      opponent: 'Gegner',
      date: 'Datum',
      event: 'Event',
      location: 'Ort',
    },
    noNextFight: 'Kein Kampf geplant',
    careerHistory: 'Karriere-Verlauf',
    statusBlurb: 'Dieser Kämpfer ist als verifizierter Profi in unserer Datenbank gelistet.',
    reportIssue: 'Fehler melden',
    minDirections: 'Profil teilen',
  },
  en: {
    breadcrumb: ['Home', 'Fighters', ''],
    sections: {
      info: 'About the Fighter',
      nextFight: 'Next Fight',
      fightHistory: 'Fight History',
      reviews: 'Fan Reviews',
      career: 'Career Log',
      similar: 'Similar Fighters',
      stats: 'Stats',
      address: 'Location',
    },
    actions: {
      instagram: 'Instagram',
      share: 'Share',
      report: 'Report error',
    },
    seeAllPhotos: 'See all photos',
    reviewsCount: (n) => `${n} reviews`,
    writeReview: 'Write a review',
    statLabels: {
      age: 'Age',
      height: 'Height',
      reach: 'Reach',
      stance: 'Stance',
      nationality: 'Nationality',
      gym: 'Gym',
      born: 'Born',
    },
    resultLabels: { W: 'Win', L: 'Loss', NC: 'No Contest', D: 'Draw' },
    nextFightLabels: {
      opponent: 'Opponent',
      date: 'Date',
      event: 'Event',
      location: 'Location',
    },
    noNextFight: 'No fight scheduled',
    careerHistory: 'Career Timeline',
    statusBlurb: 'This fighter is listed as a verified professional in our database.',
    reportIssue: 'Report an issue',
    minDirections: 'Share profile',
  },
};

Object.assign(window, { VENUES, DETAIL_COPY });
